### ISSUE TITLE
Flow diagram of how backend will work for VSFS/unpaid internships (students and recent grads)

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#10]
**Old Trello URL:** https://trello.com/c/YSQSKZyR/164-flow-diagram-of-how-backend-will-work-for-vsfs-unpaid-internships-students-and-recent-grads

**Checklists:**

**Attachments:** 

[Screenshot 2018-03-13 10.16.45.png](https://trello-attachments.s3.amazonaws.com/59df9ff7b7b887ebae452662/5a8db7d43097aec8538b1659/7f660927e4b0e4523c6145d5edea663f/Screenshot_2018-03-13_10.16.45.png)

[Open Opps + State Intern Selection Flow 031518 v3.jpg](https://trello-attachments.s3.amazonaws.com/59df9ff7b7b887ebae452662/5a8db7d43097aec8538b1659/f868b7c1679b4bf56c71fab2212b93f5/Open_Opps_%2B_State_Intern_Selection_Flow_031518_v3.jpg)

[Open Opps + State Intern Selection Flow 031518 v3.pdf](https://trello-attachments.s3.amazonaws.com/59df9ff7b7b887ebae452662/5a8db7d43097aec8538b1659/791003ebfe7ac8f84a348a748e1a0d7e/Open_Opps_%2B_State_Intern_Selection_Flow_031518_v3.pdf)

**Comments:**

**Comment by humancompanion** [comment]
[Open Opps + State Intern Selection Flow 031518.pdf](https://github.com/openopps/OpenOppsTasks/files/2428505/Open.Opps.%2B.State.Intern.Selection.Flow.031518.pdf)

This is the flow of record until @benjawin and I can update it. We'll take this task.

**Comment by humancompanion** [comment]
Ben delivered this diagram.
