### ISSUE TITLE
Open Opps: Rewrite the Can't Access screen for StateVSFS

### ISSUE THREAD

**Issue by dalenard21** [openopps/OpenOppsTasks#103]
Include more content that explains they need to provide a valid federal email address (for federal employees).

**Comment by dalenard21** [comment]
@mchung07 @kbwagner I added some new language to the "Sorry you can't access this site" screen in invision. https://opm.invisionapp.com/d/#/console/14696610/311689703/comments

But, here's my edit:

Open Opportunities is only for current federal employees and students who are looking for internships.

If you are a federal employee, make sure your profile includes a valid federal email address and the federal employee hiring path.

If you are a student looking for an internship, make sure your profile includes the student hiring path.

Update your USAJOBS profile.

Go back to USAJOBS.
Go to the Open Opportunities Help Center.

**Comment by dalenard21** [comment]
@kbwagner @tlorrison @Lforeman22 

can we make a slight edit to the second paragraph?

Open Opportunities is only for current federal employees and students who are looking for internships.

If you are a federal employee, make sure your USAJOBS profile says that you’re a federal employee and includes your current agency and a verified federal email address. 

If you are a student looking for an internship, make sure your profile includes the student hiring path.

Update your USAJOBS profile.

Go back to USAJOBS.
Go to the Open Opportunities Help Center.

**Comment by kbwagner** [comment]
I'm ok with the above.

**Comment by kbwagner** [comment]
Confirmed no new design update needed.  Closing ticket.  Thanks Debbie.
