### ISSUE TITLE
Login.gov Email: Find my Open Opps Profile

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#104]
@dalenard21 did you already do content for the find my profile for Open Opps?  I don't see an issue but seems like I saw something at some point.  We have ticket 2454 - email content for find my open opps profile that needs content.  Brice went ahead and put in content and I'll try to replicate and get the email from test so I can see what's there now.

2454: 
User Story: As an Open Opportunities user, I want to be able to confirm I have access to my government email address in order to successfully link my Open Opps and USAJOBS profiles.

Acceptance Criteria:

When the user select the "Send email" button from the Find your Open Opportunities profile page, an email will be initiated:
To: Email address provided on the find profile page
From: OpenOpps@usajobs.gov
Subject:
Content:
Functionality:

Once the user clicks on the link within the email, their Open Opps and USAJOBS profiles will be linked.
Once the user is signed in they will be taken to the signed in landing page.
If the email does not exist in the system, no email will be sent.
Invision Mock:
https://opm.invisionapp.com/d/main#/console/14593252/311571044/preview#project_console

**Comment by dalenard21** [comment]
@kbwagner so, I did write  an email that talks about confirming their federal email address and linking their USAJOBS and Open  Opps profile.  Is this what we need?

[Open-opportunities-email-confirm-federal-email-address_20180809.docx](https://github.com/openopps/OpenOppsTasks/files/2384174/Open-opportunities-email-confirm-federal-email-address_20180809.docx)

**Comment by kbwagner** [comment]
Yes, I think that’s it just didn’t catch that it was combined….I’ll review and close

Katrina Wagner
U.S. Office of Personnel Management
USAJOBS Program Office
Katrina.Wagner@opm.gov
