### ISSUE TITLE
Review Open Opps Terms and Conditions link

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#105]
@tlorrison to check with Victor on requirements for Terms and Conditions.

- Terms and conditions seems to be required somewhere around the sign in
- If the login.gov transition page goes away, where does the terms and conditions link reside (@dalenard21 to check with Matt)
- The Current Open Opps terms and conditions appears to be more of a rules of engagement.  Possibly rename link and clean up?

https://usajobs.github.io/openopps-help/terms-and-conditions/

**Comment by humancompanion** [comment]
<img width="729" alt="screenshot 2018-09-20 13 54 57" src="https://user-images.githubusercontent.com/352987/45837224-d78d7880-bcdc-11e8-9215-aafd3c30398c.png">

login.gov has a "Security Practices and Privacy Act Statement" that links to https://www.login.gov/policy/ That looks to me to be their terms. It contains this line, which is a plain language version of what we have now:

> Unauthorized access or use of login.gov (e.g. use for criminal purposes, or to cause damage, etc.) is against the law, and may subject you to criminal prosecution and penalties.

If Victor says we need to maintain our own after the transition page goes away then I'd suggest we stick it in the list of small required links in the footer. That's where our privacy policy is right now on both core and openopps. 

I have a fourth bullet item to add: While we do currently host core's terms on the Help Center I do wonder about us hosting terms in the openopps-help given that is hosted on github. That seems a bit odd to me. The current terms start with:

> This U. S. Federal Government system is to be used by authorized users only.

But the system you are reading that on would not be a fed system. We should be getting permission to make DNS changes soon so OpenOpps help can have a proper URL. So perhaps it is a moot point and we just need to be patient. I'm okay with waiting it out if you are.

**Comment by kbwagner** [comment]
@tlorrison do you have any updates on this?  Do we need to do anything with the terms and conditions?

**Comment by Piglady64** [comment]
@tlorrison Please update this issue. If this has been taken care of we can close this if not we need to show some progress on this. There are two different Terms and Conditions and we need to decide if they need to be the same.

**Comment by tlorrison** [comment]
I've re-raised the issue with Victor and Quadrina, will update when I hear back.

**Comment by kbwagner** [comment]
@tlorrison any updates on terms and conditions?

**Comment by kbwagner** [comment]
3/16/21 - 
- ATP, USAJOBS, and Open Opps should have the same footer link for Terms and Conditions
- Looking into whether we can update the USAJOBS dashboard with this language at sign in as well

**Comment by kbwagner** [comment]
POA&M closed 4/1/2021
