### ISSUE TITLE
Design for Editing location

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#106]
Location will be edited on Open Opportunities and will not come from USAJOBS.
Need design for allowing the Open Opps user to edit location in their Open Opps profile.

Date Needed: This will go into sprint 4 of the current release.  Sprint planning will occur on 11/1

**Comment by humancompanion** [comment]
I need more information. When you say "will not come from USAJOBS" do you mean that it is not currently captured in the core profile? Or do you mean that we can't use our own Locations API? Or do you mean that it cannot come from core?

Seems like there are two needs here:
1. Define the data set to be used for locations. Is this already defined? Has Team PD reviewed it?
2. Define the interface for selecting and editing a location.

#### Questions around requirements
Where in the interface does this need to happen?

What level of data are we aiming for? I believe it is currently cities. Is it acceptable to select a town, state, country? 

What is the goal of the data? Is this mainly to allow folks to know where another person lives? Is that data we can/should share with everyone (and does that need to be approved by Privacy)?

Why is the user's current contact information city, state, and country unacceptable for these purposes?

**Comment by kbwagner** [comment]
Adding @tlorrison since some of this was discussions between her and Lisa.  
- USAJOBS uses work location.  Open Opps does not want location to be specific to work, home, or desired location even but generic.  So we can't pull it from the USAJOBS profile because it may be different.  So it can't come from Core
- to my knowledge PD has not reviewed the dataset for this.  
- Since most of the profile will be edited within USAJOBS, this will almost need it's own edit link that brings up some sort of modal and yes then you select.  Min may have started on some of this as well but had been waiting for the final answer on location.

Questions around requirements
Where in the interface does this need to happen?
- In the Open Opps profile
What level of data are we aiming for? I believe it is currently cities. Is it acceptable to select a town, state, country?
right now it's a select box for city, state which seems to be ok but yes I would say it's fine to add additional 

![image](https://user-images.githubusercontent.com/18709918/46302294-a7fd2c80-c576-11e8-8367-cbbd79f4a980.png)


What is the goal of the data? Is this mainly to allow folks to know where another person lives? Is that data we can/should share with everyone (and does that need to be approved by Privacy)?
since this platform is supposed to be kind of a linked in type of tool and allow for some networking...i would say it would be used for the purpose of seeing where someone is located (again though could be work or home).  Since the nature of the platform is to share then yes I think it would be fine to share the location if logged in.  Not sure about students but that's another fish to fry.  On the policy side - @tlorrison do we have someone on the open opps side we run policy questions through officially?

Why is the user's current contact information city, state, and country unacceptable for these purposes?
Just because (kidding).....I am told it's because USAJOBS makes location specific to home or work and Open Opps doesn't.  This was apparently very important but Tracy might be able to give better background.

**Comment by humancompanion** [comment]
The USAJOBS Contact Information in Profile does not specify work vs. home vs. other. I use my home address. The few folks I polled do the same. I'd argue that it isn't specific and thus would be appropriate to use. 

It's not clear to me which location you are attempting to capture in Open Opps. Is it also non-specific or it is specific to work or home? 

Another question: How will we make a case to avoid PRA (for the Student audience) given that we already gather a location for all users? This is literally a case of asking for the same information twice, which is what PRA is supposed to prevent. 

To be clear, the end goal for shared profile is to have no separate profile for Open Opps. Once Skills are added to Core that should remove the remaining barrier to achieving that goal. In other words, the screen captured in the previous screenshot should at that point go away. So any field we add to profile for Open Opps only is a field we'll later have to move to Core. Given that this would be added to Core in Contact Information we'd need to differentiate it from the information already gathered there. That presents a bit of a problem if both are not specific to a context (home or work).

Thus one could *maybe* make the case that we should allow users of Open Opps to edit how their contact information appears when sharing their profile with others. 

We could capture home and work, or be specific about which we are asking for in Core. For work, if we were to gather that I'd rather we get a data set that contained all agency locations and let folks pick after providing their agency.

**Comment by kbwagner** [comment]
@tlorrison need you to weigh in since this was a discussion with you, Lisa and Michelle.

**Comment by kbwagner** [comment]
@humancompanion @abudz19 @tlorrison here are the final decisions on location:
1) pull work location city and state from USAJOBS profile (most current row of work experience)
2) In Open Opps we will just call it "Location (current)
3) There will be an "Edit" specific to the location field and the user can edit it to make it whatever they want but it won't update on USAJOBS
4) Since work experience isn't required, if there is no location brought over will need the ability to add location on Open Opps.

**Comment by kbwagner** [comment]
@dalenard21 can you help see if we can find the design Min had done for this  The old links didnt' work so seemed to be archived or removed.

@abudz19 can you look into the design system and see if a Form Modal is still valid and would work for this?

**Comment by dalenard21** [comment]
@kbwagner can you enter the URL you're trying to access - the one going to an old design that doesn't work?  

@humancompanion did Min upload all of her design files/assets somewhere before she left?

**Comment by abudz19** [comment]
@kbwagner The form modal should work fine for adding location, design system specifies it's fine if it's 4 fields or shorter.

**Comment by kbwagner** [comment]
@dalenard21 sadly I just deleted them from this task and can't get it back.

**Comment by humancompanion** [comment]
@dalenard21 - All of Min's file are in the Google Drive. I don't believe she created a design for this. This directly violates our desire to have one Profile. Thus we don't have a great solution for this because a user in Open Opps should interact with their Profile via Core not Open Opps. Thus I need to spend time on this next week. Min and I did talk about it but we didn't resolve it because we don't agree with the directive.

**Comment by kbwagner** [comment]
This is resolved.  We will use the location from USAJOBS so any edits will be done on the USAJOBS profile.
