### ISSUE TITLE
Design for adding a community to an opportunity

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#108]
When a user creates an Open Opportunity, they should have the option of selecting a community to assign it to.
- May be left blank and will default to agency if left blank.

**Comment by humancompanion** [comment]
I need to upload Min's Sketch files to Figma for Alex to use.

**Comment by abudz19** [comment]
@humancompanion When I log into Figma my level of access is set to "can view."

**Comment by kbwagner** [comment]
@abudz19 - this is ticket 2624.  I think this can be closed unless you want to update the mock.
