### ISSUE TITLE
Design for backend/processing of State internships (ATP?)

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#109]
Design for what happens after someone applies for a state internship:
- Data goes to ATP
- Algorithm kicks in
- What happens in ATP?
- Where does Selection occur?
- What is sent back to Open Opps (selection/non selection)
- Communication points and which system sends them
- Is the opportunity closed out in Open Opps (Task Completed)

**Comment by kbwagner** [comment]
@humancompanion I think this one can be closed since it's covered in multiple places.  Wanted to check before I closed it to make sure you agree.

**Comment by humancompanion** [comment]
There seems to be some uncertainty about how the design will need to change depending on the algorithm choices in regards to alternates. But, at this point I think we'd open new issues to make the appropriate UI and diagram updates.
