### ISSUE TITLE
Create Adminstrator view of person's activity

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#110]
Your Opportunities has been moved to the signed in landing page
This should be moved back to the profile
- User view is ok - no complaints
- Admin needs to be able view this info

**Comment by kbwagner** [comment]
Per Tracy this is not a current priority.  Can discuss after State.

**Comment by humancompanion** [comment]
@mchung07 has updated this design. 

Home has your Saved Opportunities: https://opm.invisionapp.com/d/main/#/console/16603537/348759230/preview

Profile has Opportunities you've participated in and created:
https://opm.invisionapp.com/d/main/#/console/16603537/344286020/preview

Updating the name of this issue to reflect the changes.

**Comment by kbwagner** [comment]
development ticket shell: https://github.com/openopps/openopps-platform/issues/3779

**Comment by abudz19** [comment]
Further discussion has happened in the development ticket. Closing, re-open if needs further work.
