### ISSUE TITLE
Saved Opportunities 

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#112]
Ability to save an opportunity from within the view opportunity (https://opm.invisionapp.com/d/main/#/console/15360465/320303454/preview) 

Profile - ability to view saved opportunities (https://opm.invisionapp.com/d/main/#/console/14696610/315604323/preview)

**Comment by kbwagner** [comment]
Discussion from 11/7/18 offsite and other Katrina thoughts: 

Search and opportunities:
- Student will be able to save an internship with the star
- Will the star display on the opportunity card?
- If I open the opportunity I should be able to view that it is saved as well
- This should really apply to students and non students

View favorites/saved:
- Can view saved on their signed in landing page
- What can they do from their landing page favorites?  Is there an apply button beside each one?

Application:
- When they click apply, will they be able to search from their favorites?  Should also make sure they can search from the full list as well
- Will it fall off their favorites list once they apply?

Managing favorites - can come later but provide the ability to delete or expire them once they fall off

**Comment by humancompanion** [comment]
Let's do this:

* [ ] - Add favorites to the right rail on the opportunity selection screen.
* [ ] - Add text to the first item on the summary page that indicates users could use favorites to make it easier to select their preferred opportunities during the application process.

**Comment by kbwagner** [comment]
@abudz19 I think our next big push will be anything related to the application process which would include the save favorites piece.  Do you have an estimated timeline for when this design might be done?  By the end of December would be ideal.  Thanks!

**Comment by abudz19** [comment]
@kbwagner no problem, I will make sure to prioritize this tomorrow and next week.

**Comment by abudz19** [comment]
@humancompanion FYR
https://opm.invisionapp.com/d/main#/console/15360465/319289299/comments
https://opm.invisionapp.com/d/main#/console/15360465/320303454/preview

**Comment by humancompanion** [comment]
@abudz19 - The "Next steps" screen text adjustment is fine. We can hand that page off and be done with it.

The "Saved Opportunities" needs some work. I was unclear about where I wanted to add them. The intent was to add them to the selection screen here: https://opm.invisionapp.com/d/main#/console/15360465/319289308/preview

So on that screen in the right rail I believe it would be useful to add your list of saved internship opportunities with an option on each one to "Select". Selecting it would put that opportunity into the next available slot. That combined with being able to move them up and down should make the selection process easier for those that have already saved the opps they are interested in.

**Comment by kbwagner** [comment]
@abudz19 this looks good.  Just to confirm what you are thinking:
- When I click on select from a saved on, it will move over to the left next available 1st/2nd/3rd choice and will be removed from the saved list
- When I click Go to Saved, I go to my landing/home page where all of my saved are displayed.

Question - what if I want to reorder my 1st/2nd/3rd choices?  Can I drag and drop to move them around? Or I would need to delete and reselect?  (I'm assuming the second but just could see people wanting the first)

Thanks!
Katrina
@tlorrison @Piglady64

**Comment by abudz19** [comment]
> @abudz19 this looks good. Just to confirm what you are thinking:
> 
> * When I click on select from a saved on, it will move over to the left next available 1st/2nd/3rd choice and will be removed from the saved list
> * When I click Go to Saved, I go to my landing/home page where all of my saved are displayed.
> 
> Question - what if I want to reorder my 1st/2nd/3rd choices? Can I drag and drop to move them around? Or I would need to delete and reselect? (I'm assuming the second but just could see people wanting the first)
> 
> Thanks!
> Katrina

@kbwagner Yes to the first bullet, but now that you mention it, I think it would make sense if the select changed to "selected" and I also added an option to delete/remove the card from the saved list. If you agree, I will add this. 

For the second bullet, yes. 

And the answer to the question,  the idea is that you can re-order the three internships current chosen by dragging and dropping. 

Does that make sense?

**Comment by abudz19** [comment]
@humancompanion @kbwagner FYR: https://opm.invisionapp.com/share/U6PUN2AQW9H#/339546743_State_-_Programs2
Updated with two options, drag and drop on the side cards, or just a change in text to indicate it has been selected already.

**Comment by kbwagner** [comment]
@abudz19 I like the drag and drop on the left
I'm not sure the best practice on the select/selected.  I know for saved jobs we remove them from the list once you have applied for it.  If it says "Selected" on the right bar, is it still in my main saved list on my landing page?  I personally would want it gone from there once I applied.

**Comment by abudz19** [comment]
@humancompanion FYR: https://opm.invisionapp.com/d/main#/console/16373614/339546743/comments
Does this solve most of the issues?

**Comment by humancompanion** [comment]
@abudz19 - Yes, for that variation. Though the cards do have some drop shadow on them. You can grab a card from the USAJOBS UI Elements file.

**Comment by Piglady64** [comment]
Open Opps Ticket #2901, 2900 & 2862 Currently on the backlog. All of these are related to DoS not Open Opps as a whole

Related Task #29

**Comment by kbwagner** [comment]
@abudz19 these are all in development so if you want to close this one fine by me.
