### ISSUE TITLE
State: Application: Transcript

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#114]
how to handle transcripts
where to store transcripts
integrate with USAJOBS?

Decision: VSFS does not need transcripts.  Unpaid internship does need transcripts.

Current design: 
https://opm.invisionapp.com/d/main/#/console/15360465/319289334/preview

This says upload the most recent transcript - is that correct or should they be able to upload all?

10/23/18 - Tracy to discuss options with Brice.

**Comment by kbwagner** [comment]
10/22/18 DOS Meeting:
- DOS - Yes, They should be able to upload an unofficial transcript and yes they want it
- DOS Leave as is
- Tracy - Security - there is potential PII on transcripts so we are trying to figure out a way to get around that

**Comment by humancompanion** [comment]
I believe we (@abudz19 and I) also need to revise this page to be able to show uploaded documents of type transcript from a user's profile. If the user has already done an upload they should be able to select that doc.

**Comment by kbwagner** [comment]
@humancompanion @abudz19 should we close this one since you just put in 124 and 125 with more detail?

**Comment by abudz19** [comment]
@kbwagner works for me

**Comment by kbwagner** [comment]
Closing - this is replaced with issue 124 and 125
