### ISSUE TITLE
Update language on education question

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#115]
New language: Will you be, at a minimum a full- or part-time continuing college or university junior. An applicant is considered a junior if he/she will have completed all sophomore credits (60 or more hours or 90 quarter hours) by the time the internship begins and will be entering at least the junior year immediately upon completion of the internship.

**Comment by mchung07** [comment]
Updated to: Will you be, at a minimum a part-time or full-time continuing college or university junior? An applicant is considered a junior if he/she will have completed all sophomore credits (60 or more hours or 90 quarter hours) by the time the internship begins and will be entering at least the junior year immediately upon completion of the internship.

**Comment by mchung07** [comment]
Ready for review. 
https://opm.invisionapp.com/d/main/#/console/15360465/319289334/preview

**Comment by kbwagner** [comment]
10/22/18 - This has been updated in the design and State approved.
@humancompanion and @abudz19 I think this one is good to close?

**Comment by abudz19** [comment]
@kbwagner This looks good to me. Closing.
