### ISSUE TITLE
Change Title to Opportunity Title on Create

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#116]
Create Opportunity (For Feds) - change label "Title" to "Opportunity Title" to be consistent with internship opportunity form.

**Comment by mchung07** [comment]
@kbwagner Since it's just a text change, I don't think any design work is needed here.

**Comment by humancompanion** [comment]
@kbwagner - The only file I can find for create in any of the State flow is this screen which already has "Opportunity title": https://opm.invisionapp.com/d/main/#/console/15360465/319309731/preview

1. The "Feds" create path is not depicted in any of the State flows in InVision so doesn't seem necessary for Tuesday.
2. The "Feds" create path uses "Headline", not "Title". Are you asking to change Headline to Opportunity Title?

Regardless, during this transitional time can you point us to the screen (InVision link) that you are referring to? That would really help us to understand what you are asking for.

**Comment by kbwagner** [comment]
This appears to be correct in the mock.  closing
