### ISSUE TITLE
Design for student landing page (signed out)

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#117]
What happens when a student signs out?  
- They will get the login.gov Open Opps sign out blue page.  But the link will include the Open Opps homepage.  If selected, they don't see internships but all regular opportunities.

**Comment by kbwagner** [comment]
@abudz19 @humancompanion any thoughts on this?  i'm not sure there is much we can do about this.

**Comment by abudz19** [comment]
@kbwagner So if a student ever navigates away from the Student landing page, they will get sent back to Open Opps general and have no means of return? (E.g. if they get signed out or timed out, if they click the Open Opps logo above the student internship header?) They can't access their information by just signing in at openopps.usajobs.gov?

**Comment by kbwagner** [comment]
If they are logged in, the system should know they are a student and show them their landing page.  Of course that's a ticket I should put in to verify that.  Kind of in line with one of the agenda items I have for today on students...if they sign out or get timed out, it's not super easy for them to get back to the student search.  But I think Brice has some ideas on that.

**Comment by kbwagner** [comment]
We discussed this on 1/22.  not logged in users will have the ability to see an Internship navigation under the Search menu so will be able to get to the right page.  The team decided this was an ok alternative.  Closing this issue.
