### ISSUE TITLE
Create new tickets - how help links should open

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#12]
**Old Trello URL:** https://trello.com/c/f5ZYmM8L/257-create-new-tickets-how-help-links-should-open

**Checklists:**

**Attachments:** 

**Comments:**

*Debbie LeNard 2018-05-30*: @katrinawagner I added the link behavior to the style guide and will check with matt on whether we need to add to a wiki somewhere.  I'll take myself off the task.

**Comment by kbwagner** [comment]
Implemented with 7.8
