### ISSUE TITLE
Student Landing page design - signed in

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#123]
Need a signed in landing page for community 
i.e. what will a student see?
- Ability to see the opportunities they have applied to

Note: Design/BA discussion needed to determine what should display

**Comment by humancompanion** [comment]
This issue is being worked on by dev here: https://github.com/openopps/openopps-platform/issues/2459

Thus I'm moving this to Review/QA as I believe the design team is done here except to review this when it comes back.

**Comment by humancompanion** [comment]
QA kicked this back to add sort to the column headings. But assigning to @abudz19 to have a look at it to make sure it meets the visual design in the mockup.

**Comment by kbwagner** [comment]
@abudz19 I'm ok for you to close this task once you review the Macon ticket 2459.

**Comment by abudz19** [comment]
@kbwagner The sort filters are still missing and the columns are not aligned. Also, the badge area is not there - is it intentional that it not be there if they have no badges?

**Comment by kbwagner** [comment]
@abudz19 Brice asked me to write a new ticket where more than the shell of the page can be tested.  So the view x of y won't show now and the sort won't show because there is no data.  There is another ticket once we have applications that will allow those to be tested.
- Badges won't display if there are no badges per our meeting earlier in the week, correct.
- column alignment is one we can fix.  would you like to comment directly on the Macon ticket on that?  Would make sense to me.

**Comment by Piglady64** [comment]
Open Opps Ticket #2899 https://github.com/openopps/openopps-platform/issues/2899

**Comment by kbwagner** [comment]
@abudz19 this is complete and in Test/UAT so if you want to close this one you can.
