### ISSUE TITLE
Ability to see transcripts that have already been uploaded

### ISSUE THREAD

**Issue by humancompanion** [openopps/OpenOppsTasks#124]
As an applicant to the State Dept. Unpaid Internship program, or VSFS program, I need to be able to see transcripts I have already uploaded to my USAJOBS Profile in order to attach a transcript to my application.

We need to revise the design of step 3 of the applicant flow:
https://opm.invisionapp.com/d/main/#/console/15360465/319289334/preview

It should show a list of documents by name, type, and size. We should deviate from the design system component as we continue to not be able to have thumbnails for documents.

**Comment by humancompanion** [comment]
Katrina indicates we have this week to get this and #125 done.

**Comment by abudz19** [comment]
@humancompanion ready for review https://opm.invisionapp.com/d/main/#/console/15360465/319289334/preview

**Comment by humancompanion** [comment]
Ha. That's funny that you went more vertical and I went more horizontal:

![screenshot 2018-11-19 17 36 58](https://user-images.githubusercontent.com/352987/48739357-c0f29780-ec21-11e8-8537-1a18a9383f0c.png)

Seen in context here:
https://opm.invisionapp.com/d/main/#/console/15985826/331639228/preview

One thing that neither of us accounted for that is in the current component is the document type:
https://usajobs.github.io/design-system/document/#placeholder

It's at the bottom in a grey stripe. 

Can you try a few more variations that incorporate one or both of:
A. The document type (transcript in this case but, some other examples would be "ECQ", "SF-50".
B. The file type (icon in my variation).

Thanks.

**Comment by abudz19** [comment]
Updated with redesigned component & transcript text: https://opm.invisionapp.com/share/UHNZS9XEYR8#/319289334_State_-_Education_-Desktop-

**Comment by kbwagner** [comment]
@Piglady64 I believe you wrote the ticket that includes transcript...if so we can close this task.

**Comment by kbwagner** [comment]
This is covered in ticket 2919.  Closing but if anyone feels differently please reopen.
