### ISSUE TITLE
Ability to upload transcripts to your USAJOBS Profile

### ISSUE THREAD

**Issue by humancompanion** [openopps/OpenOppsTasks#125]
As an applicant to the State Dept. Unpaid Internship program, or VSFS program, I need to be able to upload a non-official transcript to my USAJOBS Profile in order to attach a transcript to my application.

This design indicates the ability to upload:
https://opm.invisionapp.com/d/main/#/console/15360465/319289334/preview

We just need a corresponding issue for dev to do the work to write the transcript back to the Core Profile.

**Comment by humancompanion** [comment]
There isn't much design work here because we rely on the browser's handling of how to upload a document. The user doesn't need to set the type of doc since all docs uploaded at this point are transcripts. I more wanted to file this to call out the need to be able to write the file back to core's documents.

**Comment by abudz19** [comment]
@humancompanion design updated per https://github.com/openopps/OpenOppsTasks/issues/124

**Comment by kbwagner** [comment]
@Piglady64 same as the other-  I believe you wrote these tickets so if you think we're covered on transcripts we can close this task

**Comment by Piglady64** [comment]
@kbwagner We are sending the user to USAJOBS to upload and store their transcripts so I will close this task.
