### ISSUE TITLE
Inform applicants of unpaid internships that they now have a USAJOBS Profile

### ISSUE THREAD

**Issue by humancompanion** [openopps/OpenOppsTasks#126]
As a student applicant to the unpaid internship program I should understand that I now have a USAJOBS Profile that allows me to apply to other internships and eventually jobs.

This request from Michelle on 11/01/18. She would like us to make clear to students that at the end of the application flow they now have a complete USAJOBS Profile that allows them to apply to other opportunities and eventually jobs. 

The revised design should more closely mirror our "jobs to be done" page used in the Core product.

This is the screen to change:
https://opm.invisionapp.com/d/main/#/console/15360465/319289359/preview

The modal is lacking in content.

**Comment by abudz19** [comment]
@humancompanion is "Jobs to be done" a page you get after applying to job on USAJOBS?

**Comment by dalenard21** [comment]
@abudz19 here's an example of "jobs to be done".  

https://opm.invisionapp.com/d/main/#/console/14962270/316120232/preview

This is an example of completing a profile before you apply to a job or when you first started to apply but didn't have a complete profile.

@humancompanion do we have a version of this for AFTER a person completes an application?  I don't think we do.

**Comment by humancompanion** [comment]
@dalenard21 and @abudz19 - Correct, we do not have this after a person completes an application and I'm proposing that we should. It's currently after you create a profile. A clear set of next steps and setting expectations is equally important as "we received your application".

Some jobs to be done resources:
https://24ways.org/2017/jobs-to-be-done-in-your-ux-toolbox/
https://www.nngroup.com/articles/personas-jobs-be-done/
https://jtbd.info/

**Comment by dalenard21** [comment]
This work has been on back burner. I started a draft, but haven't finished.  Is this priority for State work?

**Comment by abudz19** [comment]
@dalenard21 I plan to work on this next week, Weds/Thurs. I haven't heard Katrina ask anything about it.

**Comment by humancompanion** [comment]
Michelle asked for this so, yes, it's a priority for State work. So we need to get rid of the tiny modal and have a better landing screen for students when they reach the end of this process.

**Comment by kbwagner** [comment]
@humancompanion @abudz19 @Piglady64 we are going to work on application tickets over the next two weeks to have them ready for the next sprint so if they should go in this might need to get bumped up on the priority list.  Thanks!

**Comment by kbwagner** [comment]
@abudz19 @Piglady64 - did this get put into the application tickets?  If not it's something we need to get wrapped up this week and added.

**Comment by kbwagner** [comment]
This will be done as part of ticket 2882 - we will update the Macon ticket once the screen is updated.
@Piglady64

**Comment by kbwagner** [comment]
This is now it's own ticket 2927 that will need to be updated once this is complete. (@Piglady64 )

**Comment by dalenard21** [comment]
@abudz19 @humancompanion 

Here's a first draft for the type of content that we can put on this page.  I'm thinking it would look similar to the Core version and try to reuse as much as we can.  Though, some of the 'jobs to be done' are different.

[Department-of-state-application-submitted-jobs-to-be-done_20190130.docx](https://github.com/openopps/OpenOppsTasks/files/2813843/Department-of-state-application-submitted-jobs-to-be-done_20190130.docx)

Let me know if you have questions or feedback.

**Comment by abudz19** [comment]
@dalenard21 @humancompanion Initial thoughts? Also Matt - where do I get the symbols for the buttons?

https://opm.invisionapp.com/d/main/#/console/16373614/344044190/preview

**Comment by Piglady64** [comment]
@abudz19 Is this the final design. This ticket was done with the submission confirmation modal so I need to change the A/C

**Comment by abudz19** [comment]
@Piglady64 No that is not the final design. Still iterating and adding content in reaction to State's desire to have info on the security clearance process.

**Comment by humancompanion** [comment]
@abudz19 - Regular buttons are in this Sketch library file: USAJOBS > Wireframes > Sketch libraries > uswds-assets-sketch 4 > Components > Componetns_sticket_sheet.sketch. You need to add that file as a library (File > Add as library). 

I wouldn't re-use the iconography that we used in "What would you like to do next?" in Core for things that are not those same actions. Make sense? I think the changes I suggested in the InVision comment I left this morning should alleviate that but, if not let's discuss tomorrow morning.

**Comment by dalenard21** [comment]
@abudz19 @humancompanion 

Here's version 2 of the content, including content for the selectio process and the security clearance process.
[Department-of-state-application-submitted-jobs-to-be-done_v2_20190201.docx](https://github.com/openopps/OpenOppsTasks/files/2822100/Department-of-state-application-submitted-jobs-to-be-done_v2_20190201.docx)

**Comment by abudz19** [comment]
@humancompanion Thanks - I found the drawer. For the Icons, is there a preset collection I can choose from, or was someone on the team illustrating them?

**Comment by humancompanion** [comment]
Tim created the JTBD icons that are in Core. We can still have drawers without icons. I think there is enough going on visually on the page that more icons may just be a distraction.

**Comment by kbwagner** [comment]
@abudz19 @Piglady64 I think state agreed that the security clearance info could go into the selection email.

**Comment by humancompanion** [comment]
That’s great: Belt and Suspenders. Definitely useful information to present
in both places.

**Comment by abudz19** [comment]
@humancompanion @dalenard21 Should be good to hand off after review. https://opm.invisionapp.com/d/main#/console/15360465/344480824/preview

**Comment by humancompanion** [comment]
@abudz19 - Good work, Alex! Just wire up the drawers in InVision to let folks easily click through and then you can hand it off.

**Comment by abudz19** [comment]
Thanks Matt. @Piglady64, this is ready to go: https://opm.invisionapp.com/d/main#/console/15360465/344480823/preview

**Comment by Piglady64** [comment]
@abudz19 I will get the ticket updated with this information. Is the intent to link to the DoS page for the two links? (selection process and security clearance)

**Comment by Piglady64** [comment]
@abudz19 Where are the links in the right rail going? Where do I get the information that is in the drawers?

**Comment by humancompanion** [comment]
@Piglady64 - The right rail is comprised of drawers, no links. The content of the drawers is the same as in Core excluding the new drawer here for "Learn how to save a jobs search". @dalenard21 and @abudz19 - We'll need content for that drawer. (I thought it was in Debbie's Word doc referenced earlier in this ticket but it was just a suggestion of what that content could be). Go ahead and take a crack at that Alex and have Debbie review it.

**Comment by Piglady64** [comment]
@humancompanion I will get the content for the drawers from Core and wait for the content for the new one.

**Comment by Piglady64** [comment]
Alex Budz [2:26 PM]
Drawer text for "Learn how to save a job search"
You can save a search to help you look for jobs in your area of interest. When you save a search, we’ll automatically look for jobs that match the keywords and other criteria in your search.

Learn how to create a saved search and sign up for email notifications. (https://www.usajobs.gov/Help/how-to/search/save/) (edited)

**Comment by abudz19** [comment]
@dalenard21 @Piglady64 Updated the mock to address the missing text describing the selection process and also the right rail draw label for "Learn how to make your resume and profile searchable."

**Comment by abudz19** [comment]
@Piglady64 Splitting this ticket so that Unpaid and VSFS each have their own JBTD page and requirements.

**Comment by abudz19** [comment]
Confirmed with @Piglady64 this ticket can be closed.
