### ISSUE TITLE
Finish ineligible screen

### ISSUE THREAD

**Issue by humancompanion** [openopps/OpenOppsTasks#128]
We have a screen stubbed out for those immediately found to be ineligible because of a low GPA. But we have some unanswered questions:

* When does it appear? 
* Does it encourage lying?
* Do we communicate the min. quals ahead of time?

**Comment by kbwagner** [comment]
@humancompanion this is one of the open questions we have too and @Piglady64 was thinking she could talk to State and ask for more info.  

On this screen; https://opm.invisionapp.com/share/UHNZS9XEYR8#/323746480_State_-_Opportunity3_-Desktop-  they also say you should be a US Citizen, a current student, have at least a 3.0, and be able to maintain a security clearance.  The way Min had built it the "you aren't eligible" screen appeared next.  So do they want them screened out on all of these things?  But then you can change your GPA during the application process.  
- So we are somewhat communicating ahead of time on the opportunity
- Does it encourage lying?  Old studies we used to have would say yes that this could cause gaming of the system.  But ultimately someone should be verifying on the other end.  Plus maybe students are different
- When does it appear - that's the big question - before they apply? When they click apply? After they submit?  We need to verify that with State.

So questions I see for state:
1) What exactly should they be screened out for and
2) When should they be screened out
3) Is this MVP?  Or does this come later?

**Comment by abudz19** [comment]
@humancompanion Min included a right rail help box that listed the minimum qualifications, I believe. I'd let applicants know as early in the process as possible if they don't qualify, with some warning language or notification at the top of the page that says something along the lines of "warning, your GPA is too low to qualify - you can continue the application, however your application may be rejected at a later stage."

**Comment by abudz19** [comment]
@kbwagner I'd let applicants know as early in the process as possible if they don't qualify, with some warning language or notification that stays at the top of the page that says something along the lines of "warning, your GPA is too low to qualify - you can continue the application, however your application may be rejected at a later stage." Ideally they would get weeded out after apply if they decide to continue (e.g. someone confirming GPA?)

**Comment by Piglady64** [comment]
@abudz19 this is the educational friction we have been trying to implement on USAJOBS. I think it is on Team Titan's backlog. I am not sure if it hasn't been implemented due to other features having a higher priority or if there is a technical issue. Matt may be able to provide that answer.

**Comment by abudz19** [comment]
Thanks for the heads up.

**Comment by dalenard21** [comment]
We're still working on educational friction. It's 'in progress'. Tim and I are working on it.

Does state currently get applicants who don't meet these requirements?  And, as Katrina asked, if their profile indicates they don't have the GPA or aren't a U.S. Citizen, does State want stop them from applying?

**Comment by Piglady64** [comment]
Katrina and I are going to get the questions we need answers to together and I am going to call the people at State and get the answers so we can move things forward.

**Comment by humancompanion** [comment]
Rather than ask them I'd like us to put forth what we think makes the most sense and show it to them to get their feedback. I'd like to articulate that we:

Eliminate applicants after the Education step, where we collect their GPA, if they are not U.S. Citizens (which would come from their Profile) or their GPA is below 3.0 (or whatever the correct number is). That's the soonest we could do it. 

One caveat: If VSFS has a lower threshold than 3.0 then perhaps we allow the applicant to continue their application but inform them that they are only eligible for VSFS. 

This is certainly part of our MVP.

**Comment by Piglady64** [comment]
We have more questions than just this issue so I am going to get answers to the other questions. When will you  have something to show them?

**Comment by humancompanion** [comment]
Judith was very clear in the last meeting, towards the end of the meeting, that she wanted us to depict eliminating applicants. It's in my notes:

* Can/should we eliminate applicants early on if they don't meet the minimum qualifications?
  * Yes, show this in the flow.

Is there a reason we feel strongly that we don't want to do what the client has asked for?

**Comment by kbwagner** [comment]
@humancompanion I hear you and agree with you and also heard that from Judith.  This was a huge discussion and had lots of input from the group at the offsite this week.  There was concern that students would file complaints.  My comment is they aren't jobs, they are unpaid internships.  But the group felt pretty strongly (as in it was the room against me).  Is there someone from the policy side maybe who could weigh in on whether this is ok to squelch the issue?

**Comment by humancompanion** [comment]
We're testing for two things (at the moment):

1. Are you a U.S. Citizen? - This comes from their core profile and thus we could stop them right after they click Apply.

2. Is their GPA above 3.0? - This would happen after the Education screen (step 3 in the process).

**Comment by abudz19** [comment]
@humancompanion Is there a page for this already or do I need to start from scratch?

**Comment by dalenard21** [comment]
@humancompanion @abudz19 @Piglady64 @kbwagner 

Here's some messaging to start with:

1. Display if the applicant is not a U.S. citizen.

"You're not eligible for this internship because your profile says you're not a U.S. citizen. You must be a U.S. citizen to be eligible for the Department of State Unpaid Internship Program." 

Also, for 'next steps' or other options for these users, are there any?  I'm thinking no.

2. Display if the applicant does not have a GPA of 3.0 or higher

You're not eligible for this internship because your GPA doesn’t meet the minimum requirement. You must have a GPA of at least 3.0 or higher to be eligible for the Department of State Unpaid Internship Program.

You might be eligible for these student programs.

**Virtual Student Federal Service (VSFS)**
Work remotely from your college or university campus through the largest virtual internship in the world. The Department of State partners virtual interns with more than 60 federal agencies and U.S. diplomatic posts overseas. [Learn more about virtual internships](https://vsfs.state.gov/). 

**Other Department of State student programs**
The Department of State has several other student programs for current high school, college or graduate students. [Learn about other student programs](https://careers.state.gov/intern/other-programs/).

**Pathways Program**
The Pathways Program offers federal internship and employment opportunities for current students, recent graduates and those with an advanced degree. [Learn more about the Pathways Program](https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/students/).

Question: do we want the 'next steps' to be focused on Department of State student programs?  Because that's where the VSFS and 'Other student program" links will go.  They also have info on Pathways Program, but it eventually links back to USAJOBS.  I included the link to USAJOBS student page, but if we want to focus on DOS, we could link it there instead (https://careers.state.gov/intern/pathways/).

**Comment by abudz19** [comment]
@dalenard21 For (1) we could link them to the DoS Exchange program portal for non-U.S. citizens?

**Comment by dalenard21** [comment]
@abudz19 @humancompanion 

Alex - nice work. I like version #2 for the non-U.S. citizen message and #2 for non-eligible GPA.  If we go with the 'warning' version as shown in the GPA version, then the non-U.S. citizen message should use the same design.

**Comment by Piglady64** [comment]
@abudz19 @humancompanion @dalenard21 
I agree with Debbie. I like #2 for the non eligible as well. I think the warning version makes the message more visible to the user. The other versions blended in with the rest of the text and we definitely need to make this stand out.

**Comment by abudz19** [comment]
@dalenard21 @humancompanion Is there a preference between header or no header?
Header
<img width="961" alt="header" src="https://user-images.githubusercontent.com/11526811/49042394-11c03e00-f196-11e8-9fab-a78f8f2b7c73.png">

No header
<img width="967" alt="no header" src="https://user-images.githubusercontent.com/11526811/49042415-23094a80-f196-11e8-9258-182c038de615.png">

**Comment by humancompanion** [comment]
@abudz19 - You need a header for screen readers/accessibility, seo, etc. Very rarely is it a good idea to have no header. However, we might want the header to be:

"You are ineligible"

and the alert header to be more specific. For example, "You are ineligible because your GPA is below 3.0" or "You are ineligible for this program due to your current GPA". 

Agree with Debbie and Julie that the version with the alert is a good use of the warning alert style and does break up the content better visually. I was also going to ask for links to those programs which I see you have added ("Learn more...") which is great. 

I prefer that we do include the bullets that reiterate the eligibility requirements. The user may have missed them previously and we shouldn't make it a guessing game. You could put them in the right rail as they appear in the opportunity announcement if we think the text is too long.

BTW - You can upload to InVision to get feedback inline on the mock-ups. This is fine but, InVision makes it a bit easier to comment on a mock-up. Get Drew or I to show you how.

**Comment by abudz19** [comment]
@dalenard21 can you give the language another look? @humancompanion 

Ineligible GPA: https://opm.invisionapp.com/share/UHNZS9XEYR8#/333437563_State_-_Not_Eligible_GPA_-Desktop-

Ineligible Citizenship: https://opm.invisionapp.com/share/UHNZS9XEYR8#/333432320_State_-_Not_Eligible_-_Citizenship

**Comment by dalenard21** [comment]
@abudz19 @humancompanion 

Looks good - I left a few comments.  We can also have Katrina and Julie review for content as well, but I think this is a really good start.  Thanks!

**Comment by abudz19** [comment]
@kbwagner @Piglady64 mockups are ready for review above

**Comment by Piglady64** [comment]
@abudz19 @dalenard21 @kbwagner I think this looks good.

**Comment by dalenard21** [comment]
@abudz19 @kbwagner are we good to go here?  Can we close this?

**Comment by kbwagner** [comment]
@dalenard21 @abudz19 @Piglady64 Jjulie has reviewed this so fine with me to close it.

Julie can you update the appropriate application tickets when you have a chance?

Thanks all!
