### ISSUE TITLE
Research with community managers

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#130]
Moved from development backlog 2536 to task board...not sure if this is still needed.  Should discuss with the team.

We need to conduct some research with community managers, on how communities should function.

When will this happen?
When can we create a sketch to show community managers?
When should we update sketch after research is concluded.

Julie's questions; 
I will need to know the following:

When do you want to test?
Do you want this to be a virtual test or an in-person test?
How long do you anticipate the test to take (depends on the tasks you asking participants to perform)?
Are these community managers in different agencies?
How do I find a "community manager" ? ( I need to know how to recruit them.)

**Comment by kbwagner** [comment]
@humancompanion yes it's actually in the current release.  I found this one in the development backlog so moved it here so we didn't lose it.  Julie and I weren't sure whether this needed to truly get done or not but here until we have a chance to discuss more.

**Comment by humancompanion** [comment]
@kbwagner - This isn't usability testing, this is domain research which @mchung07 and @Piglady64 and other Lab folks have been working on teeing up for a potential longer term (several month) project.  How communities should function is not something we can determine and design quickly unless we want to do it poorly.

**Comment by kbwagner** [comment]
@humancompanion that's fine - I just pulled this over from another ticket.  Not sure if it's really even needed but fine to leave open for the long term research.

**Comment by humancompanion** [comment]
We did not do research with Community managers as a part of North Star. But further research is the option that Michelle selected from our 4 proposals. My recommendation at this point is that the research take the form of a pilot. Thus you would use The Lab to assist you in piloting a Community. IU had started down this path with the TTS Research Guild at GSA and could connect you.

The questions I'd want to get answered through the pilot would be: 
* What's the right scope for a Community? 
    * For example, is User researchers too narrow or UX or Design too broad?
    * What number of users is a good size for a Community? You need more than a few to make it a functional community but does too many users have any negative impact?
* Should we just stick to existing COPs like the UX community listserv? Or does a broad topic limit discourse?
* If a goal is supporting existing Communities and giving them a home (which I think it is) then what do they need to thrive?
    * What does and doesn't work with the email lists? (My guess is that not being able to see who is on the list is a friction point that prevents more 1:1 conversations)
    * If you could see the profiles of others in the community, what would you want to see?
    * What privacy controls are necessary?

That's all I can think of at the moment.

**Comment by kbwagner** [comment]
Thanks for the brain dump!  Trying to go through history tasks and make sure we have the info before you leave!
