### ISSUE TITLE
Community "profile"/index info page

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#132]
Display:
- logo
- contact info
- description

Need to research on this.

This page would be accessed when:
- logo from the opportunity card or opportunity page is clicked
- how to search on these?  Would not be part of People search.

as part of the community research, discuss how we could store help content specific to the community without everyone seeing it.

Not MVP for state.  But see comment below...will be needed once Login.gov goes live due to the way DHS Joint Duty uses the site.

**Comment by humancompanion** [comment]
@mchung07 has been working on Community and coaching, changes to the People page, and Profile. I think these items would be ready for Atlas to pick up and work with @abudz19 on to push these further.

**Comment by kbwagner** [comment]
@abudz19 this is the meeting I set up for Wednesday so there is already an old task open for this. 

This has come up because DHS Joint Duty Program Office currently uses a DHSJointDuty email to log on and uses their profile as a DHS community profile.  So when you look at one of their opportunities such as https://openopps.usajobs.gov/tasks/884  you can see instead of a profile pic, they have a logo.  If you click on the logo, it goes to their "profile" which then has a  blurb about their office in their biography.

Lisa has brought it up as an issue that when we go live with login.gov, they won't be able to have a "fake profile" such as this which has brought up the need for a community profile

We could pull basic info from the community attribute table to display on a community profile.

**Comment by humancompanion** [comment]
Let's start with developing a taxonomy around communities and programs. Then we can build this page out and perhaps start to build out a page explaining communities and programs.

**Comment by humancompanion** [comment]
We'll start this in the current sprint but we want to do some research with users so we may not finish that work in this sprint.

**Comment by kbwagner** [comment]
Closing - this is design ticket https://github.com/USAJOBS/team-design/issues/172
