### ISSUE TITLE
Identify differences in VSFS

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#133]
Identify what changes to the apply, search, and create process are needed for VSFS to go live in March.

Apply

Search

Create

@abudz19 to create mocks for any changes to pages in the process needed for VSFS.

**Comment by abudz19** [comment]
@kbwagner 
I made note of changes I think will be needed and also clarifying questions directly in the current Unpaid mock-up. After you have reviewed them, I will create a new board to reflect the VSFS process. Let me know when you've had a chance to look. Thanks!

**Comment by humancompanion** [comment]
@mchung07 and @abudz19 to work together to review these changes against the flow Min and Ben created.

**Comment by abudz19** [comment]
@mchung07 I've started to create screens, but most of the changes I noted as comments in the invision mockup. Let me know if you want to review the comments first.

**Comment by kbwagner** [comment]
@abudz19 I read through all of the emails I got as comments on Invision.  I am fine with everything.  It would be great if we could get a board set up for VSFS and then we can walk them through it at our meeting with them and let them react and/or ask pointed questions.

It looks like a few things we need go get from VSFS (@tlorrison @Piglady64 )
- Logo
- Community info especially the community name that will display (i.e. do they also want U.S. Department of State in front of their title)
- Do they call them internships or projects?  Will change titling in several places
- Confirm they will only search on agency.  We currently have said we will remove bureau/office/post because we don't have that information for anyone other than State in open opps.

**Comment by kbwagner** [comment]
Brody was able to chat offline with Bridget at VSFS and get some initial questions answered for us that might at least help Alex move forward with her design: 

1)	What is the name VSFS wants displayed throughout the system? VSFS? Virtual Student Federal Service? U.S. Department of State Virtual Student Federal Service?  Unpaid was very clear U.S. Department of State needed to be included so theirs is U.S. Department of State Student Internship Program (unpaid).
A - Virtual Student Federal Service (VSFS) 

2) What do you refer to your internships as? It appears they are called “projects”? Currently in Open Opportunities the language refers to everything as an opportunity (Create opportunity, apply to opportunity, etc.). Unpaid has requested them to be called “Internship opportunities". Does VSFS have a preference for the language?
A - We can call them "VSFS internship opportunities" 

3) What cycle times do you use for your postings? I.e. Fall, Spring, Summer, Annual?  Currently we have cycle times for unpaid of fall, spring, summer and a table behind the scenes where for each cycle and year we enter posting and internship dates for each cycle. (vs current open opportunities where we just have a posting date and it is manually closed).
A - Ours is once a year. Students apply in July (#ApplyInJuly) so July 1-31. VSFS internships begin after Labor Day and wrap up the following Spring

4) Transcripts – we know VSFS does not collect transcripts. Would it be ok to display transcripts if it were optional for students to supply them? Or is the preference to not have transcripts at all? Unpaid does want them and we are trying to minimize UI differences  where possible.

Students do submit a transcript through A - USAJOBS but we don't actually "bring" the transcript on the VSFS.state.gov site. Yes, transcripts can be made optional or mandatory (as it is now), either way. 

5) We also need a logo for VSFS and understand if you don't have access to this during the furlough. We can pull this logo from your current site, https://vsfs.state.gov/img/VSFS_logo_inverted.png, but there may have been changed since last year. We also emailed the marketing person that is still working that sent the unpaid logo to see if they could send one for VSFS. 
A - That is the correct logo minus the black background. I can access a higher res one if you need, after the shutdown.

**Comment by humancompanion** [comment]
RE: item 4 - Don't design the flow for what is easier for the system, design what is easier for the user. If VSFS doesn't use transcripts then don't ask for them. I agree we don't want to have a million little differences that make it a maintenance nightmare but, I'd put that number higher than then 2 or 3 differences listed here.

**Comment by abudz19** [comment]
@kbwagner @humancompanion @Piglady64 
I've moved this ticket as far as I can for now. You can review what has been done here:
https://opm.invisionapp.com/d/main#/projects/prototypes/16434640

**Comment by humancompanion** [comment]
@abudz19 - Can you link these screens together so that folks can click through them? Thanks. This article details how to do that in Sketch and upload it to InVision: https://blog.prototypr.io/basic-navigation-with-sketch-and-invisions-craft-prototype-plugin-99a2d2798ef9 Let me or Drew know if you have questions.

**Comment by kbwagner** [comment]
@abudz19 @Piglady64 we would like to do a meeting with VSFS either the week of 2/4 or 2/11.  Alex do you think we can have a click through mock by then?

**Comment by abudz19** [comment]
@kbwagner @Piglady64 I've wired the VSFS - desktop screens. If there are any problems with them, let me know.

**Comment by Piglady64** [comment]
Going through this today . Will be presenting to VSFS at meeting tomorrow 2/5/19

**Comment by kbwagner** [comment]
Here's what I captured as updates to VSFS from our 2/5/19 meeting:
1) additional branding to be consistent with their existing site
2) add language requirement question - was on an old version Min had done for unpaid but didn't apply to them so we removed. 
 3) have you participated in VSFS along with have you applied to VSFS 
4) remove consent
@abudz19 

We will meet with VSFS to show them create, search, and apply in depth in the coming weeks.

**Comment by humancompanion** [comment]
### Near-term items to address
* Improve the "branding" to match the VSFS personality, especially at the start and end of the application process (landing and next steps/JTBD). See below for Branding discussion.
* Explore a different pre-landing page for State unpaid internships that gives the decision tree that they outlined (Unpaid > In person vs. digital). Doesn't have to actually be a decision tree but could instead just show both options but make more clear that one is in person and one is virtual.
* Revise Experience step to ask about prior experience with both VSFS and Unpaid programs.
* Badge for VSFS and treatment for more than one iteration.
* Add language requirement option to Opportunity creation.

### Future items to address
* Explore indicating which projects are the most popular and indicating that to users (set expectations).
* Discuss and explore a drop down list of skills based on their skill list. 
  * Can we merge with the Open Opps skill list? 
  * Can we in future send off the Opportunities they selected to skillsengine and have it return a list of skills the applicant could pick from?
* Discuss and explore differences between "open" Communities and "closed" Programs 
  * Should Program discussion groups be open only to those accepted to participate? Seems logical to me. Just need confirmation that the team agrees.

#### Branding
Brand is experience: https://www.nngroup.com/articles/brand-experience-ux/

Branding breaks down into three categories:

1. Visuals
2. Tone
3. Behavior

We could do more here to highlight what makes VSFS unique across all three.

1. Visuals: At the start and end of the process let's make their logo more prominent. Their landing could be much more inline with their visual look.
2. Tone: VSFS is much more high-touch than the Unpaid program. We could add a bit of playfulness into the content throughout and highlight their different behavior (see below). 
3. Behavior: We could focus on Bridget and Nora themselves and the fact that they will personally be looking after you, the applicant, on your search for an opportunity. That is a big differentiator for their program from other internship programs.

**Comment by abudz19** [comment]
### Near-term items to address
- [ ]  Improve the "branding" to match the VSFS personality, especially at the start and end of the application process (landing and next steps/JTBD). See below for Branding discussion.
- [ ]  Explore a different pre-landing page for State unpaid internships that gives the decision tree that they outlined (Unpaid > In person vs. digital). Doesn't have to actually be a decision tree but could instead just show both options but make more clear that one is in person and one is virtual.
- [ ]  Revise Experience step to ask about prior experience with both VSFS and Unpaid programs.
Badge for VSFS and treatment for more than one iteration.
- [ ]  Add language requirement option to Opportunity creation.
