### ISSUE TITLE
Revise home page for Students

### ISSUE THREAD

**Issue by humancompanion** [openopps/OpenOppsTasks#134]
Students need a revised home page that shows the opportunities they have applied to, participated in, and saved. 

Min started on this here: https://opm.invisionapp.com/d/main/#/console/14696610/315604323/preview

We just need to remove the Created list since a Student would not be creating an Opportunity.

**Comment by humancompanion** [comment]
I created this page: https://opm.invisionapp.com/d/main/#/console/15990896/331677019/preview

@Piglady64 and @kbwagner - Are there other alterations you feel Students need?

@abudz19 - This screen is in a new Sketch file in Open Opportunities > Wireframes > OpenOpps-Profile-20181115-Shared-MD

**Comment by kbwagner** [comment]
@humancompanion looking at the link you sent:
1) Remove What's New as lisa says it won't apply to interns
2) Definitely remove See other people like you as they won't have a title or agency
3) I think the general thought was to remove the Search Opportunities by section as well 
4) What about the ability to view their application?  Could there be a button on the participated section beside each application that says "View"?  Also note on this - now State is saying they do want applicants to be able to update their applications...so if that goes through this could be where it's initiated?
5) I wonder if "Participated" is the right term for them?  Maybe just Applied?
@Piglady64 @abudz19

**Comment by kbwagner** [comment]
@Piglady64 I think this is another ticket that is ready to be written.  Would go into 2459.  Just sharing in case you get to it before me.

**Comment by kbwagner** [comment]
Writing this ticket now.  Ok to close @humancompanion @abudz19
