### ISSUE TITLE
Email content: You are invited to join a community

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#136]
Related Dev ticket 2670

User Story: As a community manager, I want an email to be sent when I invite a new member to a community in order to notify them that they have been added.

Acceptance Criteria:
When a user is added to a community through the community dashboard, the following email will be sent:

Subject:

Content:

The standard footer will be sent

**Comment by kbwagner** [comment]
@dalenard21 this is the one we should talk about sooner rather than later so it can go into a sprint in 2 weeks

**Comment by dalenard21** [comment]
@kbwagner @Piglady64 

Here is my first stab at this email.  Let me know what you think.

[Open-opportunities-email-community-invite_20181203.docx](https://github.com/openopps/OpenOppsTasks/files/2640848/Open-opportunities-email-community-invite_20181203.docx)

**Comment by kbwagner** [comment]
@dalenard21 I think this looks fine.  I'll put it in the main ticket and fine to close this. 

So we need to update both the Air Table (internal)and Word document (external) - how to you want to handle this?

**Comment by Piglady64** [comment]
I have attached some comments 


[Open-opportunities-email-community-invite_20181203 with julies comments.docx](https://github.com/openopps/OpenOppsTasks/files/2653427/Open-opportunities-email-community-invite_20181203.with.julies.comments.docx)

**Comment by dalenard21** [comment]
@kbwagner @Piglady64 

Julie - thanks for the feedback and agree with your edits. Here is an updated version of the email. I added a comment to give an example of how the "community name" should appear in the email.

Thanks.
[Open-opportunities-email-community-invite_20181206_v2.docx](https://github.com/openopps/OpenOppsTasks/files/2654013/Open-opportunities-email-community-invite_20181206_v2.docx)

**Comment by kbwagner** [comment]
@dalenard21 I have updated 2670 with this content.  I'm ok to close this one. (although we need to update the documentation at some point)

**Comment by dalenard21** [comment]
@kbwagner I updated the AirTable with the new community member invite email.  Here's the link:

https://airtable.com/tblzvuEsjxmNuyr3g/viw2axasCD2yUZHJv

I also updated the word document you've been keeping, but I uploaded that version in the other github issue #135 

Finally, I spoke with Matt and he said everyone should be able to access Airtable...at least with read only permissions.  I'll follow up in Slack.

**Comment by dalenard21** [comment]
Per the above status, closing issue

**Comment by kbwagner** [comment]
Thanks @dalenard21 the Word document was meant to be the document we could share with our users to be more of a user friendly communications document.  I'm fine with having Air Table and the Word doc if that's what works best for all of the audiences.  Thanks!
