### ISSUE TITLE
Post Release 7.4 release notes

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#137]
Debbie - 

Brice put together release notes for 7.4 and they are fine.  I'm wondering if we just make the paragraph more bullets and use that.  We never need to display the ticket numbers as you know.

Here's what he put together: 
https://github.com/openopps/openopps-platform/releases/tag/untagged-37d3e9597e153e50a1df

Please post to https://usajobs.github.io/openopps-help/what-is-new/
Deadline: Friday, December 14th (will be released that morning).

**Comment by kbwagner** [comment]
@dalenard21 this release on 12/14 MAY be postponed so I'd suggest we just get everything ready but  not post until we hear for sure.  (security issues)

**Comment by kbwagner** [comment]
@dalenard21 this release is now on for tomorrow 12/14.

**Comment by dalenard21** [comment]
@kbwagner 

Confirmed "What's new" updated with the newest release notes.
https://usajobs.github.io/openopps-help/what-is-new/

Issue closed.

**Comment by humancompanion** [comment]
Pushed this out this morning. We had a bit of a snafu with git but Drew and I are fixing that now.
