### ISSUE TITLE
State: Help content for filters

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#138]
For the Student search page, create help content for filter right rail.
- I think we agreed this could link to the regular help center and it's ok if they end up seeing other info
- Link for this help content should go with ticket 2701

Mock: https://opm.invisionapp.com/d/main/#/console/15360465/323156811/preview

**Comment by dalenard21** [comment]
@kbwagner will the search filters be the same for State and VSFS and really, for any student looking for an internship opportunity?

Here's my first draft of the "How to search for opportunities" help page.

Also, I assume this needs to go out with the 7.6 release?
[Open-opportunities-help-center-how-to-search-opportunities_v2_20190116.docx](https://github.com/openopps/OpenOppsTasks/files/2769904/Open-opportunities-help-center-how-to-search-opportunities_v2_20190116.docx)

**Comment by kbwagner** [comment]
@dalenard21 I'll take a look at the attachment in a few but to answer the questions:
- Yes, this should go out with the 7.6 release 
- The different in the search filters will be that for Unpaid internships the agency will default to DoS and then they can pick and office/post.  For VSFS, they can pick any agency but will not have Office/post

**Comment by kbwagner** [comment]
[Open-opportunities-help-center-how-to-search-opportunities_v2_20190116 (1) kbw.docx](https://github.com/openopps/OpenOppsTasks/files/2770448/Open-opportunities-help-center-how-to-search-opportunities_v2_20190116.1.kbw.docx)
@dalenard21 see my comments attached.  Thanks!

**Comment by dalenard21** [comment]
@kbwagner thanks for the feedback.  Here's an updated version.

[Open-opportunities-help-center-how-to-search-opportunities_v3_20190123.docx](https://github.com/openopps/OpenOppsTasks/files/2788381/Open-opportunities-help-center-how-to-search-opportunities_v3_20190123.docx)

**Comment by kbwagner** [comment]
@dalenard21 will the link for this info still be: https://usajobs.github.io/openopps-help/opportunity/search/

**Comment by dalenard21** [comment]
@kbwagner Yes it will be the same URL.  Is that okay?

**Comment by kbwagner** [comment]
@dalenard21 yes that's fine - I just had to put the URL in the ticket so wanted to make sure

**Comment by Piglady64** [comment]
@dalenard21 Is this done? If it is we are just waiting for our next release.

**Comment by dalenard21** [comment]
@Piglady64 I think it's done. @kbwagner reviewed my first draft and I updated the second draft with her feedback.  If either of you want to review it again, that's great.  If not, then we wait until we get closer to the release to update the pages in GitHub.

**Comment by dalenard21** [comment]
@kbwagner @Piglady64 

I've updated the page with the new filters.  Here it is in Federalist

https://federalist-proxy.app.cloud.gov/site/usajobs/openopps-help/opportunity/search/

Ready for release.

**Comment by kbwagner** [comment]
@dalenard21 are we moving to federalist for the help center?  I know it's been discussed in the past so just wondering since this one is in federalist. Thanks!

**Comment by dalenard21** [comment]
Hi @kbwagner - I just commented on the other github issue.  We're just using it as a 'test' site right now - which makes it easy to preview pages before they get pushed to production.  But, maybe Matt has more updates on a final move to Federalist.

**Comment by kbwagner** [comment]
@dalenard21 reviewed and this looks good.  FYI - when/if we go live with VSFS they will not have the bureau/office/post filters...but I think you've already said some filters won't be available so we should be good.

Thanks!

**Comment by dalenard21** [comment]
@kbwagner thanks for reviewing.  Do you think we should state that not all internship programs will see Bureau or Office/post?  Yes, we say not everyone will see the same filters, but we do have Bureau/Office listed under "internships".  Thoughts?

**Comment by kbwagner** [comment]
Maybe not all internship programs will see all filters.

VSFS will only have agency and not bureau and office/post
Unpaid will not have agency because it's defaulted to state behind the scenes but will have bureau and office/post

so maybe just a generic statement in the heading that the filters may vary by program.

**Comment by dalenard21** [comment]
@kbwagner does this need to go out on Friday?

**Comment by kbwagner** [comment]
@dalenard21 no this will not go out on Friday. Thanks for checking.

**Comment by kbwagner** [comment]
5/22/19 - Need to make a plan for who will push out help content once Matt is gone.
@humancompanion @Piglady64

**Comment by dalenard21** [comment]
@kbwagner the open opps help center was updated in production with the filter content. 

https://usajobs.github.io/openopps-help/opportunity/search/

Issue closed.
