### ISSUE TITLE
Unpaid Internship Branding (includes logo)

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#139]
Need to discuss branding for the Unpaid Internship pages

Branding Areas:
1) Search banner - yellow bar (note - the colors don't really match their banner)
2) Opportunity card logo
3) Opportunity page logo
4) Application

Per Rebecca at State: 
One key item I’d like to ask is regarding the branding of the Department.  In all of our public-facing recruitment communications, we use U.S. Department of State to avoid any possible misunderstanding or confusion that we’re the federal one and not the Department of State for a specific state.  While we’d like to think that all visitors to USAJOBS would understand this, you’d be surprised how many don’t!

•         Main Search Bar – if we can have a branded search banner that would be great
•         Internship Opportunity Card – if we meet the specs, can we use a banner across the bottom of each card? Can we use the 4-color logo attached?  Also, the text should be consistent and indicate “U.S. Department of State Unpaid Internship Program”
•         Internship Opportunity Full Page - can we use the 4-color logo attached?  Also, the text should be consistent and indicate “U.S. Department of State Internship Program (Unpaid)”

![dos unpaid internship 4-color logo](https://user-images.githubusercontent.com/18709918/49960825-0f244f00-fedf-11e8-904e-f71ce02ece73.jpg)
![state banner](https://user-images.githubusercontent.com/18709918/49960876-2cf1b400-fedf-11e8-8aa3-4327c1e18542.jpg)

**Comment by abudz19** [comment]
@kbwagner  We briefly discussed not making these changes earlier this week, and also I want to confirm again the name of the program. Per Khadijah, U.S. Department of State Internship Program (unpaid). However, above you have different guidance.

**Comment by kbwagner** [comment]
@abudz19 yes please follow Khadijah as that has been confirmed.  we need to circle back with state on the branding.

**Comment by abudz19** [comment]
For branding, I don't think there is a lot to be done. We can include the color logo on the cards and opportunity page where the background is white (and conducive to a color logo). I would not recommend customizing the banner.

**Comment by kbwagner** [comment]
@abudz19 it sounded like there was talk of changing the yellow banner to a different color that might more closely align with a DOS color but was still in the design system?

**Comment by abudz19** [comment]
@kbwagner Julie and I reviewed it in color on the yellow and several other colors, and will just keep it in color on yellow. I'll change the mocks. The transparent background logo is attached here in case development needs it. 

![state-logo-2-transparent-bg](https://user-images.githubusercontent.com/11526811/51278899-d417ae80-19a9-11e9-8006-387d9b62bce9.png)

**Comment by kbwagner** [comment]
@abudz19 @Piglady64 let me know when you're done making any changes to the branding since we'll have to put in a new ticket for dev to update it.  Thanks!

**Comment by abudz19** [comment]
@kbwagner @Piglady64 As far as the Unpaid Program goes, if everything else looks fine it should just be a swap of the BW logo for the color logo. For VSFS, I know that Bridget provided us with a logo. I wanted to wait to see if they had any alternate logos we could use, as the one they an be an awkward size/shape to fit in certain places. I've been using a square one I mocked up based on their favicon and facebook image.

**Comment by Piglady64** [comment]
Will show this to DoS in 2/14/19 meeting with them.

**Comment by kbwagner** [comment]
@abudz19 @Piglady64 this can probably be closed unless they come back with more branding requests once their marketing person sees things.
