### ISSUE TITLE
Department of State - Review content for adding languages

### ISSUE THREAD

**Issue by dalenard21** [openopps/OpenOppsTasks#140]
Review how we ask for languages/foreign languages in the create opportunity and application flow.

Current language text: 
1)	Opportunity View/Apply: (applicant)
https://opm.invisionapp.com/d/main#/console/15360465/320303454/preview
Title: Foreign language
Additional language: The following language(s) may be helpful in the internship

2)	Create Opportunity (bureau internship coordinator)
https://opm.invisionapp.com/d/main#/console/15360465/319309731/preview

Title: Foreign language
Additional Text: Please list the desired language(s) and the proficiency level for each language.

3)	Create Opportunity add language page (bureau internship coordinator)
Title: Foreign language
Additional Text: none

4)	Create Opportunity preview page (bureau internship coordinator)
https://opm.invisionapp.com/d/main#/console/15360465/319314059/preview
Title: Foreign language
Additional Text: The following language(s) may be helpful in the internship
5)	Applicant Languages & skills
https://opm.invisionapp.com/d/main#/console/15360465/319289343/preview
Current Title: Languages
Current Additional text: Please list the languages you can speak, write or read.  Include your proficiency with each.

6)	Applicant add languages:
https://opm.invisionapp.com/d/main#/console/15360465/319289346/preview
Current title: Languages
Current additional text: none

**Comment by kbwagner** [comment]
@dalenard21 and one note - State asked specifically for the word "Foreign" to be included.
- the main issue seems to be plural vs singular language vs languages and the text below matching as well.  Thanks!

**Comment by dalenard21** [comment]
@kbwagner I think it's okay for the instructional text to 'not match' in every instance, because the context for each instance changes.  An applicant reading the opportunity needs to know what, if any, languages may be helpful to know.  But a creator who's 'creating' the opportunity needs to  ' list any language(s) that they'd like someone to have.

Re:

1.) This looks good.  Just add a 'period' at the end of the instructional text so it reads:

The following language(s) may be helpful in the internship.

2. This looks good.

3. This looks good. I don't think we need instructional text, because we provided it on the previous screen.

4. This looks good, except add a 'period' at the end of the instructional text so it reads:
The following language(s) may be helpful in the internship.

5. Looks like this screen is for Dept. of State too, so let's change to "Foreign language". I'm not sure why the page title is "Languages and Skills", since they're both captured on separate pages. And, in the application itself there are two different sections you can edit. One for Languages and one for Skills.  if we really want to change it, I'd suggest making the page title where a user lists their languages as "Foreign language" and the page title for skills as "Skills".  But not sure if that's feasible.  Is it because of the core profile?  If it's too much work, then just leave the page title as 'Languages and Skills", but change the heading to Foreign language.  

6. Same as #5.

Does this make sense?

**Comment by kbwagner** [comment]
@dalenard21 that sounds good.  
@abudz19 please see the notes above.  Can you make sure the mocks are up to date with this?  I tried to consolidate in the attached word document if it helps.  Also see Debbie's question on #5 which sounds like what you and Julie had discussed in Invision comments
[Languages.docx](https://github.com/openopps/OpenOppsTasks/files/2738396/Languages.docx)

**Comment by abudz19** [comment]
@kbwagner I know that State is currently furloughed, but I wanted to ask if we could re-open this conversation with them. Do they have any evidence that their students are currently confused about or could be confused by leaving the label as language? Just doing a quick scan of their current information on careers.state.gov, they mention foreign languages only once and it is in a pdf document so it is pretty hidden.

**Comment by kbwagner** [comment]
@abudz19 we can ask although for at least the create opportunity side the dev  has already been done. This came from an email to them because they wanted to be specific that it wasn't just english...it was something else.  So we can add this to our list but yes it might be a bit before we know.

**Comment by abudz19** [comment]
@kbwagner So as an aid to opportunity creators, that makes sense. I will go ahead and make all the corrections to languages on the apply and opportunity side to fix the plurals vs. singles. If they are amenable to leaving it as languages, great. If they can't be persuaded, it will be a quick fix to add Foreign to all the titles.
