### ISSUE TITLE
Updates to help center for release 7.5

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#142]
[Release 7.5 Open Opps deployment checklist.xlsx](https://github.com/openopps/OpenOppsTasks/files/2737846/Release.7.5.Open.Opps.deployment.checklist.xlsx)

I've flagged these are areas that we may want to consider updating with release 7.5:
1) How to create an opportunity: https://usajobs.github.io/openopps-help/opportunity/
- Add a step to select target audience once create is selected

2) How to create an account:  https://usajobs.github.io/openopps-help/account/
- This appears to already having login.gov info which won't be released until 7.6.  Do we still have the old one we can repost?  

3) how to create an opportunity .pdf: 
https://usajobs.github.io/openopps-help/assets/Opportunity_Creation_Process_final.pdf
- Add step of selecting target audience

4) What is new/Release notes...covered by separate task

**Comment by kbwagner** [comment]
@dalenard21 

With release 7.5 when I click on "Create opportunity" I get this screen:
![image](https://user-images.githubusercontent.com/18709918/50981900-f69d5980-14c9-11e9-99fb-a35d52cdc1df.png)
- Who's your target audience will display Federal employees and a dropdown to Choose a community.  FAI is an "Open" community that anyone can create an opportunity for so if you click on the dropdown everyone will see that.
- Some people may also be a member of a "closed" community such as DHS Joint Duty Program office. They will also see that value in the dropdown.
- The dropdown is optional so if I do nothing and select nothing and click continue, it will associate the opportunity to my agency

This is the piece that would need to be added to the areas identified above as a new step

**Comment by dalenard21** [comment]
updated how to create an opportunity in github.  ready to go out with release.

**Comment by dalenard21** [comment]
How to create an opportunity is updated in production.

https://usajobs.github.io/openopps-help/opportunity/

I'll create a new issue for updating the PDF and for the login.gov rollback.
