### ISSUE TITLE
Research updating application

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#143]
Research allowing an applicant to update their application until the closing date.
- Would they go to their homepage and click "update application" or something similar to USAJOBS?
- If they open an opportunity they have applied for would the button name change to update?
- Would we allow them to change their mine on one of the three they have already selected?  Or can they only update their application info?

From 11/16/18 meeting with State:
7)	Apply button disable
Question:    In our last meeting we discussed allowing a student to come back and update their application once they have applied. It is our understanding that you don’t want to allow a student to be able to do this. Therefore, we are going to disable the “Apply” button once the student has submitted their application to prevent this action. 
Response: We were under the impression that students could not apply and adjust all the way up to the deadline but we have been informed that the students are able to make adjustments after an application has been submitted. We think it will be okay to allow them to make changes all the way up to the deadline for submission.
Action: Determine if we will allow them to modify their applications until the closing date.  This ticket has not been created/worked yet.  
-	In a previous meeting they said they were ok with not being able to update their applications once submitted.

**Comment by humancompanion** [comment]
@kbwagner - What's the intended outcome here and by when? Do you want just a list in this github issue of all of the changes that would need to be made so that the dev team can assess the amount of work involved? Or do you want updated mocks in InVision? Both? What's the target due date for either or both of those?

**Comment by kbwagner** [comment]
@humancompanion this is my fault that I didn't add this as an action item earlier.  It got lost in notes.  
- Dev hasn't start development of the apply process yet.  It will be at least another sprint.
- I just want to see how it would work.  If it's not complicated, we could go ahead and build it (even without a design - we can always just denote changes)
- If it seems like it would be complicated and a high level of effort, we can table as an enhancement for after go live since they did originally say they were ok without it 
- So I guess even if we just talk/write out how it would work that would be helpful. I  took a stab above but wanted to get feedback and see what i'm not thinking of.
- Target date - if we could at least discuss in the next two weeks that would be helpful.
- Invision mocks - if we decide it's doable, invision mocks would be a nice to have but not fully necessary since I think I can denote any updates in AC just fine.  Dev knows that we might not always have mocks right now and that's fine.

**Comment by humancompanion** [comment]
@abudz19 - Julie asked us to show a version of an opportunity with an "Update application" button instead of "Apply" on it. Please see to that. Thanks.

**Comment by abudz19** [comment]
@Piglady64 You can find that screen here: https://opm.invisionapp.com/d/main#/console/16373614/342347596/preview

**Comment by abudz19** [comment]
@kbwagner @Piglady64 Is it absolutely critical that they have a way to update their application from the signed-in home page? If they clicked on the opportunity, they would be brought to that screen and could then use the "update application" button to launch back into their application.

**Comment by kbwagner** [comment]
No probably not critical.  Worst case we can add some help instructions on how to update
