### ISSUE TITLE
Update content on language help page

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#145]
Should cover USAJOBS and Open Opps.

For Open Opps we should jump to the description of the levels since the link reads, "What does novice, intermediate, advanced mean?

https://www.usajobs.gov/Help/how-to/account/profile/languages/

@dalenard21 I think you have a ticket for this on another board but adding it to Open Opps so I don't forget.  You don't need to update both tickets but if we can link the two that would be great.  Thanks!

**Comment by dalenard21** [comment]
@kbwagner 

Here's the original issue in the Core Help Center, which is where I uploaded a draft of the proposed change.

https://github.com/USAJOBS/Help/issues/335

Please review and then you can update the Open Opps TFS ticket with an anchor link to the help page.

**Comment by dalenard21** [comment]
@kbwagner the language page in USAJOBS Help Center is updated with definitions of the levels.

https://www.usajobs.gov/Help/how-to/account/profile/languages/

I believe we can close this issue?  Let me know.

**Comment by kbwagner** [comment]
@dalenard21 thanks...I will close!
