### ISSUE TITLE
Profile management for Open Opps users

### ISSUE THREAD

**Issue by humancompanion** [openopps/OpenOppsTasks#147]
The design team needs to come up with a few variations of what to do about this. I think we got to agreement in that thread that a single profile is still desirable in the long term but we don't have agreement about what to do in the short term. Well maybe we do in that Dan and Brice indicated they were reluctant to do anything differently than what we've done already which was to stick an edit button on the page and call it a day.

For the long term we don't have consensus on how to get the user to their profile nor what to show them when they are there.

### Short-term options
I'll reiterate: Where we landed is insufficient in terms of returning the user to Open Opps after an edit is made in the Core Profile.

I'll add: It's also insufficient navigational scent at the moment when we reject access to Open Opps because the user has not filled nor confirmed their federal email address. While the Learn a Skill drawer appears it doesn't open or provide any clue to the user that it's the way to get back to Open Opps.

Those items are more urgent to fix than the header. The design team is going to go through the end-to-end experience tomorrow and file github issues for the team to triage and consider. That may result in some design revisions to try and tighten things up.

### Navigating to USAJOBS Profile
The question that Brice and I were arguing about boils down to: What best fits the user's mental model around managing their profile data? Or put another way, do we need to make it very clear that (nearly all of) their data is housed in USAJOBS Core?

My desire was to make this seamless and not disturb the user's mental model of which application they are in because it doesn't seem necessary to me. But, I understand the objection to this. It's certainly less clean and clear given that there is now a smaller subset of data only managed in Open Opps.

If our intention is to never move those items (Photos, skills, location) to Core Profile nor to remove them (Photo can't really live in Core) then I'll admit the design needs reinvestigation. I still don't agree with either of those decisions however as it presents a new set of problems. But, I will take a stab at solving those problems in a new way. If we don't like those then we need to revisit these decisions.

**Comment by humancompanion** [comment]
### Problems with the current implementation

Just keeping a running list in this comment of my issues with the current implementation so I can try and address them.

* "Edit at USAJOBS.gov" - Do we really need the .gov in there? It looks odd to have a half uppercase and half-lowercase URL. 
* "Edit at USAJOBS.gov" navigates in the same window/tab so I lose navigational scent back to Open Opps (see https://github.com/USAJOBS/DoS/issues/35)
* We show Biography in People search but we don't show it in the Profile of Open Opps. Not sure why this was dropped because this now causes some cognitive dissonance around what I'm seeing in OO Profile: It's a subset of Core Profile but doesn't match what is displayed for me in OO People search (when you click through to a user's profile).
* The Share link doesn't belong here. Who am I sharing my own profile with? Mom? (Good one Drew)
* There is no option to opt-out of sharing my information.
* There is no clear indication of what information I am sharing (and what I'm not). 
* The navigation to Core leaves me with no clear route back.
* It's not clear where the data is coming from.

**Comment by humancompanion** [comment]
@Piglady64, @dreeeeewwwww, @abudz19 (and adding @dalenard21):

Here are the 5 variations we discussed yesterday and a 6th hybrid that I created today:
https://opm.invisionapp.com/d/main/#/projects/prototypes/15990896

Please get my comments at your earliest convenience. Thanks!

**Comment by humancompanion** [comment]
In the short term I've offered to put the tab (v3) variation into the design system:
https://opm.invisionapp.com/d/main/#/console/15990896/340556358/preview

In the longer term we need to consider whether Profile is separated out as a micro-service and then evolves to allow you to control how you appear to others not only in Open Opps but in ATP as well (Michelle raised this excellent point to me yesterday). That would go a long way towards solving the confusion around what is shared when you opt into resume mining (which today is resume + some profile data).

Keeping this open for further long term investigation. If we do decide on the short term then I'll open a design-system ticket to track that work.

**Comment by Piglady64** [comment]
@humancompanion this isn't currently in development. The team needs to discuss this option and create a development ticket both Team Titan and Team Atlas will need to be involved.

**Comment by humancompanion** [comment]
@Piglady64 - Is this in development now? If not, if it comes up in backlog review today this would be my vote for something that should be pulled in.
