### ISSUE TITLE
Inform applicants of VSFS internships that they now have a USAJOBS Profile

### ISSUE THREAD

**Issue by abudz19** [openopps/OpenOppsTasks#149]
Related to #126 

As a student applicant to the VSFS internship program I should understand that I now have a USAJOBS Profile that allows me to apply to other internships and eventually jobs.

This request from Michelle on 11/01/18. She would like us to make clear to students that at the end of the application flow they now have a complete USAJOBS Profile that allows them to apply to other opportunities and eventually jobs.

**Comment by abudz19** [comment]
[From Slack - Matt] On this page, for the VSFS version it may be a good place to bring in some branding. I'd rather do it here than during the application process as they suggested.

**Comment by abudz19** [comment]
Working through comments from Min on Invision

**Comment by abudz19** [comment]
@humancompanion final review https://opm.invisionapp.com/d/main#/console/16434640/349073410/comments

**Comment by humancompanion** [comment]
Just finish up the drawers and then we are done here.

**Comment by abudz19** [comment]
@kbwagner @Piglady64 This is ready: https://opm.invisionapp.com/d/main#/console/16434640/349073410/comments

**Comment by kbwagner** [comment]
10/28/19 - Closing - VSFS has contacted us that they will not be going with Open Opps in the near future
