### ISSUE TITLE
Design for changing a community

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#150]
We need to provide the ability for a user to change the community they selected for the internship/opportunity or add one if they didn't select one (i.e. what DHS is doing now in production)

Suggestion was to display the selected community name on the edit opportunity/internship page with an edit button beside?  

https://github.com/openopps/openopps-platform/issues/2838

**Comment by abudz19** [comment]
@kbwagner @humancompanion  Can the "Make Changes" button bring you back to the "Choose an Audience" page? This is the new 'beginning' of creating an opportunity and would allow them to confirm or change their community.

**Comment by kbwagner** [comment]
@abudz19 I think that would be fine as long as we make sure when they click next the existing opportunity information comes up.  Then I guess they would have to save the opportunity to save the new community.  Would have to think about whether the opportunity status would change with this or it would need to be reapproved.

**Comment by abudz19** [comment]
@kbwagner They would have to save if they made any other kind of change to their opportunity right? I don't see it as materially that different from changing the title or description. I expect the status would change -- the new community manager would not have seen the opp previously if it was originally approved/posted in a different community?

**Comment by kbwagner** [comment]
@abudz19 yes they would have to save regardless...was just fully thinking through the process not saying it's an issue to save.
- correct the new manager wouldn't have seen it to approve.  In the instance we have right now where DHS didn't enter a community, Lisa approved it as a sitewide admin for them,..if they were to be able to change it to the DHS community I still think it would be good to change it back to submitted, keep any applicants who already applied, but have the community manager approve again.

**Comment by abudz19** [comment]
Another thing to consider is where we will display the community name on the opportunity page itself, possibly the blue summary box or in the header. The place where we are indicating the community for students is where in a normal opportunity you get the poster's name and picture.

**Comment by kbwagner** [comment]
@abudz19 true and even VSFS yesterday seemed to want the community name or logo to display on the create page as they will have people that create for both unpaid and VSFS.

**Comment by kbwagner** [comment]
@abudz19 where do we stand on this one?  This is a ticket we might be able to fit in the next sprint but I'd need to write it up by 3/20.  Thoughts?
- Or we can just discuss and don't need a full design.  I think Brice had some ideas on this too

**Comment by humancompanion** [comment]
This seems like a nice-to-have UI to cover up an administrative snafu. Is this really worth doing right now? If this is just UI to cover for DHS it seems like this isn't really as important as some of the other community related functionality.

**Comment by kbwagner** [comment]
@humancompanion it's definitely a nice to have but the good news is that we are getting down to the nice to have tickets!  We did decide this one is at the top of the nice to have since we have already  had issues where DHS Joint Duty didn't select a community at all and posted jobs.  So it's not just internships - it's DHS and FAI for this one too.  Since we can't change it on the admin side either we need something.

**Comment by kbwagner** [comment]
Per Brice - we need to do a spike on this

**Comment by abudz19** [comment]
@bmcorum I can't find an up-to-date open opps file, but what I'm thinking is either putting Community as the first item under step 1, or right before series. Header text is black, normal, so I would try the community text in gray, and then there could be an edit or change link next to it, that would bring them back to the audience/community page. Also, on the create opportunity page I would change the cancel button to a previous button so they can navigate back to the audience page on their own, though as Katrina noted above, what are the implications for the data they may have already entered?
<img width="908" alt="Open_Opportunities" src="https://user-images.githubusercontent.com/11526811/58815729-20305c00-85f6-11e9-9d41-3b2bfdad0927.png">

**Comment by kbwagner** [comment]
@abudz19 the spike for this was completed.  Are you working on a design for this or just update 2838 (the actual ticket) with the notes and let them run with it?

Spike outcome:

Only allow for changing communities within the same target audience. If wrong target audience was selected the entry will need to be deleted/closed and recreated using the correct target audience.

Update target audience page to only allow selection of federal employees or students. Remove community selection from this page.
On the respective opportunity or internship form add a new section for community selection.
Optional selection for federal target audience
Required selection for student target audience

**Comment by abudz19** [comment]
@kbwagner Updated the Student mockup: https://opm.invisionapp.com/d/main#/console/15360465/319309731/preview
The federal Open Opps create should place the drop down as the first selection below who as well. Thanks.

**Comment by kbwagner** [comment]
Updated 2838 - closing as design is done
