### ISSUE TITLE
Handle full-time details

### ISSUE THREAD

**Issue by humancompanion** [openopps/OpenOppsTasks#151]
Request from the engagement team:

> DHS JDP contracted with us to develop a way for the Joint Duty Program Office to post cross-agency full-time details on the Open Opportunities platform, and continue to use the standard qualification and application process outside the platform. Right now when details are posted they appear in the cards right along with the microdetails. We need a way to separate details on the platform from the the microtasks so that people can easily separate them.

This likely entails the following:

* A filter in Open Opps for "work schedule" (full-time, part-time or full-detail, micro-detail, etc.). 
* Adding options to tracks hours vs. full-time when creating the opportunity
* Having that information show up on the search results/opportunities

I've asked Lisa for some details on how the applicant portion of this is handled.

**Comment by abudz19** [comment]
@humancompanion is there a current Sketch file I can duplicate to start with this, or just rebuild the screens from the elements of the design system?

**Comment by Piglady64** [comment]
@humancompanion I am assuming that this will work like USAJOBS when someone advertises the position but provides a link to actually apply on another site.

**Comment by humancompanion** [comment]
@Piglady64 - Assuming gets us into trouble. I have no idea what we've told DHS. Maybe they are cross-posting to Core? Maybe they have no application process and expect us to magically have gathered all of the data? Maybe we sold them an application process and forgot to tell the design team? Who knows! ZenHub remains broken but the large issue is here: https://github.com/USAJOBS/team-engagement/issues/129

@abudz19 - Talk to @mchung07 about which file has what you need.

**Comment by abudz19** [comment]
@humancompanion Just an FYI, a filter already exists for Full-time detail.

**Comment by humancompanion** [comment]
Apparently our product owners are not familiar with the product (and neither am I). Alex informs me this is already possible. Alex to close this out with Lisa.

**Comment by abudz19** [comment]
@humancompanion What JDP would like is something akin to Acquisitions, where they can send people to click a link and see JDP opportunities already sorted out. Lisa has asked to put this on hold until she has talked to Tracy and Michelle.
