### ISSUE TITLE
Create a VSFS badge

### ISSUE THREAD

**Issue by abudz19** [openopps/OpenOppsTasks#152]
[Copied from DoS ticket 61](https://github.com/USAJOBS/DoS/issues/61)

VSFS would like a badge for those students who have completed a VSFS internship

We discussed a way to visualize multiple internship participation without displaying multiple badges of the same kind

**Comment by abudz19** [comment]
Min is working on this

**Comment by kbwagner** [comment]
@abudz19 did you mean to close this if it's still being worked on?  we can just change the assignee

**Comment by abudz19** [comment]
@kbwagner it was a duplicate issue, sorry I should have put that in the comment. Both you and Julie are creating tickets in different boards (OpenOppsTasks vs. DoS) for the same issues sometimes. Min is working on this and the related ticket is linked to above, DoS #61 .

**Comment by kbwagner** [comment]
@abudz19 Got it - yes it's confusing.  @Piglady64 and I can chat about that.  This is the board I thought all design stuff should go on.  But we also need it on the action item list but at least they should reference each other.  We'll figure out the best plan.  Thanks!
