### ISSUE TITLE
Update Open Opps badges

### ISSUE THREAD

**Issue by mchung07** [openopps/OpenOppsTasks#153]
5/5/2020: 
During roadmap meetings - Lisa took the action item from Michelle to contact IO psychologists on bading Charlie and Kelly

Old comments: 
We want to update Open Opps badges to match the updated site's look and feel and be more meaningful. 

List of current badges 
https://github.com/openopps/openopps-platform/blob/2c8a055edaa9c3685a3bb2b735e4d7f33cc11971/docs/badges.md

From Dev 11/19/19: 
Badges awarded to creators of a task:
Instigator – awarded to “one time” task;
Mentor – awarded to “ongoing” task;
Team builder – if the number of volunteers for the opportunity reaches 4.

Badges award to applicants depending on the number of opportunities completed:
1 - newcomer,
3 - maker,
5 - game changer,
10 - disruptor,
15 – partner.

**Comment by humancompanion** [comment]
Tim has the Unpaid internship badge and is working on it.

**Comment by mchung07** [comment]
I've been replicating current badges in .ai since I'm not able to find the original source file for it. I'll hand this over to Tim after I talk to @kbwagner  in case any other badges are needed.

**Comment by kbwagner** [comment]
@humancompanion - what's the status on the Open Opps badges?  I have the badges for the internships but it looks like Min and Tim were working on changing all of them.  Is this done? Thanks.

**Comment by humancompanion** [comment]
Yes, I have them. Ping me on Slack to remind me and I’ll get them to you.
