### ISSUE TITLE
Design for a student ability to withdraw application

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#154]
During State meeting on 2/28 State indicated they would like for a student to be able to withdraw their application.  This would withdraw all 3 of their applications, give them some sort of modal confirmation, and then will send an email to confirm withdrawal to the applicant.

Thought was to do this from the student landing page as possibly an icon or link?  

For reference: Current Open Opps has a "Cancel your application" link on the right rail of the opportunity which doesn't exist for students.

Related development backlog shell ticket: https://github.com/openopps/openopps-platform/issues/3087

**Comment by abudz19** [comment]
@humancompanion FYR: https://opm.invisionapp.com/d/main#/console/15360465/350174926/preview

**Comment by humancompanion** [comment]
Left a comment in InVision. This one needs a bit of a rethink.

**Comment by kbwagner** [comment]
@abudz19 @humancompanion looking at the backlog, I'd love to have this one figured out for the sprint that starts in 2 weeks.  So ticket written by 3/21.  Is that doable?

**Comment by humancompanion** [comment]
@kbwagner - Yes, we discussed it some earlier in the week. @abudz19 is working on it. It's likely going to require changes to two or more screens, but they should be small in nature.

**Comment by abudz19** [comment]
@humancompanion 
Option 1 (4 screens): https://opm.invisionapp.com/d/main#/console/15360465/346381941/preview
Option 2 (4 screens): https://opm.invisionapp.com/d/main#/console/15360465/351799522/preview

**Comment by abudz19** [comment]
@humancompanion Should be wired correctly: https://opm.invisionapp.com/d/main#/console/15360465/352071150/preview

**Comment by abudz19** [comment]
@kbwagner @Piglady64 Final screen sequence for handoff: https://opm.invisionapp.com/d/main#/console/15360465/352514658/preview
This includes updates to the Signed in landing page, a new view for students to update or withdraw, modals, and is wired up if you want to go through the experience.

**Comment by kbwagner** [comment]
@abudz19 I reviewed this and created the ticket https://github.com/openopps/openopps-platform/issues/3087

I had a couple of questions that I put in the Invision mock that I think went to Debbie so I can follow up with her.  

I'm ok to close this as long as those questions get answered.

**Comment by dalenard21** [comment]
@kbwagner @abudz19 I just answered two comments on the invision mock above.  Thanks for the reminder...usually comments show up in my email, so I must have missed those.

**Comment by abudz19** [comment]
Done.
