### ISSUE TITLE
Badge for Unpaid internships

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#155]
Please create a badge that would display when a student completes the unpaid internship program.
Can be similar to discussions on VSFS where if they complete 1, 2, or 3 they get a number beside the badge.
From 152: We discussed a way to visualize multiple internship participation without displaying multiple badges of the same kind

Requested completion date: 3/21/19

**Comment by kbwagner** [comment]
@mchung07 - any updates on the badge for unpaid interns once they complete their internship?  Will it be done this week?

**Comment by mchung07** [comment]
![Screen Shot 2019-03-21 at 5 29 56 PM](https://user-images.githubusercontent.com/15160200/54786397-23bf6400-4bff-11e9-9f51-826d28ee1430.png)

**Comment by kbwagner** [comment]
@mchung07 there are two different logos here.  Are they all for Unpaid internships?

**Comment by humancompanion** [comment]
Astronaut is the selection. Go forth!

**Comment by mchung07** [comment]
[badges_intern.zip](https://github.com/openopps/OpenOppsTasks/files/2997054/badges_intern.zip)

**Comment by kbwagner** [comment]
Entered into development ticket 3001.  Closing.
