### ISSUE TITLE
Design for community cycle table UI

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#156]
If there is time, we could use a design for the community cycle table.  

The page exists where you can add to a cycle...but you can't get back to it to edit or remove a cycle.  In addition, ATP has requested some additional fields to be added:

Related tickets: 
- New fields to add to cycle page: https://github.com/openopps/openopps-platform/issues/3048
- Ability to edit/remove cycle: https://github.com/openopps/openopps-platform/issues/2835
- To get to current cycle UI: Admin --> Community (select Unpaid internship)--> Opportunities --> Manage --> Create Cycle

**Comment by kbwagner** [comment]
@abudz19 I think this one is going to be in the next sprint because it's become an issue that we can't edit cycles.  
https://github.com/openopps/openopps-platform/issues/2835

This is one we are probably ok with without a design but keeping you in the loop.

**Comment by abudz19** [comment]
@kbwagner I was just looking over what is in production and was curious as to why for each date range entered there are different labels - "date range to create" uses first day/last day; "date range for accepting applications" uses start date/end date; "date range of internship" uses start date/end date. 

Probably all of them could just be labeled start date/end date.

**Comment by abudz19** [comment]
Also, this is already in development right?

**Comment by kbwagner** [comment]
@abudz19 yes the new and improved version is in development right now.  I can mention to Brice the label consistency. 

I did ask if we could use a calendar icon instead of all of the different date fields but he said that is a design system thing.  Not a fan but I'll go with it!

**Comment by kbwagner** [comment]
@abudz19 you can close this ticket if you'd like and just review the development ticket once ready.  I'll make sure to tag you on it
