### ISSUE TITLE
New pill for internship status of "Approved"

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#157]
We are adding a new internship opportunity of "Approved"

Internships will go from Draft --> Submitted --> Approved --> Open 
- We are adding this new status because internships will not automatically open like regular opportunities.
- The pill will be added to the community admin dashboard 
- Need to determine pill color for Approved

Current pills
https://usajobs.github.io/design-system/pill/

Requested completion: 3/21/19 (sorry for the late notice)

Related Development ticket: https://github.com/openopps/openopps-platform/issues/3000

**Comment by abudz19** [comment]
<img width="130" alt="Open_Opps_-_Dept_of_State__master_-AB" src="https://user-images.githubusercontent.com/11526811/54639225-3e5cd600-4a63-11e9-89fc-9fdff3da1d8f.png">
design system color = #4c2c92

**Comment by kbwagner** [comment]
Entered into ticket.  Closing.  Thanks @abudz19
