### ISSUE TITLE
Determine plan for DHS Joint Duty once login.gov goes live

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#158]
Current DHS Joint Duty opportunities use a group email address, a logo for their profile picture, and a blurb about DHS in their biography.  Once login.gov goes live, they will not be able to use a group email with login.

USCIS also uses the system this way.

Tracy to discuss options with Lisa.

**Comment by Piglady64** [comment]
@tlorrison @bmcorum we need to come up with a solution for these two agencies because on May 3rd they will  no longer be able to operate like they are now.

**Comment by kbwagner** [comment]
Meeting held with DHS JPD and tickets entered. Tracy has reached out to USCIS

**Comment by kbwagner** [comment]
Two tickets were created for DHS JDP to set them up correctly for Open Opps.
