### ISSUE TITLE
Review Next Steps page

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#163]
On the next steps page: https://opm.invisionapp.com/d/main#/console/15360465/319289299/comments

#2 says "Review your experiences and references" and then "You must give us two references we can contact."  But...references are optional in the system.  Julie has confirmed with State that references are optional.

Can we update this text?  Also...there is a lot more on that page other than just references.

Debbie - please review content and provide updates - DONE
Alex - please update mock with decisions - DONE
Katrina - Please update this ticket and mark requirements ready when finished: https://github.com/openopps/openopps-platform/issues/3248 - DONE

**Comment by dalenard21** [comment]
@kbwagner @abudz19 @Piglady64 

I've added this as a comment to the Invision mock as well. Let's update the content to:

**Review your experience and references**
Tell us about your work, military or other experience.

I think we can leave 'references' out of the description since it's optional.

**Comment by kbwagner** [comment]
@dalenard21 - looks good thanks
@abudz19 - once the mocks are updated you can close this ticket out.

**Comment by abudz19** [comment]
Done
