### ISSUE TITLE
Provide text for application review when no references provided

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#164]
Add text under the references section on the review page if nothing provided.  We have to show the header so they can edit.  Something like "You haven't provided any references"

What does USAJOBS do? References are suppressed when no references provided in the USAJOBS resume builder review. 
- We need to keep the header in Open Opps because it has an "Edit"

![image](https://user-images.githubusercontent.com/18709918/54771690-28265580-4bdc-11e9-9ddc-507865e65f07.png)

**Comment by dalenard21** [comment]
@kbwagner how about this:

You haven't added any references.

**Comment by kbwagner** [comment]
Created ticket https://github.com/openopps/openopps-platform/issues/3253 with recommended text above
