### ISSUE TITLE
Create Opportunity button design

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#166]
from 3/26/19 Bug bash:
Landing page – Create Opportunity button should it be blue instead of white – doesn’t look like a button

**Comment by abudz19** [comment]
<img width="1177" alt="Open_Opportunities" src="https://user-images.githubusercontent.com/11526811/58126849-f7659b00-7be1-11e9-9c4c-5856d116dc5e.png">

Here is what it would look like blue. I don't have any concern about changing it to blue, if we think that will help them figure out where to start creating the opportunity. 

For future iterations, @Piglady64 prior to this, was any usability testing conducted around creating an opportunity? I know that in Min's prototype for communities & coaching, the create function was omitted altogether so we can definitely have a more strategic discussion about where to place it when that future work is picked up.

**Comment by kbwagner** [comment]
5/22/19 - the button is correct as secondary action button and it meets design standards.

**Comment by Piglady64** [comment]
The only test I have done for OO is for DoS. We tested with Bureau Internship Coordinators. I can try to find that report. I am not sure if I put it on the U drive or not. give me a sec.

**Comment by Piglady64** [comment]
@abudz19 I looked at the report for the test I mentioned above. It looks like we started them on the page  after they would have hit the "+create opportunity" button. I don't remember anyone outside of the PMO commenting on this. We have shown this to Khadijah and her team multiple times and I don't remember them saying anything about the button not looking like a button.
