### ISSUE TITLE
Verify font size

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#167]
Alex - this was entered from the bug bash on 3/26 but can you please verify if there is a change needed?

42)	Font size under description too small
font size for the description under Foreign Language
![image](https://user-images.githubusercontent.com/18709918/55434221-15f5d100-5565-11e9-8479-19b1a7e33159.png)

**Comment by abudz19** [comment]
The font size should be the same as the body text of the Opportunity, i.e. the same size as the text in the screenshot that says "for open source research." In the mockup, that would be 17. 

So yes, it is too small.

**Comment by kbwagner** [comment]
Entered ticket 3527
