### ISSUE TITLE
Verify punctuation

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#168]
Debbie - this was entered from the bug bash 3/26. Thoughts?

![image](https://user-images.githubusercontent.com/18709918/55434335-610fe400-5565-11e9-9241-ca6d5298133b.png)

**Comment by dalenard21** [comment]
Remove the comma and add period.

**Comment by kbwagner** [comment]
Added https://github.com/openopps/openopps-platform/issues/3350
Closing. Thanks Debbie!
@abudz19 FYI in case you want to update the mock.
