### ISSUE TITLE
Name display in Open Opps

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#169]
From Bug bash 3/26/19:
- USAJOBS only displays first name in navigation header
- Open Opps displays full name

Should we be consistent across platforms?

**Comment by abudz19** [comment]
@kbwagner I don't see a problem with being consistent. I'd opt for first name only, it matches Open Opps more informal tone better.

**Comment by kbwagner** [comment]
@abudz19 thanks

Made this 3445 and closing this
