### ISSUE TITLE
Steps process for Create does not conform to USAJOBS

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#170]
From 3/26/19 Bug bash
- Steps process for Create does not conform to Apply, USAJOBS, or ATP

**Comment by abudz19** [comment]
Can you give me a little more context on this?

**Comment by kbwagner** [comment]
@abudz19 (You may have to slack me questions since I won't get  Github emails for a while)...this came from Brody and he's saying the Create process doesn't have the 1/2/3 steps like our other systems.  So threw this one here for us to discuss whether we want that.  

If you totally disagree, then we can close it.  I don't have a huge opinion on it...the main thing I hear is people don't want to have to preview if they are just editing and some of the buttons aren't clear to them.

**Comment by kbwagner** [comment]
5/22/19 - Team discussed and this is a non issue.
Create is on one page, then it's preview.  Doesn't warrant a steps process.
