### ISSUE TITLE
Sorry page revamp

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#171]
We should re-look at the blue Sorry page that new users get when they try to create an account on Open Opps.

1) Katrina has a ticket 3325 to work on the flow for the new user
2) Brice suggested possibly not having the page be blue as people see that as the blue screen of death (Alex?)
3) We should look at the language as well - maybe the header of "Sorry" isn't the best way to start the page...users aren't reading past that (Debbie?)

**Comment by humancompanion** [comment]
1) No
2) No
3) NO

Fix the actual problem. Require the right fields if the user comes from Open Opps through the new user flow. It's really not that complicated.

**Comment by abudz19** [comment]
Closing, I created a duplicate issue.
