### ISSUE TITLE
language for how to convert your GPA to a 4.0 scale

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#172]
debbie - we need to make students enter their GPA on a 4.00 scale...so we need to make a conversation formula.  Maybe a question mark with some text behind it?

(GPA_Value-GAP_Min)/((GAP_Max-GPA_Min)/10)

https://pages.collegeboard.org/how-to-convert-gpa-4.0-scale
Account Help
How to Convert Your GPA to a 4.0 Scale
How to Convert Your GPA to a 4.0 Scale. Colleges report GPA (grade point average) on a 4.0 scale.
(grades * credit)/credits = GPA

Development ticket: https://github.com/openopps/openopps-platform/issues/3304

**Comment by dalenard21** [comment]
@kbwagner I think we decided yesterday that we aren't going to include content about converting the GPA.  What's the new ask here?  Add a line of instructions to say if your GPA is over a 4.0, just enter 4.0?

**Comment by kbwagner** [comment]
@dalenard21 - I think this is ok and can be closed but left this one in Julie's capable hands.

**Comment by dalenard21** [comment]
Okay. I'll close this issue.  Thanks.
