### ISSUE TITLE
New design for Oops page

### ISSUE THREAD

**Issue by abudz19** [openopps/OpenOppsTasks#174]
Improve this page for user experience

![image.png](https://images.zenhubusercontent.com/5af355f74b5806bc2bd288bb/f220baf8-6db7-44a6-936a-b714fdca2fee)

**Comment by abudz19** [comment]
@humancompanion @Piglady64 
https://opm.invisionapp.com/d/main#/console/15360465/358271694/preview
Four screens total. 
- First two screens are an option if we can't tell if the user has a profile already or not. 
- Second two screens are an option if we can tell which problem the user is having (no existing USAJOBS profile vs. missing information from USAJOBS profile) and can serve the user a more specific page. 

Brice said he would check on this for me. Thanks!

**Comment by abudz19** [comment]
This mockup has been updated and ready for a second review.

**Comment by Piglady64** [comment]
@abudz19 this is definitely a move in the right direction. these pages don't make me STOP and think I have done something wrong. Once you have the design the way you want it I will start working on the content. I want to see what information you are going to present before I start working on it. Good Job

**Comment by abudz19** [comment]
@Piglady64 If @humancompanion approves, I'm finished. There are screens for 1. never created your profile that provide a little info for feds and students on what not to forget, 2. if you chose fed as hiring path but didn't include current agency and/or validated email address, and 3. if you didn't choose a hiring path, and info to decide if you are student or fed.

**Comment by Piglady64** [comment]
@abudz19 Great, once these are approved let me know and i will work on the content for each section.

**Comment by abudz19** [comment]
https://opm.invisionapp.com/d/main#/console/15360465/358534511/preview
@Piglady64 Let me know if you have any questions.

**Comment by abudz19** [comment]
https://opm.invisionapp.com/d/main#/console/15360465/358534511/preview
@Piglady64 Let me know if you have any questions.

**Comment by abudz19** [comment]
This is fully updated right now with Debbie's content and also updates to the Navigation bar per discussions with Brice.

**Comment by dalenard21** [comment]
@abudz19 @Piglady64 looks great.  

On a couple of the screens we bold "Experience" in some places but not others.  For example, on this screen:https://opm.invisionapp.com/d/main#/console/15360465/361462004/preview , we should bold "Experience".  

Might want to look at the other screens, or at least tell the Dev team in the ticket to make sure it's bolded.  

Thanks again for working on this.  A big improvement from the oops.

**Comment by kbwagner** [comment]
@dalenard21 @abudz19 I udpated the tickets yesterday, added a comment on Invision for Alex on the bold experience and noted in the ticket that it should be bold to be consistent.  So good on this end!  Thanks!
