### ISSUE TITLE
Manual Phase Control for ATP

### ISSUE THREAD

**Issue by abudz19** [openopps/OpenOppsTasks#175]
- for Wednesday May 1st
![IMG_20190424_164033](https://user-images.githubusercontent.com/11526811/56692364-0410d500-66b0-11e9-9168-94d293850578.jpg)

**Comment by abudz19** [comment]
@Piglady64 https://opm.invisionapp.com/d/main#/console/17190930/360249570/preview

**Comment by Piglady64** [comment]
@abudz19 This looks great. It is a lot of clicks but I understand where you are going. I was hoping that when she clicked the "Start Alternate Phase" it would close the primary phase and open the alternate column. I was trying to keep her from having to click to close one phase and another to open the next considering they will most likely be done at the same time.

**Comment by Piglady64** [comment]
@abudz19 I will make some changes to the list we created on Dan's board to mirror this design.

**Comment by abudz19** [comment]
@Piglady64 

> It is a lot of clicks but I understand where you are going. I was hoping that when she clicked the "Start Alternate Phase" it would close the primary phase and open the alternate column.

Yeah I understand. We can definitely design it that way, as long as you don't think there would ever be a situation in which there would need to be space between the phases.

**Comment by Piglady64** [comment]
@abudz19 I know there won't be a space between the Primary and Alternate phase because she gives them 4 weeks to make their selections and when she closes it all of the boards will close so I don't anticipate a space. Can you do a design where the buttons close one board and open the other so we have two versions to show them on Tuesday

**Comment by abudz19** [comment]
@Piglady64 here is the second version: https://opm.invisionapp.com/d/main#/console/17190930/360656832/preview

**Comment by Piglady64** [comment]
@abudz19 This looks great. A few less clicks and it explains what is being done in each phase. I like it. We will present this to the group tomorrow and see which one they want to use. Great job.

**Comment by abudz19** [comment]
Waiting on any requested changes resulting from Tuesday's meeting with the Product Owners.

**Comment by kbwagner** [comment]
Closing - design work is done and tickets are being written.
