### ISSUE TITLE
Content for "Next Steps" page

### ISSUE THREAD

**Issue by Piglady64** [openopps/OpenOppsTasks#176]
@dalenard21 The references are not required for DoS. We changed the label to 

"Tell us about your work, military or other experience"

We need content to go under this label.

![image](https://user-images.githubusercontent.com/15252970/56904753-e99e7900-6a6c-11e9-878f-50bcb4c2b734.png)

**Comment by dalenard21** [comment]
@Piglady64 

Update the heading to be: "Review your experience" 

Update the content under it to read: "Tell us about your work, military or other experience."

**Comment by dalenard21** [comment]
@Piglady64 I think our work here is done.  Can we close this?
