### ISSUE TITLE
Revamp create new account page

### ISSUE THREAD

**Issue by abudz19** [openopps/OpenOppsTasks#177]
Create new account page – create new account should be more prominent
Create shows up at the bottom of the page so the majority of users are entering their email to try to match a profile when they are new users and need to click the Create account button at the bottom.

**Comment by abudz19** [comment]
https://opm.invisionapp.com/d/main#/console/15360465/361723866/preview

@dalenard21 The goal with this page is to get new users to create a profile, or to link their existing OO profile if they have one. If they do not find their existing profile and link it to their USAJOBS profile, they will lose their user history. It's based off this existing page in core: https://opm.invisionapp.com/d/main#/console/14962270/311112658/preview

I tried to keep the content on the left (for completely new users) from mentioning creating a new profile, since that was the process they just went through with login.gov/USAJOBS and it seemed to confuse them more than help when we were testing with State employees. The box on the right is for existing OO users who now have to link their USAJOBS account with verified federal email address to their existing OO account if they want to save all of their previous information.

**Comment by abudz19** [comment]
@kbwagner fully updated text
https://opm.invisionapp.com/d/main#/console/15360465/362009695/preview

**Comment by kbwagner** [comment]
@abudz19 this is in development - you can close.
