### ISSUE TITLE
Design for hiring manager moving selectee to task complete

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#180]
Open Opps will be automatically moving interns to selected or not selected once the emails are sent out in ATP to notify applicants.

Once the intern has completed their internship, State would like for hiring managers to go into Open Opps and move the selectee to internship completed.  

We have currently removed the right rail from all internships.  But current Open Opportunities have a right rail that has a selectee section with a task completed link under each one.  Once they are moved completed, the opportunity can be closed.

Design for:
- A modified right rail only visible to community members
- Modified verbiage for internships
- all applicants should not appear, just selected

**Comment by abudz19** [comment]
Holding off until further conversations are had about whether to put this in ATP or Open Opps.
