### ISSUE TITLE
Need new page for Education screen out questions

### ISSUE THREAD

**Issue by Piglady64** [openopps/OpenOppsTasks#181]
@abudz19 In our meeting with DoS yesterday they said they want us to stop students if they answer "no" to any of the following questions on the Education and Transcript page. We need a page similar to the one used for GPA and Citizenship. 

- Are you currently enrolled (part-time or full-time) or accepted for enrollment in an accredited college or university?
- Will you be, at a minimum, a college or university junior (i.e. have completed 60 or more undergraduate semester credit hours or 90 or more undergraduate quarter credit hours) by the start of the intern session for which you are applying?
- Will you continue your education after this internship has been completed?
- If you are selected for an internship, will you be able to work between 32 and 40 hours a week for 10 consecutive weeks? #3486

- One page for all of these questions is fine.
Development Ticket: https://github.com/openopps/openopps-platform/issues/3490

**Comment by abudz19** [comment]
https://opm.invisionapp.com/d/main#/console/15360465/361505804/comments
@dalenard21 can you please review the content

**Comment by kbwagner** [comment]
@Piglady64 can this be closed now?  I think it's done.
