### ISSUE TITLE
Add save star to the internship card

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#182]
State has requested save star be on the card for the internship.

Need to determine best location.  In USAJBOS it is in the top right corner.

Backlog ticket; https://github.com/openopps/openopps-platform/issues/3519

**Comment by abudz19** [comment]
Top right corner seems reasonable to me.

**Comment by kbwagner** [comment]
@abudz19 my only concern was that the title seems to go all the way across.  So it's wasn't a clear fit 
![image](https://user-images.githubusercontent.com/18709918/58054831-db062780-7b29-11e9-8fe4-e1f60b4272da.png)

**Comment by abudz19** [comment]
@bmcorum Can the display of the title be coded so that we have the save star in the top right corner with a buffer of 15 px around it?

**Comment by bmcorum** [comment]
@abudz19 I don't see why not

**Comment by kbwagner** [comment]
@abudz19 let me know if you are good with the saved star should appear in the upper right corner of the opportunity card.  
- The title will be coded so that we have the save star in the top right corner with a buffer of 15 px around it?

**Comment by abudz19** [comment]
@kbwagner Yes that is fine.

**Comment by kbwagner** [comment]
@abudz19 you can close this one.Ticket 3519 on the Macon board.
