### ISSUE TITLE
Wording for Oops page

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#184]
When a student clicks on the search interns link from State Dept website or Open Opps, but there are no interns posted because it's between cycles...they get the standard Oops page

Attempt for release 7.8 - June/July timeframe.

![image](https://user-images.githubusercontent.com/18709918/58256499-1cbaec00-7d3d-11e9-9981-dc036c96a426.png)

Ray had a good suggestion that we reword it for interns and if there are dates available for the next cycle in the system, display those dates.  But we also may not always have those dates so might want another version of wording if no future cycles are available.

**Comment by dalenard21** [comment]
@kbwagner @Piglady64 

Please review this content to use for the Oops page. I added a comment about one of the links to "sign up for email updates".  Let me know if this is good or you have any edits.

[Department-of-state-student-internship-program-oops-no-results-page_20190528.docx](https://github.com/openopps/OpenOppsTasks/files/3228591/Department-of-state-student-internship-program-oops-no-results-page_20190528.docx)

**Comment by kbwagner** [comment]
[Department-of-state-student-internship-program-oops-no-results-page_20190528 kw.docx](https://github.com/openopps/OpenOppsTasks/files/3228747/Department-of-state-student-internship-program-oops-no-results-page_20190528.kw.docx)

@dalenard21 @Piglady64 I added a comment and a tracked change.

**Comment by Piglady64** [comment]
Here are my comments:
[Department-of-state-student-internship-program-oops-no-results-page_20190528 (1) julies comments.docx](https://github.com/openopps/OpenOppsTasks/files/3233154/Department-of-state-student-internship-program-oops-no-results-page_20190528.1.julies.comments.docx)

**Comment by dalenard21** [comment]
@Piglady64 @kbwagner 

Here's the updated content including Julie's feedback. Let me know if you need anything else.
[Department-of-state-student-internship-program-oops-no-results-page_v2_20190529.docx](https://github.com/openopps/OpenOppsTasks/files/3233412/Department-of-state-student-internship-program-oops-no-results-page_v2_20190529.docx)

**Comment by kbwagner** [comment]
Closing - This has been completed by dev.
