### ISSUE TITLE
Help text for community table add/edit

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#185]
Add help text to the community attribute table add/edit to help administrators when they edit fields to know what they 

https://opm.invisionapp.com/share/U8R4CAV3HXF#/screens/353420496/comments

Low priority

**Comment by dalenard21** [comment]
@kbwagner what's the priority on this one?

Is the request to define each field?  So something like 

How to edit community information?

**Comment by kbwagner** [comment]
@dalenard21 - low priority.  This came as a suggestion from Matt saying that people won't know what to put in each field.  we are bringing on two new customers next year so maybe January?  
- Yes, define each field

**Comment by kbwagner** [comment]
@dalenard21 closing this here and adding it to the design system tickets. https://github.com/USAJOBS/team-design/issues/254
