### ISSUE TITLE
Remove Geo Names from Help center footer

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#186]
We are no longer using Geo Names for our locations.
- Dev has removed the link from the footer in Test/UAT but let us know that we will also need it removed from the help center footer

Screen shot: 
![image](https://user-images.githubusercontent.com/18709918/58769562-2aab1100-8576-11e9-9bf1-19bcbd30d4c9.png)

Please remove the link that reads "Locations provided by GeoNames" from the Open Opps Help Center footer.  The 6/10/19 release should remove it from production

**Comment by dalenard21** [comment]
@humancompanion can you do this for 6/10?

**Comment by humancompanion** [comment]
Will do.

**Comment by dalenard21** [comment]
@humancompanion not sure if the link got removed.  Is that something you can still do? Or do we need to wait until the next release?

**Comment by humancompanion** [comment]
It's gone.
![Screenshot 2019-06-19 21 37 28](https://user-images.githubusercontent.com/352987/59812047-77af1700-92da-11e9-9766-72b8471f1ae1.png)
