### ISSUE TITLE
Create updated user personal list for Open Opps

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#188]
Include community personas:
Community Member
Community Admin/Hiring Manager

Current list to update: 
[Open_Opps_User_Types_v2_2222018.xlsx](https://github.com/openopps/OpenOppsTasks/files/3254961/Open_Opps_User_Types_v2_2222018.xlsx)

share when complete with BACOP and ATP

**Comment by Piglady64** [comment]
@kbwagner @tlorrison I added the Community Manager (Khadijah's office), Community Member (HMs for DoS and members of other communities) and Site Wide Administrator. I also removed all of the options we went through last year to come up with the final title. I don't want to confuse the other teams. Let me know if anything else needs to be added. 
[Open_Opps_User_Types_v3.xlsx](https://github.com/openopps/OpenOppsTasks/files/3266848/Open_Opps_User_Types_v3.xlsx)

**Comment by kbwagner** [comment]
@Piglady64 thanks for doing this.  As we discussed...for now admin and system admin are the same so they can be combined.  

Otherwise this looks good.  Once it's udpated we should posted to the BACOP and also find a good home on Github I guess and or U:/usajobs/open opps but guess we're moving away from the share drive.

**Comment by Piglady64** [comment]
Put in BACOP Slack Channel on 6/12/19

**Comment by kbwagner** [comment]
[Open_Opps_User_Types_v4.xlsx](https://github.com/openopps/OpenOppsTasks/files/3282238/Open_Opps_User_Types_v4.xlsx)

This is complete - closing
