### ISSUE TITLE
Create definition of Ready documentation for Open Opps

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#191]
Definition of Ready document

Can be stored here: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/Atlas/_dashboards?activeDashboardId=8b77b59b-bd42-408a-b4e1-70a234a730ea

Definition of Done needs to be done by the development team

**Comment by kbwagner** [comment]
@NObiako I mentioned this to Brice today and he said the development team needs to write the definition of done so I changed this to only be definition of ready

**Comment by NObiako** [comment]
Submitted bullet points for DOR to Brice for discussion in Retro

- Who / What / Why Defined (Value Statements)
- Acceptance criteria/  Expected outcome defined
- Designate as “manual testing required”
- Bugs and Backlog items that impact what the user sees (specifically UI items) will be manually tested.
- Bug has been reproduced by BA
- Design is complete and uploaded (if applicable)
- Signoff (Approval) from PO is received

**Comment by kbwagner** [comment]
@NObiako I'd add:
- Public link to mock is included (if applicable)
- Point of contact/BA is assigned to ticket
- PBI is related to an Epic/Feature (if applicable)

**Comment by NObiako** [comment]
Good points. The initial list is a starting point for discussion tomorrow. Once we have a team consensus, I can put the finished list for both DOR and DOD criteria in a PPT and store the doc on the U drive after the Retro.

**Comment by kbwagner** [comment]
@NObiako we reviewed this and the definition of done during sprint planning today.  It is posted in TFS.  If you're happy with it feel free to close.  Brice said we can review each sprint review as well for any necessary updates.
