### ISSUE TITLE
Create content for the "close out internship" modal

### ISSUE THREAD

**Issue by Piglady64** [openopps/OpenOppsTasks#193]
@dalenard21 

When the HM closes their internship opportunity they will get a confirmation modal https://opm.invisionapp.com/d/main#/console/15360465/368187817/preview.

Here is a draft to get you started: 
Are you sure you want to close this internship?
You haven’t marked these interns completed and they will not get credit. Do you still want to close this internship opportunity? Once you close it, you will not be able to re-open it.

If you need to go back and complete any of the interns above, choose cancel. If you are ready to close this internship opportunity, choose close. 

Here is what it looks like in production for reference
![Screen Shot 2019-06-12 at 3.04.15 PM.png](https://images.zenhubusercontent.com/5b59d12efee5ed0b01c00008/8c2b6c29-53ef-4a03-98a6-d4e149cc07fc)

**Comment by dalenard21** [comment]
@Piglady64 
[Department-of-state-student-internship-close-internship-modal_20190613.docx](https://github.com/openopps/OpenOppsTasks/files/3287665/Department-of-state-student-internship-close-internship-modal_20190613.docx)

Let's try this message. Feel free to edit.
