### ISSUE TITLE
Applicant Status Help Text

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#194]
Create help text that can be accessed from the landing page for both regular and internship applicants.  
- should we create separate pages for these?  Or one page with jump link?

Internship application status values:
- In progress - The applicant has started the application process and saved but not submitted
- Submitted - The applicant has submitted their student intern application
- Not selected - When the non select email has been sent from ATP, pull the information and mark those applicants as non selected.
- Selected - when the selected email has been sent from ATP, pull the information and mark those applicants as selected.
- Completed - an applicant has completed the task or internship

Regular Opportunity status values:
- Applied - opportunity applied to
- Assigned - applicant selected and moved to assigned participant status
- Not assigned - applicant not selected
- Complete - assigned participant completed task

Student landing page applicant status view:
![image](https://user-images.githubusercontent.com/18709918/59458000-89c71c00-8de7-11e9-8643-1931c7fa07f7.png)

Federal user landing page applicant status view:
![image](https://user-images.githubusercontent.com/18709918/59458232-0bb74500-8de8-11e9-85db-6790370700fe.png)

**Comment by kbwagner** [comment]
This is ticket development ticket 3613.  

@abudz19 do you have any thoughts on where the "? Help" link should go on the landing page for applicants to view application status info?

**Comment by dalenard21** [comment]
@kbwagner @Piglady64 here is my first draft of this help page. I put it into one page, and I think we can just 'anchor' to the student internship section.  But, I'm open to your opinion on if we should make it two pages.

Question - for the internship "you've been selected' status, is there anything else we want to tell them? I assume they will have received the email by the time this status shows up.

[Open-opps-help-center-what-does-the-application-status-mean_20190617.docx](https://github.com/openopps/OpenOppsTasks/files/3297997/Open-opps-help-center-what-does-the-application-status-mean_20190617.docx)

**Comment by abudz19** [comment]
@kbwagner top right hand corner of the card?

**Comment by kbwagner** [comment]
@abudz19 this is on the landing page....I originally thought maybe somewhere by the sort by (screen shot above) but that's far away from the application status...would it be too much to put it  by the field header Application status?

**Comment by abudz19** [comment]
It looks a bit cluttered with the help text next to status. 

<img width="729" alt="Open_Opps_-_Dept_of_State__master_-AB" src="https://user-images.githubusercontent.com/11526811/59625620-c6588780-9107-11e9-93e5-e71ac655c9cd.png">

**Comment by kbwagner** [comment]
@abudz19 - agreed...if we leave if top right...should we add help text related to program and cycle as well @dalenard21 ?

**Comment by dalenard21** [comment]
@abudz19 @kbwagner @Piglady64 

here's an updated version of the help text for application status. This includes updates to the internship application status, adding an 'assigned' and 'not assigned' status so they can track who actually showed up.  let me know if this is still what you want.

@kbwagner re: the help content for program and cycle, right now there's just one program, so I don't think we need help for that.  maybe once there are other internship programs?

[Open-opps-help-center-what-does-the-application-status-mean_v2_20190621.docx](https://github.com/openopps/OpenOppsTasks/files/3315257/Open-opps-help-center-what-does-the-application-status-mean_v2_20190621.docx)

**Comment by kbwagner** [comment]
6/27/19 - @dalenard21 I reviewed the content and it looks good
@Piglady64 - did we finalize a new word for not selected but not your fault?

@dalenard21 let me know if we can get a URL for this to plug into the ticket.  I think this will go into the next sprint.

**Comment by Piglady64** [comment]
@kbwagner No we haven't finalized a word for "not selected but not your fault"

**Comment by dalenard21** [comment]
@kbwagner @Piglady64 

In the word doc I suggested adding an 'assigned' and 'not assigned' status. "Not assigned" = you weren't selected because you were selected as an alternate and were no longer needed for the internship.

Does that work?

**Comment by dalenard21** [comment]
@kbwagner @Piglady64 

This is the url to use: 
https://usajobs.github.io/openopps-help/opportunity/application-status/

Here's the page in the test 'federalist' site:
https://federalist-proxy.app.cloud.gov/site/usajobs/openopps-help/opportunity/application-status/ 

Take another look at the status and their definitions to make sure they make sense.  Thanks.

**Comment by kbwagner** [comment]
@Piglady64 I'll let you look at the status suggestions above since you've been working on that close process.  
- I can think more about this on Monday too.

**Comment by dalenard21** [comment]
@kbwagner @Piglady64 

The content is now in production.  I'm closing this issue, but if you want to review the definitions and have any changes, just submit a new issue.

https://usajobs.github.io/openopps-help/opportunity/application-status/
