### ISSUE TITLE
Update applicant modal

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#195]
![image](https://user-images.githubusercontent.com/18709918/60204991-22b15a80-981e-11e9-97b1-b368b94a094c.png)

Add info to the application modal to encourage users to update their biography on USAJOBS and Skills (otherwise their profile is pretty blank and meaningless)

Related ticket: https://github.com/openopps/openopps-platform/issues/3667

**Comment by dalenard21** [comment]
@kbwagner what about:

I've updated my profile to include my biography and skills (optional, but recommended)

or

I've updated my profile, including my biography and skills (optional, but recommended)

Thoughts?

**Comment by kbwagner** [comment]
@dalenard21 I like the second one I've updated my profile, including my biography and skills (optional, but recommended)

I can update the ticket and if you're happy with this one we can close this task. Thanks!

**Comment by dalenard21** [comment]
@kbwagner yes, let's go with the second one.  Once you update the ticket, I'll close this.

**Comment by kbwagner** [comment]
Ticket updated....closing
