### ISSUE TITLE
Release 7.8 Release notes

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#196]
Katrina to provide draft
Debbie to review
How to get posted to help center? Brice?

Date needed for posting 7/15/19

@dalenard21 and @tlorrison the What's new page is getting pretty long.  Do we just keep adding to it?  Do we archive the old stuff and maybe only show a release or two?
https://usajobs.github.io/openopps-help/what-is-new/

**Comment by kbwagner** [comment]
@dalenard21 @tlorrison draft release notes attached.
[Release.7.8.Release.Notes.docx](https://github.com/openopps/OpenOppsTasks/files/3370399/Release.7.8.Release.Notes.docx)

**Comment by dalenard21** [comment]
@kbwagner thanks, I'll take a look at the release notes.  I agree it's time to move some of the releases to an archive.  Matt did that with the JOA playbook release notes, but I'm not 100% comfortable doing that code.  Here's a link to how it's done in the playbook https://usajobs.github.io/ATP-Support/job-announcement-playbook/release-notes/

Is that what you're looking for?  When Brice gets back, we can ask him to help ?

**Comment by kbwagner** [comment]
@dalenard21 yes I like the way they are archived. I had also thought about putting the release number by the date and see that they did that on USAJOBS too so maybe we also add that.  

I'll create another task to work with Brice on this so this task doesn't get overtaken.  Thanks!

**Comment by dalenard21** [comment]
@kbwagner I've updated the release notes.  You can see the page in the federalist test site:

https://federalist-proxy.app.cloud.gov/site/usajobs/openopps-help/what-is-new/

When Brice gets back, he needs to push this to production.

**Comment by kbwagner** [comment]
@bmcorum here is the link in federalist for the release notes for today: https://federalist-proxy.app.cloud.gov/site/usajobs/openopps-help/what-is-new/

**Comment by dalenard21** [comment]
Release notes are in production here:

https://usajobs.github.io/openopps-help/what-is-new/

Work complete. Issue closed.
