### ISSUE TITLE
Determine how to open internship from saved right rail

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#198]
Related ticket: https://github.com/openopps/openopps-platform/issues/3520

When an applicant has saved internships and begins the application process, the internships display in the right rail of the selection page.
State has requested the ability for the applicant to click on the internship that they have saved to view the internship again prior to applying.
- Need to determine what adds the internship to the selection vs what opens the internship for viewing (and thus takes the user away from the page)

Alex options: 
1) we can just make the link header go to the internship (open in a new window) and then I believe there is an add button that actually adds the internship currently.
2) adding a second link above or below select that says view (which will open the opportunity into a new window

**Comment by abudz19** [comment]
Both mocks are wired, and purple text is simulating a previously clicked link.
- [Option 1](https://opm.invisionapp.com/share/ZEPNZR09Q54#/372984499_State_-_Programs_-_Preview_Option_2)
- [Option 2](https://opm.invisionapp.com/share/ZEPNZR09Q54#/372984500_State_-_Programs_-_Preview_Option_1)

**Comment by kbwagner** [comment]
@abudz19 I like option 2 better so there is a clear difference.  Either we'd have to open it in the same window though or make it a modal (without an apply button).  That's what I'm thinking at least.  

Adding @tlorrison and @Piglady64 to take a look.
- This isn't likely going to be in the next sprint but would be good to decide so we can shelve the ticket at least.

**Comment by dalenard21** [comment]
@kbwagner @abudz19 I think we need to be consistent in the process of 'adding' an internship as one of their selections.  For example, if a user has no saved internships, when they click select 1st choice and then click on an internship, they get to see the internship and then must click apply to add it as one of their selections.  The process/flow should be the same for the saved internships.  If they click one of their saved internships, they should see the details and then click apply to add it as one of their selections.  I don't think we should make it a different process for saved internships.

So, my vote is option 1

**Comment by abudz19** [comment]
@dalenard21 I see your point and that would be more consistent. We would need to remove the "select" off each card and just display "selected" if it's in one of the three slots.

**Comment by dalenard21** [comment]
@abudz19 I think that would work.  @kbwagner thoughts?

**Comment by kbwagner** [comment]
@abudz19 @dalenard21 I can go with that suggestion.  That's fine.  

So clicking on internship opens it in (same window) with an apply button
Once apply then it changes to "Selected"

Correct?

**Comment by abudz19** [comment]
Right.

**Comment by kbwagner** [comment]
@abudz19 do we need to remove the "Select" off of Option 1 then?

**Comment by kbwagner** [comment]
Development Ticket: https://github.com/openopps/openopps-platform/issues/3520

**Comment by abudz19** [comment]
The dev ticket as written looks good to me. Thanks!

**Comment by kbwagner** [comment]
@abudz19 making sure you saw my question above too - so we will remove the "Select" option and only show when "Selected" correct?  I can make a note that it won't match the mock but wanted to verify.
