### ISSUE TITLE
Look at Open Opps welcome page

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#201]
wondering if we need to look at this welcome page again...I've gotten a lot of questions from new Open Opps users who seem to just put their email in the returning users section and don't get an email back and keep trying.  They aren't getting they are new users to Open Opportunities.   A few thoughts - 1) Add Open Opps to the labels 'New Open Opportunities user?  Start here." or "Returning Open Opportunities user?  Link your profile."  They seem to think they aren't a new user...since they have gone through login and USAJOBS.
2) Not getting the confirmation email continues to be an issue.  they just think the system is broken when they don't get an email and start trying other email options.   I know we have to be cautious with security but can we say something like "If we find a matching account, you'll receive the confirmation email."  (I had a site just this week that did that).  Or give a timeline of emails?  I've had multiple people wait 2-3 days thinking the email might still come.  Open to other suggestions...just throwing this out.  Seems simple enough but also seems to be one of the questions I'm answering the most.  Rather than try the new user option they just keep trying other emails to link and then not getting confirmations.  Thanks! (edited) 
![image](https://user-images.githubusercontent.com/18709918/62481050-5e293800-b77f-11e9-811e-55629f24993a.png)

**Comment by dalenard21** [comment]
@kbwagner @abudz19 @tlorrison I'm back from vacation and I think there's been some discussion on this page, outside of this ticket.

@abudz19 @tlorrison was there a decision to remove this page?  Did you all decide on a direction?  Let me know if you need me to relook at the content, because clearly it's not working.

**Comment by abudz19** [comment]
@dalenard21 Yes, we are removing the page. I already wrote the platform ticket.
