### ISSUE TITLE
Create data dictionary for dashboard metrics

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#202]
Sitewide, agency and community administrators have access to metrics on their dashboards.  It's important we define each metric and explain how it was calculated.

@dalenard21 I'm thinking we just put a question mark help on the dashboards and it links to the help center but maybe in a different section since it's a limited audience?
- I can put together the calculation information but could you help write it in more english than techie speak?

Related ticket: https://github.com/openopps/openopps-platform/issues/2381

**Sitewide Admin:** 

1) User Section:  (ticket 2363)
![image](https://user-images.githubusercontent.com/18709918/64645142-36fb0180-d3e2-11e9-865b-877b79a8f46e.png)
Total Users: Number of users who have created an account in Open Opps whether they are disabled or enabled
Active Users: Number of users who have an active account in Open Opps that has not been disabled
Admin: Number of active users who are a sitewide administrator

2) Opportunities:  (ticket 2364)
![image](https://user-images.githubusercontent.com/18709918/64645284-8d684000-d3e2-11e9-8af7-30b2c9aa673e.png)
Total Created - Total created’ should be the total number of Opportunities sitewide for all statuses including cancelled but NOT including draft
Submitted: Total number of opportunities sitewide that are currently in Submitted status
Open: Open will include both open and in progress accepting applicants opportunities sitewide
Not open; Total number of opportunities in not open status sitewide
In progress: Will include only in progress not accepting applicants opportunties. Omit in progress opportunities that are accepting applicants. Sitewide
Completed: Total number of sitewide opportunities in Completed status
Canceled: Total number of sitewide opportunities in Canceled status
No data on drafts will display at this time

3) Interactions (ticket 2365)
![image](https://user-images.githubusercontent.com/18709918/64645366-c4d6ec80-d3e2-11e9-9313-63246410016e.png)

Total applications - total number of everyone who has applied to an opportunity sitewide. Not unique applicants. This should anyone who has applied that is an applicant + assigned participant + task completed. As an example, if I have applied to 4 opportunities, I will count as 4 applications.
Total assigned - Total number of applicants who were moved to assigned participants for all opportunities sitewide. Includes Task completed. Not unique.
Total completed: only those participants who have been marked as task completed. Not unique participants.
Discussion posts: Total number of comments and reply to comments for all opportunities sitewide

4) Top Contributors --> Opportunities Created (ticket 2366)
![image](https://user-images.githubusercontent.com/18709918/64645818-b6d59b80-d3e3-11e9-8e57-a1f2bf83f70d.png)
Agency: Display top 5 by created number
Agency - display the agency name of the creator. Display all agency/subagency information provided (i.e. DHS/Customs)
of opportunities created - display the total number of opportunities created whether published or not. (does not include drafts) in the current fiscal year
The default sort will be sorted by greatest to least number.
Display for agency should be agency/department when possible (e.g. NIH/HHS or FSIS/USDA) name so we can see who our biggest users are, as well as where we need more outreach)

5) Top Contributors --> Participating in Opportunities (ticket 2367)
![image](https://user-images.githubusercontent.com/18709918/64645723-7d9d2b80-d3e3-11e9-9b29-6f72be7b7b8c.png)

List the agency and the # of opportunities participated (not applied but actually selected to participate)
For agency, list the agency/department as possible to provide as much info for outreach
-# will be the number of participants and task completed for opportunities for that agency
Sort order will be by opportunity participated number

6) Opportunities Section (ticket 2369)
![image](https://user-images.githubusercontent.com/18709918/64645091-1c288d00-d3e2-11e9-9175-027d2a455af0.png)

o Carryover (Not completed)- this row will display data for any opportunities opened (published) in a previous selected time period that have not yet been completed.  
o Published - opportunities published in the selected time period
o Completed - opportunities completed during the selected time period by the opportunity creator
o Completed by admin - opportunities completed during the selected time period by the administrator
o Percentage completed - of the number opened in the time period selected how many were closed
o Percentage canceled - of the number opened in the selected time period, how many were canceled
o Applicants - number of applicants to opportunities within the selected time period that applied to completed opportunities.

Full Sitewide Admin screen shot: 
![image](https://user-images.githubusercontent.com/18709918/64645974-0b791680-d3e4-11e9-988d-100e30c5b475.png)

**Comment by dalenard21** [comment]
@kbwagner yes, happy to help.  just send my way when you're ready.

**Comment by kbwagner** [comment]
@dalenard21 I put all of the info in for the Sitewide Admin data.  Some of it will be slightly different for the Agency and Community dashboards.  I have those tickets written but need to give you all of the info.  But this is a good start and most of it will be similar but limited to the agency or the community so we can probably just call out anything different.  Thanks!

**Comment by dalenard21** [comment]
@kbwagner what's the priority for this one?

**Comment by dalenard21** [comment]
Added issue in team design repo https://github.com/USAJOBS/team-design/issues/74

**Comment by kbwagner** [comment]
@dalenard21 low - it's already out there in production just not with anything to explain it.  So it can go behind any other major priorities as a nice to have.  Maybe we could say Jan/Fed?  Just to get it done.

**Comment by kbwagner** [comment]
This is in https://github.com/USAJOBS/team-design/issues/74 closing
