### ISSUE TITLE
Add help text for update and withdraw function

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#209]
Issue: Students do not understand how to withdraw their application.  most are withdrawing because they want to pull updates over from their USAJOBS profile and will resubmit

Once logged in, they should click on their name in the navigation which will take them to their landing page, they should click on the link in the program column, it will open their existing application and they can update or withdraw.

We have an existing help question mark on the landing page for application status...so perhaps the same question mark help page can have content with withdraw...and maybe even update?

![image](https://user-images.githubusercontent.com/18709918/65722556-767c4b80-e07a-11e9-9e45-221ddbf3e88d.png)

When the cycle link is clicked: 
![image](https://user-images.githubusercontent.com/18709918/67692583-bcc51300-f976-11e9-8079-88971d5645e3.png)

When Update is clicked, the following modal appears and clicking update takes you to the internship selector page
![image](https://user-images.githubusercontent.com/18709918/67692623-d23a3d00-f976-11e9-9734-ebc218b82318.png)

When withdraw is selected: 
![image](https://user-images.githubusercontent.com/18709918/67692720-fa29a080-f976-11e9-8837-ffedec4e2743.png)

Goal: before the next internship apply cycle which I believe is January 2020; should be in place for release 8.4; December 2nd

**Comment by dalenard21** [comment]
@kbwagner I can write some help text on how to withdraw an application, but is anyone looking into how we can get their application updated without having them to withdraw?  It's not logical for a user to have to withdraw their application just so they can submit an updated one.

**Comment by kbwagner** [comment]
@dalenard21 - per our conversation last week I added some screen shots in here that might help.  

and I thought I answered your question above but yes we are working on the USAJOBS data flow which would solve the issue of having to withdraw to get data updated but not likely going to be ready for the next release.

**Comment by dalenard21** [comment]
@kbwagner 

Here is a draft of help content for how to withdraw an application.

I'm also going to write content for how to update an application.

Please review and let me know what you think.

[Department-of-state-how-to-withdraw-application_20191125.docx](https://github.com/openopps/OpenOppsTasks/files/3892553/Department-of-state-how-to-withdraw-application_20191125.docx)

**Comment by kbwagner** [comment]
@dalenard21 the only change I have is that they can't withdraw at any time.  They can only withdraw while the application cycle is open.  This may change because I have a current email from State about this but for the time being that's where it stands

**Comment by kbwagner** [comment]
@dalenard21 this would be good to get in place before the next apply cycle which is unofficially mid January.

**Comment by dalenard21** [comment]
@kbwagner 

I've revised the How to withdraw to remove the part about 'at any time' and added a sentence before the steps to say you can only withdraw while the application period is open.

I've also attached a draft of "How to update".  Let me know what you think.

[Department-of-state-how-to-update-an-application_20191218.docx](https://github.com/openopps/OpenOppsTasks/files/3979800/Department-of-state-how-to-update-an-application_20191218.docx)
[Department-of-state-how-to-withdraw-application_v2_20191218.docx](https://github.com/openopps/OpenOppsTasks/files/3979801/Department-of-state-how-to-withdraw-application_v2_20191218.docx)

**Comment by kbwagner** [comment]
@dalenard21 reviewed withdraw - looks good.  Will look at udpate soon.

**Comment by kbwagner** [comment]
@dalenard21 reviewed update and no changes.  Looks good. 

Thanks!  Let me know when they are ready to be pushed out. the next push is 12/30 and then after that mid January I believe.  Since these are state specific we'll want to make sure they are noted as such I guess or not in the general applicant section.

**Comment by kbwagner** [comment]
@dalenard21 FYI with our release on 1/27/20 we will allow students to withdraw even after the apply cycle has closed.
- Would be good to get this help text in by 1/27 as well if possible.

**Comment by dalenard21** [comment]
@kbwagner @abudz19 

Do you think we need to get the "Communities" section in place so this content has a better home? 

Or we add a section called "Internships" where this content can live.

Or we put this content under "opportunity" and add a sentence at the top of each page to say "This help content is for U.S. Department of State Internship (Unpaid) applicants." That's the easiest approach, but the most confusing.

**Comment by kbwagner** [comment]
@dalenard21 I think originally we discussed the third option.  Which is pretty much what we do now for statuses.  I think we do that to get it out.

But...if we are able to get the community help up and running or create a new section for internships with our Github developer, then we take a look at possibly move a  bunch of that stuff over.

**Comment by kbwagner** [comment]
@dalenard21 did this get done?  if not, I can move it over to the design board.
