### ISSUE TITLE
Create System Requirement Specification Document to start the Authority to Operate Process

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#21]
**Old Trello URL:** https://trello.com/c/hw2xm8BL/159-create-system-requirement-specification-document-to-start-the-authority-to-operate-process

**Checklists:**

**Attachments:** 

**Comments:**

**Comment by kbwagner** [comment]
@tlorrison is this document complete?

**Comment by kbwagner** [comment]
@tlorrison I believe this part is complete.  Can we close?

**Comment by tlorrison** [comment]
All documents from PMO have been submitted in support of the ATO
