### ISSUE TITLE
Email content: Reminder your internship is about to close

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#210]
Needed by: Tuesday 10/29

We would like to send an email reminder to internship applicants who have not completed their application 3 days prior to the close date of the application cycle.

I believe we do this for USAJOBS?  @dalenard21 do you have a copy of the language we use for USAJOBS that we could leverage?

Goal due date: mid to late October

Related Github ticket: https://github.com/openopps/openopps-platform/issues/4001

For reference:

Email from USAJOBS that a job you saved closes in 3 days: 
USAJOBS – Your saved job is closing soon.
Hello [[GivenName]], 
The following job that you’ve saved in your USAJOBS profile will close in three days. Once a job closes, you can no longer apply or make updates to your application and we’ll remove the job from your profile. 

Job title [Insert job announcement link] 
Announcement #: [[PositionID]]
Agency Name: [[OrganizationName]] 
Job Title: [[PositionTitle]] 
Series & Grade: [[SeriesGrade]] 
OPM Control Number: [[DocumentID]] ** 

View all saved jobs 

The USAJOBS Team
U.S. Office of Personnel Management 
1900 E Street NW. 
Washington, DC 20415 
About this message
To make sure you get USAJOBS emails in your inbox (and not your spam) add "notifications@usajobs.gov" to your address book.
Unsubscribe from saved job emails. | Unsubscribe from all email notifications.
If you doubt the authenticity of a USAJOBS email, please visit the USAJOBS site using your browser or read our Help Center article on this topic.
Please do not reply to this message. Replies to this message go to an unmonitored mailbox.
Have questions or comments? Visit our Help Center at usajobs.gov/Help/.

Email from USAJOBS that a job you applied for has closed:
Hello [[GivenName]], 
The job below has closed. You can no longer make updates to your application. 

Announcement #: [[PositionID]] 
Agency Name: [[OrganizationName]] 
Job Title: [[PositionTitle]] 
Series & Grade: [[SeriesGrade]] 
OPM Control Number: [[DocumentID]] 

Check status of job application

The USAJOBS Team 
U.S. Office of Personnel Management 
1900 E Street NW. 
Washington, DC 20415 
About this message
To make sure you get USAJOBS emails in your inbox (and not your spam) add "notifications@usajobs.gov" to your address book.
Unsubscribe from job status emails. | Unsubscribe from all email notifications.
If you doubt the authenticity of a USAJOBS email, please visit the USAJOBS site using your browser or read our Help Center article on this topic.
Please do not reply to this message. Replies to this message go to an unmonitored mailbox.
Have questions or comments? Visit our Help Center at usajobs.gov/Help/.

**Comment by kbwagner** [comment]
Email content manually sent 10/3: 
Hello,
The application period for the U.S. Department of State Student Internship Program (Unpaid) will close tomorrow, October 4, 2019, at 11:59pm ET. 
It looks like you have started an application, but have not submitted it.  If you’re still interested in applying to the internship program, click the link below to submit your application before the application period closes.

Sign into Open Opportunities to submit your application.

Thank you,

The Open Opportunities Team
U.S. Office of Personnel Management 
1900 E Street NW. 
Washington, DC 20415

**Comment by kbwagner** [comment]
Note: for the real email we may want to add a line that says if you have already submitted please disregard this message or we apologize for the inconvenience or something...and tell them how to verify they have submitted on their dashboard...have gotten some emails from people that submitted after we pulled the email list.

**Comment by dalenard21** [comment]
@kbwagner I can revise the email.  Will the newer email be sent by Open Opps? Can we input a 'date', so instead of saying it will close in X days, can we always include the date of when the cycle will close?

Do we have any way of knowing what internship they may have started their application for?

**Comment by kbwagner** [comment]
@dalenard21 yes this new email should be sent via Open Opportunities so we should be able to insert form fields...but they might have selected three internships as part of their application so would you want all 3 to display?  We can.

We should be able to display the date it's closing.  Brice has some concerns about the cycle date changing and the email being compromised but Michelle really wants this to go out and be automated so we'll have to work through some things.

**Comment by dalenard21** [comment]
@kbwagner what about this version of the email:
Hello, 
The application period for the U.S. Department of State Student Internship Program (Unpaid) will close on [insert date].

 It looks like you have started an application, but have not submitted it. If you’re still interested in applying to the internship program, click the link below to submit your application before the application period closes.

[Sign into Open Opportunities to submit your application](link to Open Opps).

Did you already submit your application?  Great!  You can check the status of your application on your [Open Opportunities dashboard](link to Open Opps dashboard).

Thank you,
The Open Opportunities Team U.S. Office of Personnel Management 1900 E Street NW. Washington, DC 20415

**Comment by dalenard21** [comment]
@kbwagner did you get a chance to review this?  thoughts?

**Comment by kbwagner** [comment]
Sorry I didn't get the github notification so hadn't seen this yet.  Adding it to my list for today.

**Comment by kbwagner** [comment]
@dalenard21 this looks good.  Should we say on here to make sure you always submit after you make any changes?  Or leave that be for now.  Working on other solution for those people

**Comment by kbwagner** [comment]
@dalenard21 please also add closing time to this as well.  11:59 PM ET

**Comment by dalenard21** [comment]
@kbwagner How about this:

Hello, 
The application period for the U.S. Department of State Student Internship Program (Unpaid) will close on [insert date] at 11:59pm EST.

 It looks like you have started an application, but have not submitted it. If you’re still interested in applying to the internship program, click the link below to submit your application before the application period closes.

[Sign into Open Opportunities to submit your application](link to Open Opps).

Did you already submit your application? Great! You can check the status of your application on your [Open Opportunities dashboard](link to Open Opps dashboard). If you need to make an update, don't forget to submit your application again.

Thank you,
The Open Opportunities Team U.S. Office of Personnel Management 1900 E Street NW. Washington, DC 20415

**Comment by kbwagner** [comment]
@dalenard21 this look  good.  Thanks!  You can close this

**Comment by dalenard21** [comment]
Thanks @kbwagner. Closing this issue.
