### ISSUE TITLE
Release notes for 8.1 releasing 10/21/19

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#211]
Katrina to provide draft Debbie to review
![image](https://user-images.githubusercontent.com/18709918/66926297-c86e1c80-effb-11e9-84f6-b12748f78515.png)

**Comment by kbwagner** [comment]
@dalenard21 if you have a chance, can you please review this week and get ready for these to be pushed out Monday?  Thanks!

**Comment by dalenard21** [comment]
@kbwagner changes made and it's ready to be pushed out to production.
https://federalist-proxy.app.cloud.gov/site/usajobs/openopps-help/what-is-new/

**Comment by kbwagner** [comment]
These are now posted to production - closing
