### ISSUE TITLE
Release notes for 8.2 releasing 11/4/19

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#212]
Draft release notes for Debbie review (I just provided the basic bullets but didn't try to make sound pretty).  Thanks!

Release date 11/4/19

![image](https://user-images.githubusercontent.com/18709918/66924879-6dd3c100-eff9-11e9-9d66-002122638224.png)

**Comment by kbwagner** [comment]
@dalenard21 - any chance you can take a look at these by tomorrow 10/29?  Brice will be out after Wednesday so I may have him to the help center push before he leaves and just have it out there early.

**Comment by dalenard21** [comment]
made the edits.  view them here:
https://federalist-proxy.app.cloud.gov/site/usajobs/openopps-help/what-is-new/

ready for release

**Comment by kbwagner** [comment]
@dalenard21 Brice made the updates today.  Feel free to review and close this.

**Comment by dalenard21** [comment]
@kbwagner yep, change is in production.

https://usajobs.github.io/openopps-help/what-is-new/

Closing issue.
