### ISSUE TITLE
Create/finish saved search tickets based on design

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#233]
Goal to finish no later than 5/25 to get into the following sprint.

**Comment by kbwagner** [comment]
Katrina to review and then will close

**Comment by kbwagner** [comment]
@eponsonby I finally got through these.  I tagged you on a couple of questions:
- 44451
- 44431
- 43182
- 44564

Looks like I missed reviewing one too so will do that now

**Comment by eponsonby** [comment]
@kbwagner changes are ready for you to review

**Comment by kbwagner** [comment]
@eponsonby looks good thanks!
