### ISSUE TITLE
Decide how to handle opt-outs and bounced/rejected email addresses in MyEmma

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#24]
**Old Trello URL:** https://trello.com/c/n44r0fUG/146-decide-how-to-handle-opt-outs-and-bounced-rejected-email-addresses-in-myemma

**Checklists:**

**Attachments:** 

[error_optout_audience_export_02_08_2018.1518103465.csv](https://trello-attachments.s3.amazonaws.com/59df9ff7b7b887ebae452662/5a7c6bd016960a89a09ecb35/12d92b7c1f279da3da106b72264b856b/error_optout_audience_export_02_08_2018.1518103465.csv)

**Comments:**

**Comment by abudz19** [comment]
@LisaLNelson I suspect that rejected email addresses probably has more to do with email security in place by agencies and less to do with MyEmma.

**Comment by abudz19** [comment]
@LisaLNelson I would say not to delete them because they don't get rejected every time. Can we close this issue?
