### ISSUE TITLE
Set up accounts on Max so we can access community manager forum documents

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#243]
https://portal.max.gov/portal/home

**Comment by kbwagner** [comment]
5/21/2020 - I emailed max support on my account because I have an old one and it won't let me in.

**Comment by kbwagner** [comment]
@eponsonby I finally got my max account set up so I can see Keenan's community manager forum notes.  I'll leave this open until you have a chance to do this too.  Mine was a pain only because I had an old account they had apparently deactivated.

Community manager forum page on Max: https://community.max.gov/pages/viewpage.action?spaceKey=Egov&title=Open+Opportunities#comment-2120779111

**Comment by eponsonby** [comment]
@kbwagner I set this up when Keenan mentioned it a few weeks ago :)

**Comment by kbwagner** [comment]
@eponsonby great - closing.  Thanks!
