### ISSUE TITLE
Discuss Editing a Saved Search

### ISSUE THREAD

**Issue by eponsonby** [openopps/OpenOppsTasks#266]
This process is a little confusing. When you click to edit a saved search, add/remove filters or pills and then click cancel, the search does not save (as is expected) but the visible pills and filters retain the changes. So it's hard for the user to tell what the saved search looks like without going back home and reopening it. Need to discuss how we can refine this process.

**Comment by kbwagner** [comment]
Discussed - let's see if we have issues when this is live
