### ISSUE TITLE
 tickets For Admin Pages Overhaul

### ISSUE THREAD

**Issue by eponsonby** [openopps/OpenOppsTasks#270]
- Reorganizing the dashboards (sitewide, agency, communications)

- the community admin tab itself.  May end up being quite a few tickets.  https://opm.invisionapp.com/d/main?origin=v7#/projects/prototypes/19985649

**Comment by kbwagner** [comment]
@eponsonby 46208 is on the backlog for reorganize community pages (shell).  Can use it or remove whichever just noting

**Comment by eponsonby** [comment]
@kbwagner Okay thanks for the heads up, I'll take a look!
