### ISSUE TITLE
NOAA: Create opportunity tickets

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#284]
Date needed: no later than 8/19

1) Verify requirements against design - let Alex know if anything is missing; 
https://opm.invisionapp.com/share/W7XSG0Q2RVD#/422495659_Create_-_Part-Time_Detail

**Requirements**
-	Would like co-owner functionality – this is live as of 6/26/20
-	Emails to notify of submitted opportunities will only go to the line office community manager not the overall community manager (Tracy)
-	Add new ticket - If a user is associated to multiple line offices, provide a way for them to determine which line office should be listed on the opportunity (add to create)
When section:
-	Rename Ongoing to “Recurring” and remove the “Requires up to 20 %...” sentence
-	Limit participation will only be for NOAA.  Not to line offices.(i.e. do not show limit to NWS)
-	Add help text for “Is this detail reimbursable?” (content ticket and a question mark ticket)
-	Add Estimated start date (optional)
-	Estimated completion date: update example date to be future date  
-	When are applications due (optional)

Where: 
-	Add question mark and help text around the options for in person and virtual.  
o	(content ticket) - Suggest taking the entire create form and creating help and having a question mark for each section
o	Consider adding it under each label
-	Allow for multi select In person, Virtual, Negotiable
o	Display OR between if multi selected on opportunity page
o	Would display for both in search
o	Remove allow virtual under 
o	Make checkboxes instead of icons
-	For In person, 
o	add optional fields for Host office will pay for travel and lodging Yes/No/Open for discussion

Pay Scale/Grade: 
-	Leave as optional
-	allow for multiple selections, (to and from box for grade)
-	change label from Grade/Band, 
-	change from numerical field to text field to allow for roman numerals and allow for 4 characters
-	Need the ability to add multiple grades (from/to)
-	Create Opportunity - Community managers should have the ability to change the line office of the opportunity if it is wrong
-	Add all new fields to the opportunity .csv
-	Add all new fields to the preview
-	Add all new fields to the duplicate

2) Write any missing tickets

**Comment by eponsonby** [comment]
@kbwagner I've gone through the mock and tagged Alex where changes need to be made with the exception of the Pay Scale/Grade section since we're still figuring out how this section will work

**Comment by kbwagner** [comment]
@eponsonby NOAA is ok to not do the roman numerals so we can proceed with it just being a numeric field for grade

**Comment by eponsonby** [comment]
@kbwagner I think this is done but I'll put it in needs review so you can check

**Comment by kbwagner** [comment]
@eponsonby can you please make sure the create mock link is in all of the tickets?  I added it so the ones I approved I think.  Thanks!

I'll take a look at the rest.
