### ISSUE TITLE
NOAA: Opportunity CSV ticket

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#286]
Goal no later than 8/19

- [ ] 47332 - add all new fields to opportunity .csv and indicate order on the file

- [x] new ticket - make sure all new fields get added to duplicate process

- [x] Toggle tickets 46824 and 47303 - will need to list out all optional fields on community attribute where they can toggle on and off then the second ticket is for the create opportunity to look at what the community has toggled on/off

**Comment by eponsonby** [comment]
@kbwagner I've started all of these but I'll keep it in progress until:

- We discuss the opportunity CSV
- We finalize all new fields that we want to add
- We discuss 46824 layout during a PBI session

**Comment by kbwagner** [comment]
[Opportunity_CSV_Fields.xlsx](https://github.com/openopps/OpenOppsTasks/files/5099221/Opportunity_CSV_Fields.xlsx)

**Comment by kbwagner** [comment]
Written - waiting for Brice to review
