### ISSUE TITLE
Create saved search experience - notifications

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#29]
Item #6 from FAIs contract requests. They'd like push notifications. We're thinking we'd leverage the core saved search feature here. 

### Open questions
There is an open question of whether we had the design would this in fact be supported (Amazon SES?) or are we dependent on Core's email infrastructure build out.

**Old Trello URL:** https://trello.com/c/qzeDngRZ/119-create-saved-search-experience

**Checklists:**

**Attachments:** 

**Comments:**

**Comment by kbwagner** [comment]
We have a saved search experience for students but need to add this to the full Open Opps for regular opportunities as well.

**Comment by kbwagner** [comment]
Design completed
