### ISSUE TITLE
Talk about the future of bug bashes

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#3]
**Old Trello URL:** https://trello.com/c/QmCxlmGR/286-talk-about-the-future-of-bug-bashes

**Checklists:**

**Attachments:** 

**Comments:**

**Comment by kbwagner** [comment]
@tlorrison I'm guessing this can kind of be closed as I think we have a way forward doing our own bug bashes as needed, writing high level scenarios for them to follow, etc.

Thoughts?

@Piglady64

**Comment by Piglady64** [comment]
@kbwagner I think we have this covered. I am not sure if the new person they are hiring for Dywane's position will be doing this or not. When Brody introduced me to the two he interviewed last week he said they were going to be working in Data with PD. I am not sure if we are going to get another testing person or if each team just does their own. TBD
