### ISSUE TITLE
Design for rejecting an opportunity

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#30]
Add a comment box for why the opportunity was rejected, send the rejection email, and display the info to the task creator. 

**Old Trello URL:** https://trello.com/c/qWfyRITr/151-design-for-rejecting-an-opportunity

**Checklists:**

**Attachments:** 

**Comments:**

**Comment by kbwagner** [comment]
Moved to design board https://github.com/USAJOBS/team-design/issues/253
