### ISSUE TITLE
Invite to opportunity - part 2 tickets

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#305]
Waiting for Alex to complete design https://github.com/USAJOBS/team-design/issues/373

Ideally will be ready for 9/3/20 sprint planning

- [x] Dashboard page - 48587 shell ticket

- [x] Default text for creator page when there are no applicants - review content with Debbie - 48588 shell ticket

- [x] add invited section to applicant list in right rail 48586

**Comment by eponsonby** [comment]
Current status - waiting on content from Debbie
