### ISSUE TITLE
Audit of optional fields

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#353]
- [x] Where does the "all fields required unless noted" comment display as they will need to be removed
- [x] Do all optional fields have (optional) beside them (may have to click save/next to get error messaging and verify all that don't have red error messages appropriately say optional)

Check throughout the system but especially:

- [x] profile
- [x] Admin dashboard
- [x] Create opportunity

**Comment by kbwagner** [comment]
@NObiako can you attach the latest file here please?

**Comment by NObiako** [comment]
Latest Version of Optional fields audit
[Open Opps Optional fields Inventory v1.pptx](https://github.com/openopps/OpenOppsTasks/files/5920783/Open.Opps.Optional.fields.Inventory.v1.pptx)

**Comment by kbwagner** [comment]
@NObiako this needs one PBI to remove "All fields are required unless otherwise noted" from all create opportunity pages

**Comment by kbwagner** [comment]
@NObiako I created a placeholder ticket for this https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=53976&_a=edit

**Comment by kbwagner** [comment]
@NObiako I think this one can be closed once the last ticket is written for, "Bug - Community attributes Admin --> Community --> Add new or edit) - Who we are should say "optional" beside it.  This one can also get moved up with the admin dashboard tickets"

**Comment by NObiako** [comment]
@kbwagner Bug ticket was written yesterday so I'll move forward with closing this thread. 
https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/Atlas/_workitems?id=54136&_a=edit
