### ISSUE TITLE
Release notes for admin dashboard release 11.9/12.0

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#357]
@NObiako after sprint planning 3/18 can you write up release notes form 11.9/12.0?
- Existing release notes are on https://usajobs.github.io/openopps-help/release-notes/
- Draft up some content.  May not be a lot of bullets since it's really just admin overhaul and enhancing usability
-  Once you have a draft, create a design ticket on https://github.com/USAJOBS/team-design/issues and then add the labels Open Opps and Content and assign to Debbie.  
- 12.0 goes live 4/16 so I usually ask for it a couple of days before so we can confirm content then she will post it on the release day

Then now that we'll get back on regular releases every two weeks after every sprint planning this will be a task to draft release notes, give to Debbie, etc. 

Let me know if you have any questions.

thanks,

**Comment by NObiako** [comment]
@kbwagner  - Draft has been submitted to Debbie. (Design ticket #503)
