### ISSUE TITLE
Open Opps Celebration Event

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#36]
**Old Trello URL:** https://trello.com/c/Y2oVdYdQ/113-open-opps-celebration-event

**Checklists:**

Checklist - 

   - [ ] need to confirm date with space
   - [ ] Need to confirm budget with Michelle
   - [ ] Need to confirm who to invite/expected numbers of attendees
   - [ ] Plan to execute on week Kat is planning to be in DC (20-22 Feb)
   - [ ] Discuss vision for event with Michelle
   - [ ] Kat to set up meeting with Michelle/Lisa/JodieY to discuss.

**Attachments:** 

**Comments:**

**Comment by kbwagner** [comment]
10/11/18 - Confirming plan with Lisa.

**Comment by LisaLNelson** [comment]
Not sure if or when this will happen.
