### ISSUE TITLE
Newsletter integration tickets 

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#362]
2) Ability to request being added to the newsletter distribution list: 
- Design ticket 176 - Deanna to mock up design of where it might make sense on the home page https://github.com/USAJOBS/team-design/issues/377
- Katrina to look into whether we can limit to official government email addresses (.gov, .mil, .edu) 
- Nnamdi - update 46309 with mock once available and back end requirements: requirements include sending the new email to myEmma via API, and ensuring they aren't added again as a duplicate, and restricting students so only allowing .gov/.mil/and .edu if they are federal (i.e. Smithsonian)
- Nnamdi - can you also create a new design ticket to do usability testing on the signed out and signed in landing pages to consider enhancements based on what people are clicking on please?  

3) auto add new users 
- Nnamdi - please create a new TFS ticket that creates an API with myEmma.  Anytime a new user account is created and they are a fed (not student or contractor), add their email to the API to add as a new email to myEmma.  Can link to the completed research spike 41585

4) allow opt in/opt out 
- I added a note to design ticket 260 which is profile privacy settings that we could also consider the opt in/opt out for the newsletter here when we get to (estimated FY21Q4)

Timelines: 
- This is slated for release 12.1.
- Sprint starts 4/5/21
- Sprint planning for the sprint will be 4/1/21 (Thursday)
- Design would be ideally ready by 3/25 at the latest so tickets could be written and approved by 3/30 (note- I will be out of town starting 3/29 so in the ideal world we could get it all wrapped up by 3/26 but recognize that's quick)
- Release goes live 4/30/21

**Comment by kbwagner** [comment]
@NObiako I created some shell tickets for this work:
- 55344: all all new users to myEmma
- 55345: Add newsletter sign up to open opps footer
- 46309: newsletter sign up on signed out landing page

**Comment by NObiako** [comment]
@kbwagner 
55345: Add newsletter sign up to open opps footer - Approved with mocks
46309: newsletter sign up on signed out landing page - Approved with mocks
55344: all all new users to myEmma - Not ready yet
