### ISSUE TITLE
Prepare report out for 3/30 10:30 status meeting

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#364]
Prepare a report out of what's going on with team atlas for the 3/30 status meeting.  My bullets from this week to use as a starting point: 

-	Skills engine:
o	Looking at usability testing and evaluation metrics for enhancement opportunities for two releases
o	Story telling with lab and engagement
-	Released technical upgrades Friday
-	Next sprint 12.1:
o	Agency table
o	Newsletter integration
o	Backlog
o	Data warehouse research
o	Skills engine metrics (possibly)
-	Design priorities – 
o	co-creation sessions
o	newsletter (Deanna)
o	authentication (affects all teams)
o	Discussion boards
-	Development: 2 sprint admin overhaul
o	Community now – releases 4/16
-	Sprint planning:
-	Next focus:
o	Backlog while we can
o	Spike for data warehouse
o	Discussion boards
o	Student internship marketplace
o	Authentication
o	Google tag manager

**Comment by NObiako** [comment]
Michelle cancelled this meeting on Friday 3/26
