### ISSUE TITLE
Draft 12.1 release notes after 4/1 sprint planning

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#366]
Release notes won't need to include the spike...just anything the users will care about

Likely inclusion: (depends on admin dashboard holdover)
- Agency table updates
- Newsletter integration
- backlog items so those should be listed out separately since they aren't part of a larger feature

Post draft to design board and tag Debbie

**Comment by NObiako** [comment]
Sending to Debbie today
