### ISSUE TITLE
Review TFS 53229

### ISSUE THREAD

**Issue by NObiako** [openopps/OpenOppsTasks#375]
Per Larry - the next to the last line of the ac is not good.  We only show the created date in two places one is on the opportunity csv and the other is on the draft status on the admin dash.  So it never shows on an opp card and only the creator sees that date until it is submitted then it gets a submitted date. Unless you want the csv changed?  then that needs to be added to be more clear

**Comment by kbwagner** [comment]
@NObiako I think it should just say, "Once the opportunity is updated, change the Posted date display the last updated date"  Does that make more sense?

**Comment by kbwagner** [comment]
@NObiako I have 56080 to update the opportunity .csv so I added adding last update to the .csv in that ticket on the backlog

**Comment by NObiako** [comment]
@kbwagner - Changing the posted date display to show the last updated date makes more sense. If it's not too much trouble, can you change the last point on the AC to say that so Larry can complete his test cases? I would do it but I still don't have my access.

**Comment by kbwagner** [comment]
@NObiako done!

**Comment by NObiako** [comment]
@kbwagner - thanks!
