### ISSUE TITLE
Endorsement tickets

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#386]

**Comment by kbwagner** [comment]
@NObiako I think we need a backlog ticket for phase 2 of endorsements which is the ability to view "Your endorsements" as a tab on the dashboard and allow them to hide/delete.  Once that goes in the backlog this ticket can be closed.  Thanks!

**Comment by NObiako** [comment]
@kbwagner  - I'll add the ticket to the backlog and close this request.
