### ISSUE TITLE
Open Opportunities - First pass

### ISSUE THREAD

**Issue by yraza261** [openopps/OpenOppsTasks#39]
We'll get going on Open Opportunities the week of 8/14 (assuming other things don't slip leading up to that date). Some materials to look at:

https://github.com/openopps/openopps-platform/tree/dev/api/notifications

https://openopps.digitalgov.gov/dashboard

https://openopps.github.io/

https://github.com/18F/openopps-design/tree/master/mockups/admin

https://github.com/openopps/openopps-platform/issues?q=is%3Aopen+is%3Aissue+label%3Adesign

https://docs.google.com/document/d/1qRp7F1OmzrQaYhP6_MgpRnOLLEqhYkf_zuoOCLfdokw/edit?usp=sharing_eip&ts=59837d5e

https://docs.google.com/presentation/d/15SWwCmzdTFQqNODqRcOnCo_h6ptW_oJRf9mr5hSpuaQ/edit?usp=sharing_eip&ts=59837f1f

https://docs.google.com/document/d/190lbKtor5lVxJBnrHmvzIbwZ_2sjruPXTFiGHoX2Bls/edit?usp=sharing_eip&ts=59837f85

https://docs.google.com/document/d/1ReKNlEykzBRj0rZAOcXRAsmo-pV5s_JlHeHAA8DVk9Q/edit?usp=sharing_eip&ts=59838052

https://drive.google.com/file/d/0B5ZkkkN_EN7iN3NnOVdkSXhkRk0/view?usp=sharing_eip&ts=59838a84

### What problem does it solve?
Start to make clear that OPM backs Open Opportunities and it is related to but not yet a part of USAJOBS.

### How does it affect the user?
The users are current Federal Employees who are looking for developmental opportunities.

### Why is it better than the alternative?
Exploring these variations:
A. Minimal changes just to apply the design system more succinctly. 
B. We begin to apply more of the USAJOBS visual style to the site.

### Relevant Research
Lisa Nelson is sending over Personas and other documentation.

### Create a hypothesis
Ky to fill this in. 

Here is a template:
We believe that...[hypothesis]. We will do/make...[what we're going to test]. We will know the hypothesis is valid if by [date] we get [quantitative measurable outcomes] and [qualitative observable outcome].

**Old Trello URL:** https://trello.com/c/rnGtb9ww/41-open-opportunities-first-pass

**Checklists:**

FAI enhancements - 

   - [ ] 1. Add a “degree of complexity” field to the “Create an Opportunity Form” to include three choices for the poster to categorize the opportunity: 1) basic learning opportunity; 2) mid-level work; 3) advice/experience needed. - Easily categorizes opportunities to discern level or skill/knowledge required.
   - [X] 2. Add a button to the current Open Opps landing page that allows for filtering all acquisition opportunities.- Fast way to sort opportunities specific to the acquisition community.
   - [ ] 3. Add a drop down menu for selecting which “high level” competency is mapped to the opportunity, using the 10 technical and 1 professional competency units. - Allows searching for opportunities based on high level competencies.
   - [ ] 4 Add a field to the “Create an Opportunity Form” to capture CLPs to be earned for the opportunity. Develop a “certificate” that can be released that identifies the CLPs earned. Request for an increase of the current 20 CLP yearly limit for experiential learning to 40 CLPs. - Provides motivation to participate in appropriate Open Opp tasks, and provides the ability to earn CLPs by participating in hands on learning.
   - [X] 5. Add an optional box on the member profile page that communicates the individual’s interests/desired opportunities. - Users could view other profiles to identify potential applicants or determine if there is interest among the community for a particular type of opportunity.
   - [ ] 6. Add a field to the member profile that allows individuals to sign up for push-notifications for new acquisition opportunities as they are posted. - Provides a daily or weekly alert when new opportunities are posted to eliminate the need for individuals to continually check the site.
   - [X] 7. Develop a dashboard that will identify which agencies are using the site as a task creator and as a participant. Metrics will show agency participation and help encourage usage.
   - [ ] 8 Add a field to the profile page that includes supervisor “approval” or “endorsement”. - Allows posters to see that potential participants have the backing of their supervisor.

**Attachments:** 

[openopps-mockups.sketch](https://trello-attachments.s3.amazonaws.com/5623ffeeee531d25521a97ba/597b37daf1e92f30e110de38/ced9c231ec725f10554c52d2e18e2b6a/openopps-mockups.sketch)

[Open Opportunities.zip](https://trello-attachments.s3.amazonaws.com/5623ffeeee531d25521a97ba/597b37daf1e92f30e110de38/9f4017581ffc40fc34bd3adb0735069e/Open_Opportunities.zip)

[Open OPS OPM_7600A&B_$210,000_Open Opportunities_Signed.pdf](https://trello-attachments.s3.amazonaws.com/5623ffeeee531d25521a97ba/597b37daf1e92f30e110de38/83d9ed39a5039ab7073267bb1d2d580c/Open_OPS_OPM_7600A%26B_%24210%2C000_Open_Opportunities_Signed.pdf)

[Open OPS FY17 Service Level Agreement between GSA FAI and USAJOBS Program Office_FINAL.pdf](https://trello-attachments.s3.amazonaws.com/5623ffeeee531d25521a97ba/597b37daf1e92f30e110de38/5abeb4a1363fb44319638d7a6d57eae1/Open_OPS_FY17_Service_Level_Agreement_between_GSA_FAI_and_USAJOBS_Program_Office_FINAL.pdf)

[DoD](https://trello-attachments.s3.amazonaws.com/5623ffeeee531d25521a97ba/597b37daf1e92f30e110de38/605a69422c7f84ce01c037adf2556eed/Screen_Shot_2017-08-21_at_12.13.01_PM.png)

[openopps-mockups.sketch](https://trello-attachments.s3.amazonaws.com/5623ffeeee531d25521a97ba/597b37daf1e92f30e110de38/4920cd6a856f606113e48a01a2d37e93/openopps-mockups.sketch)

[Open Opportunities Emails - 2015-Feb-03.pdf](https://trello-attachments.s3.amazonaws.com/5623ffeeee531d25521a97ba/597b37daf1e92f30e110de38/f7922d4b8879f791007bb2089e63eb71/Open_Opportunities_Emails_-_2015-Feb-03.pdf)

**Comments:**

**Comment by humancompanion** [comment]
We're well past this at this point.
