### ISSUE TITLE
Rework Help Desk (Footprints) processes

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#4]
**Old Trello URL:** https://trello.com/c/tIf0gHJv/287-rework-help-desk-footprints-processes

**Checklists:**

**Attachments:** 

**Comments:**

*Katrina Wagner 2018-06-26*: Intern will be working on.

*Katrina Wagner 2018-06-05*: 1) how often to check
2) who checks
3) Canned responses

**Comment by kbwagner** [comment]
@tlorrison do we have a date when Open Opps Footprints will be moved to Macon?
