### ISSUE TITLE
Federal career portal

### ISSUE THREAD

**Issue by yraza261** [openopps/OpenOppsTasks#40]
Answer these questions with the team before proceeding.

### What problem does it solve?
Write a problem statement. Look for one on the problem roadmap or add it: https://github.com/USAJOBS/american-discovery-trail/wiki/problem-roadmap

### How does it affect the user?
Who are the users and what are their goals? Every element in your design should be justified by a user need or goal.

### Why is it better than the alternative?
Why are we choosing to solve the problem this way. Perhaps you don't know yet how it will be solved in which case define the variations you want to explore. Capture your assumptions!

### Relevant Research
Locate and read existing research related to this problem.

### Create a hypothesis
Once you have the above, create a hypothesis that you want to validate. 

Here is a template:
We believe that...[hypothesis]. We will do/make...[what we're going to test]. We will know the hypothesis is valid if by [date] we get [quantitative measurable outcomes] and [qualitative observable outcome].

## Entrance criteria
* Items from the impact map or problems from the problem roadmap have been prioritized into this queue.

## Exit criteria
* The team agrees on the hypothesis you are going to measure your success against.

**Old Trello URL:** https://trello.com/c/AuVZjhc2/37-federal-career-portal

**Checklists:**

Checklist - 

   - [ ] Finish Developmental Opportunities content audit
   - [ ] Interview Michelle Earley (and others) to nail down some requirements and understand her vision for the "Federal career portal"
   - [ ] Work with Julie to setup a survey and/or interviews with new and seasoned Federal Employees
   - [ ] Federal employee experience map (focus on career development)

**Attachments:** 

[USAJOBS Vision_May 2017.pptx](https://trello-attachments.s3.amazonaws.com/5623ffeeee531d25521a97ba/5981db255600827fb55b05c4/00a46458c843dedf13d8980f7dba9366/USAJOBS_Vision_May_2017.pptx)

[USAJOBS Strategic Framework - Ideation_June 2017.xlsx](https://trello-attachments.s3.amazonaws.com/5623ffeeee531d25521a97ba/5981db255600827fb55b05c4/17970d2b695966f3d59e120f9462042a/USAJOBS_Strategic_Framework_-_Ideation_June_2017.xlsx)

[USAJOBS Impact Mapping_April 2017.pdf](https://trello-attachments.s3.amazonaws.com/5623ffeeee531d25521a97ba/5981db255600827fb55b05c4/0fb4010bd6a2ddacb81ee03f54573fa0/USAJOBS_Impact_Mapping_April_2017.pdf)

**Comments:**

**Comment by humancompanion** [comment]
Moved to North Star: https://github.com/USAJOBS/team-design/issues/13
