### ISSUE TITLE
Research career paths

### ISSUE THREAD

**Issue by yraza261** [openopps/OpenOppsTasks#41]
We need to do a bit of research on how OPM defines career paths.

**Old Trello URL:** https://trello.com/c/ZolGgl3A/36-research-career-paths

**Checklists:**

Checklist - 

   - [ ] Talk to April Davis on how OPM defines career paths
   - [ ] Talk to Leslie Pollack in HRS on how they define career paths
   - [ ] Talk to USA Learning - Will Parantino and Paul Jesukiewicz - they have plans to produce something that could be used with USAJOBS profiles

**Attachments:** 

**Comments:**

**Comment by humancompanion** [comment]
Moved to North Star: https://github.com/USAJOBS/team-design/issues/14
