### ISSUE TITLE
Create Operational Model Outline

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#47]
Discussed in 1/25/18 BA/Design meetup.  Michelle suggested.  

**Old Trello URL:** https://trello.com/c/OyZsKb1J/136-create-operational-model-outline

**Checklists:**

**Attachments:** 

**Comments:**

**Comment by kbwagner** [comment]
@tlorrison I think this is OBE...can this be closed?

**Comment by tlorrison** [comment]
@sean-lewis I don't know what this item is regarding...can you please enlighten me?

**Comment by kbwagner** [comment]
@tlorrison I think we close this at this point unless you know of a new request for this?

**Comment by tlorrison** [comment]
I am not sure what this is, so…we can close it and open a new ticket if necessary.
