### ISSUE TITLE
Discuss Adding Open Opps Data into Data Warehouse

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#48]
**Old Trello URL:** https://trello.com/c/bZWPLY1N/137-discuss-adding-open-opps-data-into-data-warehouse

**Checklists:**

**Attachments:** 

**Comments:**

**Comment by kbwagner** [comment]
@tlorrison - I think a meeting to discuss this issue should happen before we decide on the dashboard.

**Comment by tlorrison** [comment]
I spoke with Michelle about this. For the time being, we’ll proceed with building out our “dashboards” in Open Opps. If we have to change course in the future/migrate the data elsewhere, we’ll deal with it then.

**Comment by kbwagner** [comment]
@tlorrison should I close this or leave it open for future discussion?

**Comment by tlorrison** [comment]
You can leave it open – can’t say we’ll deal with it anytime soon, but it’s still a need.
