### ISSUE TITLE
Communications: Schedule Monthly Online Office Hours for Open Opps beginning Nov. (skip Dec)

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#49]
**Old Trello URL:** https://trello.com/c/i8JBhrpe/180-communications-august-and-september-online-office-hours-for-open-opps

**Checklists:**

Checklist - 

   - [ ] Choose dates and times
   - [ ] Schedule Adobe sessions via Lisa
   - [ ] Publicize each session at least two weeks prior to date in Open Opps weekly newsletter AND the week of the session.
   - [ ] Ask Anne to share information in Acq newsletter at least two weeks prior and week of session.   Anne Reinhold - M1V1B <anne.reinhold@fai.gov>

**Attachments:** 

**Comments:**

**Comment by Piglady64** [comment]
Do you need to use Adobe for this? Is that why you assigned it to me?

**Comment by abudz19** [comment]
@Piglady64 How far in advance can I schedule these?

**Comment by Piglady64** [comment]
I am assuming you need the Adobe 500 account. I should be able to book whatever you want. Just give me the dates and I will let you know how far I was able to book

**Comment by abudz19** [comment]
@LisaLNelson do we need the 500 account for this? How many people usually sign in?

**Comment by abudz19** [comment]
@LisaLNelson Also, I think since this is engagement work it makes more sense to be in the [Engagement Team repo](https://github.com/usajobs/team-engagement#boards?repos=143051048)

**Comment by abudz19** [comment]
ticket now at https://github.com/USAJOBS/team-engagement/issues/63
