### ISSUE TITLE
Move Lisa's files to share drive.

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#5]
**Old Trello URL:** https://trello.com/c/3j1jv0dM/275-move-lisas-files-to-share-drive

**Checklists:**

**Attachments:** 

**Comments:**

*Lisa Nelson - XC0D 2018-06-26*: I think this is going to have to be as needed.  I can't just add the zip files as it would add a lot of info that is not relevant.

**Comment by LisaLNelson** [comment]
completed
