### ISSUE TITLE
Participants miss that they have access to the task creators email address in their profile and that there is a comment box at the bottom for questions.  This could e something for the Q&A.  How do I get in touch with the Opportunity Creator.

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#53]
**Old Trello URL:** https://trello.com/c/O1NMt8tO/235-participants-miss-that-they-have-access-to-the-task-creators-email-address-in-their-profile-and-that-there-is-a-comment-box-at-t

**Checklists:**

**Attachments:** 

**Comments:**

**Comment by kbwagner** [comment]
6/4/19 - Participants can click on the creator's picture to open their profile where the email address is displayed for contact.
