### ISSUE TITLE
Revise People page

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#55]
Michelle is concerned that we not expose too much PII on the People page when we revise and have a shared Profile. Thus we need to rethink the person component on the People page. Might be a good time to introduce some of the concepts that Jaryn and Jen introduced.

No due date yet as this work would follow the State work.

People Page in NorthStar: https://opm.invisionapp.com/d/main#/console/16603537/344286038/preview

**Old Trello URL:** https://trello.com/c/vF3pMLPv/278-revise-people-page

**Comment by humancompanion** [comment]
@mchung07 has a design for this:
https://opm.invisionapp.com/d/main/#/console/16603537/344286038/preview

This is definitely an area worth testing and iterating on. As an aside, visually I'm still not super psyched with the intensity of the skills tags components. But the pagination, result card, filtering options, and revised badges are all headed in the right direction.

**Comment by kbwagner** [comment]
Implementing People revamp from North Star with Release 7.9
