### ISSUE TITLE
Help: Add Acquisition content

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#60]
Lisa shared via google drive a few docs that need posting.

**Old Trello URL:** https://trello.com/c/IJ8rg8S5/260-help-add-acquisition-content

**Checklists:**

Checklist - 

   - [ ] Sample Acquisition Open Opportunities
   - [ ] 1 pager PDF

**Attachments:** 

[Acquisition Open Opportunities Samples _April2018 discussion paper.docx](https://trello-attachments.s3.amazonaws.com/59df9ff7b7b887ebae452662/5afb4f522b8a6c84c7922d3c/908e9dd4d7b27f640e3fe0959e78e432/Acquisition_Open_Opportunities_Samples__April2018_discussion_paper.docx)

**Comments:**

*Katrina Wagner 2018-06-19*: @lisanelsonxc0d what is that status of this card?

*Debbie LeNard 2018-06-04*: @lisanelsonxc0d @katrinawagner @minchung12 

We pushed a new help center page for "sample opportunities".  It's here:

https://usajobs.github.io/openopps-help/opportunity/sample-opportunities/

These  examples were pulled from the Acquisition examples.  I only posted ones that seemed to work for any field, not just acquisitions.

I also added a link to the examples on the How to create an opportunity page.  It's in the 'Before you get started' section.

@lisanelsonxc0d - I think Acquisitions can point people to this page for example opportunities.  

@minchung12 and I spoke and we think the newsletter might be a great way to provide the full list of Acquisition examples.

**Comment by humancompanion** [comment]
Low priority. Debbie to talk to Tracy about whether or not this is done, or if there are remaining tasks.

**Comment by kbwagner** [comment]
6/4/19 - Closing - community specific content will not be in the help desk.
