### ISSUE TITLE
Finish updating dashboard tickets?

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#62]
**Old Trello URL:** https://trello.com/c/U60mzprr/296-finish-updating-dashboard-tickets

**Checklists:**

**Attachments:** 

**Comments:**

*Katrina Wagner 2018-07-03*: Update with answers to questions

*Katrina Wagner 2018-07-02*: These are complete, however, have open questions we need to discuss.

**Comment by humancompanion** [comment]
@kbwagner - I'm doing some task grooming. Can we close this? It came from the old Trello board. If we can't close it can you add details about what this is tracking? Thanks.

**Comment by kbwagner** [comment]
@humancompanion nope we still need to get the dashboard tickets updated.  
I can'update this but probably not this week.  I'm the only assignee so I will make sure I keep up with it.  Just not going to get back to the dashboard tickets soon

**Comment by kbwagner** [comment]
Completed September 2019.
