### ISSUE TITLE
Help Center Rework

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#64]
1) Reexamine What's new and context summary
2) Need to have a place where customers can post supporting documentation (i..e. Acquisition samples)
- what is the status of microsites? are they available?  Would that work for FAI?
- would files need to be downloaded
3) overall structure

**Old Trello URL:** https://trello.com/c/PukxhaMN/302-help-center-rework

**Checklists:**

**Attachments:** 

**Comments:**

*Katrina Wagner 2018-06-26*: @tracyorrison and @lisanelsonxc0d to meet with Michelle on microsite potential.

**Comment by humancompanion** [comment]
@tlorrison - Did Michelle, Lisa, and you meet to discuss microsites? Are we building one for FAI? If so, when is the target date? 

Is there actual Help Center rework to be done here?

**Comment by humancompanion** [comment]
@tlorrison or @kbwagner - Is there an ask here or should I just close this?

**Comment by kbwagner** [comment]
@humancompanion the orignal ask was how can we store Acquisition content somewhere where only acquisitions can see it.  I think the answer is if you want it somewhere not everyone can see it then it needs to be a microsite.  IF that's the case, this can be closed 
BTW - a lot of things on this board are just action items for the project team and not design so you can definitely ignore a lot of these

**Comment by humancompanion** [comment]
Yes, the Help sites don't have a way to keep someone from seeing content if they have the URL. That said, we don't have to provide navigation between content that is unrelated. For example, if we post content that is only relevant to State Dept. and some that is only relevant to FAI that content can live under the same Help repo/site but not link. Thus we could make it unlikely that a user in agency A would stumble upon the content intended for a user in agency B.
