### ISSUE TITLE
Develop and manage contest for Acquisition community.

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#67]
Contest to encourage the posting of acquisition open opportunities. The agency/department who posts the most opportunities will be sent by OMB's OFPP to ACT-IAC’s Executive Leadership Conference in Philadelphia.  That person will get recognized at the conference.

**Old Trello URL:** https://trello.com/c/hcOm4wK1/242-develop-and-manage-contest-for-acquisition-community

**Checklists:**

Contest plan - 

Run contest - 

**Attachments:** 

[Acquisition Open Opportunities Contest_May 9 2018 draft3.docx](https://trello-attachments.s3.amazonaws.com/59df9ff7b7b887ebae452662/5ae872993dc6140acd67c3bc/9b60d883b490b597caf5f83a64509ac0/Acquisition_Open_Opportunities_Contest_May_9_2018_draft3.docx)

[ACQUISITION OPEN OPPORTUNITIES CONTEST_14May2018_Draft2.docx](https://trello-attachments.s3.amazonaws.com/59df9ff7b7b887ebae452662/5ae872993dc6140acd67c3bc/37384a618c56f5f4503ac2d374c764a8/ACQUISITION_OPEN_OPPORTUNITIES_CONTEST_14May2018_Draft2.docx)

**Comments:**

*Lisa Nelson - XC0D 2018-06-05*: [ACQUISITION OPEN OPPORTUNITIES CONTEST_14May2018_Draft2.docx](https://trello-attachments.s3.amazonaws.com/59df9ff7b7b887ebae452662/5ae872993dc6140acd67c3bc/37384a618c56f5f4503ac2d374c764a8/ACQUISITION_OPEN_OPPORTUNITIES_CONTEST_14May2018_Draft2.docx)

**Comment by LisaLNelson** [comment]
Completed.
