### ISSUE TITLE
State: Update Create unpaid internship opportunity page

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#7]
**Old Trello URL:** https://trello.com/c/Mk7XWnND/311-state-update-create-unpaid-internship-opportunity-page

**Checklists:**

Checklist - 

   - [ ] Create
   - [ ] Preview
   - [ ] Create - choose audience

**Attachments:** 

**Comments:**

**Comment by humancompanion** [comment]
Min has done this and there is a new card for it.
