### ISSUE TITLE
Develop a strategy for the Announcement section of the landing page.

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#71]
We need to have a strategy for keeping the content fresh.
- How often should we change the content? 
- What might we include if there are no major announcements? New opportunities?Other?
- Should we change the name from Announcement to something more social? How about What's new? 

**Old Trello URL:** https://trello.com/c/WrLEh0dx/261-develop-a-strategy-for-the-announcement-section-of-the-landing-page

**Checklists:**

**Attachments:** 

[Open-Opportunities-announcement-area-strategy_20180628.docx](https://trello-attachments.s3.amazonaws.com/59df9ff7b7b887ebae452662/5afb854930cc24f2450d120d/54d8982b1244c4422685f178858dbde4/Open-Opportunities-announcement-area-strategy_20180628.docx)

**Comments:**

*Lisa Nelson - XC0D 2018-06-26*: @katrinawagner meeting scheduled with Debbie 6/27.

*Katrina Wagner 2018-06-26*: @lisanelsonxc0d to set up a meeting to discuss questions and move this forward.

*Debbie LeNard 2018-06-05*: @lisanelsonxc0d @minchung12 

Before we start deciding how often this content gets updated, let's define the purpose of this "Announcement" section.

A few questions to get started.

1. What is the purpose of the “announcement area”?  
2. What information do you want to highlight here?  
3. Why do we need this content? 
4. Who is the audience of this content?
5. What do we want users to do with this content?

Some of these questions overlap, but if we can define the purpose of this section, that will help drive the strategy for keeping it fresh and knowing what needs to go there.

**Comment by humancompanion** [comment]
Kinda has been dropped. Waiting to hear.

**Comment by kbwagner** [comment]
@LisaLNelson @tlorrison I believe this one can be closed.  Lisa plans on updating this content in production at least every two weeks.  Can this be closed?

**Comment by LisaLNelson** [comment]
completed
