### ISSUE TITLE
Login.gov Learn More info for help center

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#73]
**Old Trello URL:** https://trello.com/c/KblqNZdQ/314-logingov-learn-more-info-for-help-center

**Checklists:**

**Attachments:** 

**Comments:**

*Katrina Wagner 2018-07-26*: @debbielenard yes...sorry..threw the card in and then got disctracted.
Yes...we need a page that will be linked to when "Learn more" is selected from yellow banner saying there is a new way to login from Open Opps.
- The content can be the same as what's in USAJOBS but geared to Open Opps.
Mock for yellow bar with Learn More link: https://opm.invisionapp.com/d/main#/console/14593252/310828323/preview

For the ticket, I'll just need the help center link to where it will be housed.  It will go into this new sprint so if I can get a link no later than 8/8.

*Debbie LeNard 2018-07-26*: @katrinawagner are you talking about using this content but just updating it to say open opps instead?  And putting it into the open opps help center?https://www.usajobs.gov/Help/faq/account/login-gov/

**Comment by dalenard21** [comment]
@kbwagner @minchung12 @tlorrison 
[Open-opportunities-help-center-what-is-login-gov_20180802.docx](https://github.com/openopps/openopps-design-team/files/2254948/Open-opportunities-help-center-what-is-login-gov_20180802.docx)


Here's my first draft for the 'learn more about login.gov' for the Open Opportunities help center. I've changed it from USAJOBS, because we have to explain that they need a USAJOBS profile now and we'll be linking all of it to one profile. 

Please review and let me know if it makes sense or if there are changes/edits. 

The URL will be: /openopps-help/account/login-gov

**Comment by kbwagner** [comment]
@Lforeman22 any chance you could take a stab at reviewing Debbie's document attached?

**Comment by Lforeman22** [comment]
Hey Katrina,

Yes, I can do this. I have finally been unblocked from my computer and have full access again.

Very Respectfully,

Lauren A. Foreman
Management & Program Analyst
Office of Personnel Management
USAJOBS
Cell: 202-270-8595
Lauren.foreman@opm.gov<mailto:Lauren.foreman@opm.gov>
https://www.usajobs.gov/

[USAJOBS]<https://www.usajobs.gov/>

**Comment by Lforeman22** [comment]
@kbwagner  @dalenard21 I looked over the Help Center Content for Open Opps in reference to Login. Everything looks good on my part. I just thought one thing was missing. Can we address, if someone cant link their accounts? Not sure if we should address this. But aside from that, everything looks good.

**Comment by dalenard21** [comment]
@Lforeman22 @kbwagner @minchung12 

Yes, I can add an 'faq' for if they can't link their accounts.  But, do we know what happens?  Thanks!

**Comment by dalenard21** [comment]
@Lforeman22 @kbwagner @mchung07 just following up on this. I want to start getting the content into Github.  I can add the content with the FAQ about issues with linking their account, but do one of you knows what happens or what we can tell the user?

On USAJOBS, we have this content: https://www.usajobs.gov/Help/faq/account/no-profile/  I'm not sure if this is the same solution for Open Opps?  We could just link people to this help article.  Let me know what you think.

**Comment by dalenard21** [comment]
Based on meeting with @kbwagner and @Lforeman22 here's an updated version of the "Learn more about login.gov" help center page. Please review and if it's okay, I'll create the page in GitHub.

[Open-opportunities-help-center-what-is-login-gov_20180920_v3.docx](https://github.com/openopps/OpenOppsTasks/files/2401711/Open-opportunities-help-center-what-is-login-gov_20180920_v3.docx)

**Comment by Lforeman22** [comment]
@dalenard21 Took a look and everything looks good to me. Thanks for adding that if they can't find their account or link it, they will just have to create a new one. @tlorrison This is ready for your review.

**Comment by KatMullens-work** [comment]
I just looked at the document. you can now add two phone lines to your login.gov account. This is a great step for those who are in SCIFs, etc. You might want to add that you can add up to two phone numbers (or for existing users who don't know, add a second number). @dalenard21

**Comment by KatMullens-work** [comment]
@dalenard21 we might also want to update the existing article with this information. It's a big win for a decent sized slice of our users!! :)

**Comment by dalenard21** [comment]
@KatMullens-work that's great. I'll update this page and our existing help content too.  Thanks.

**Comment by dalenard21** [comment]
This page is now in production in Open Opps help center.

https://usajobs.github.io/openopps-help/account/login-gov/

Issue closed.
