### ISSUE TITLE
login.gov: Email all users

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#74]
https://github.com/openopps/openopps-platform/issues/2425
User Story: As an Open Opportunities user, I want to be notified that the way I log in will be changing.

**Old Trello URL:** https://trello.com/c/Dp1TGjhy/315-logingov-email-all-users

**Checklists:**

**Attachments:** 

**Comments:**

*Min Chung 2018-07-26*: @debbielenard We need your help creating content for this email

This will be ticket 2425 once completed (note for Katrina)

**Comment by dalenard21** [comment]
@minchung12 @kbwagner 

Can one of you give more guidance on what needs to be included in this email?

Does this email go to all current Open Opps users?

Do we want to tell them WHEN the way they sign in is changing?  Or explain the process?  I remember we were going to email USAJOBS users, but I think the email was pretty vague.  I'll see if I can find that email.

**Comment by dalenard21** [comment]
@minchung12 @kbwagner 

I talked to Matt and we never sent an email to USAJOBS users warning them that the way they'll sign is was going to change.  We just waited until we made the change on the site.

Do we really need to email Open Opps users that the sign in process will change?

**Comment by kbwagner** [comment]
@minchung12 @tlorrison @dalenard21  - I thought that we decided at Excella not to do this?  I know that's when it came up that we didn't do it for Core.  

@tlorrison  - decision point - do we want to send an email to all Open Opps users to let them know that the way they log in will change?

**Comment by tlorrison** [comment]
Yes, we do want to send a notification to existing open opportunity users a few days prior to the switch. We didn’t do it for JOBS because of the sheer number of people it impacted and the complications it would have caused if they did it early.

**Comment by kbwagner** [comment]
I looked at my notes on this issue and have the following which made me think that we decided to ask the Core team to send this email out???  

send email to all current users to let them know login.gov is coming
Send email a few days before login.gov is deployed.
link them to the help center content on login
Need content for email
Provide list of users to USAJOBS - create footprints ticket to send through USAJOBS

@dalenard21 I think that may answer a few of your questions as to when and who.  I'm not sure we can really give a date yet but likely now mid September.  Providing a link to the help center to give more info.  So I think it's yes a somewhat vague email and pointing them to more info elsewhere.  I'll ask about this email in scrum this morning to see if we can get clarification on how it gets sent out.

**Comment by dalenard21** [comment]
@kbwagner @tlorrison @minchung12 

Here are two variations of the email to send to all Open Opps users about the upcoming switch to login.gov.

Variation A is very generic. It doesn't mention login.gov at all. It just tells them there will be a new way to sign in.  This was the version USAJOBS was going to send, but never did (at least I don't think they did).

Variation B tells the users about login.gov.  It includes a link to 'learn more' which would go to the page in the help center we're creating to talk about login.gov and what they need to do.  The concern with this approach is if users go to login.gov website and create an account ahead of time.  Maybe some already have an account because they did this with USAJOBS.  Will either scenario cause an issue in linking their Open Opps profile?

I also put a few comments in the docs.  These versions are starting points. I can update based on what we want to communicate to the users.

[Open-opportunities-login-gov-coming-soon-email_variationA_20180807.docx](https://github.com/openopps/openopps-design-team/files/2275254/Open-opportunities-login-gov-coming-soon-email_variationA_20180807.docx)
[Open-opportunities-login-gov-coming-soon-email_variationB_20180807.docx](https://github.com/openopps/openopps-design-team/files/2275255/Open-opportunities-login-gov-coming-soon-email_variationB_20180807.docx)

**Comment by kbwagner** [comment]
@Lforeman22 - want to take a stab at this review too?

**Comment by Lforeman22** [comment]
Sure thing!

Very Respectfully,

Lauren A. Foreman
Management & Program Analyst
Office of Personnel Management
USAJOBS
Phone: 202-418-3156<tel:202-418-3156>
Cell: 202-270-8595<tel:202-270-8595>
Lauren.foreman@opm.gov<mailto:Lauren.foreman@opm.gov>
https://www.usajobs.gov/

On Aug 9, 2018, at 2:04 PM, Katrina Wagner <notifications@github.com<mailto:notifications@github.com>> wrote:


@Lforeman22<https://github.com/Lforeman22> - want to take a stab at this review too?

-

**Comment by Lforeman22** [comment]
@kbwagner @dalenard21 Hey Ladies, for what ever reason when I started replying to you on Github it wouldnt allow me to tag you.
Nonethless, i like the more generic version of the email you drafted @dalenard21. I think it will stop folks from creating a login account ahead of time, and possibly confusing themselves.
I don't think we should send an additional email. I think we should put in that email, that when the new way to login becomes available, that we will walk them through the process. Just my 2 cents.
Let me know.

**Comment by dalenard21** [comment]
Thanks for the feedback @Lforeman22 

Here's an updated version of the 'generic' email.

Does @tlorrison need to review this as well?
[Open-opportunities-login-gov-coming-soon-email_variationA_20180813_v2.docx](https://github.com/openopps/openopps-design-team/files/2283735/Open-opportunities-login-gov-coming-soon-email_variationA_20180813_v2.docx)

**Comment by dalenard21** [comment]
@tlorrison just following up on this. Have you had a chance to review the 'coming soon' email?  It's attached to this GitHub issue.  Please let me know if you have edits.

**Comment by kbwagner** [comment]
@tlorrison - can you take a look at this when you have a chance so we can have it ready and waiting?

Open-opportunities-login-gov-coming-soon-email_variationA_20180813_v2.docx

Is this a new ticket on Atlas?  Or is this the one where we extract out all of our users and create a Footprints ticket?

**Comment by kbwagner** [comment]
@tlorrison @Piglady64 @dalenard21 with login.gov coming up with the next release, we probably need to revisit this.

**Comment by Piglady64** [comment]
Open Opps ticket #2425

This is on hold pending @tlorrison review and approval.

**Comment by tlorrison** [comment]
@dalenard21 I think it may be best to tell users that they don't need to do anything now, as when we switch to one profile, any changes users make in USAJOBS will over-write updates they may make in Open Opps. If you'd like me to take a stab at editing the message, just let me know. The message should be more of a heads up that a new way to login in is coming. (@Piglady64 for awareness)

**Comment by dalenard21** [comment]
@tlorrison if you still want to email users, here's a shortened version of the message.  Feel free to edit to how/if you want to message users.

Email Subject Line: Open Opportunities update - A new way to sign in.
Email body copy:

Hello [Guest Name],

In a few days, Open Opportunities is changing the way you’ll sign in, making it easier and more secure.

**What do I need to do?**
You don’t need to do anything just yet. Once we make the change, we’ll walk you through the new process when you sign in.

Thanks, 

The Open Opportunities Team
U.S. Office of Personnel Management
1900 E Street NW. Washington, DC 20415

**About this message**
You received this email because you signed up for Open Opportunities.

Have questions or comments? Check out our help center or email us at OpenOpps@usajobs.gov.

To make sure you get Open Opportunities emails to your inbox (and not your spam) add 'noreply@openopps.uat.usajobs.gov' to your address book.

**Comment by dalenard21** [comment]
Need to add more information to this email - work with @KatMullens-work @tlorrison @LisaLNelson 

Things to add:

* Info about moving their "Bio"
* Adding and validating their federal email address to their federal service experience section (of their USAJOBS profile)
* What about current Open Opps users who don't have a USAJOBS profile?  Do we want to tell them to create one before May 17?

**Comment by dalenard21** [comment]
@tlorrison @KatMullens-work @LisaLNelson 

I have two versions.

Version A covers:

* Something's changing on May 17
* Copy your Bio
* Update your USAJOBS profile if you have one 
* Don't worry if you don't have a USAJOBS profile - we'll help you out after May 17

Version B covers:

* Somethings changing on May 17
* Copy your Bio
* Don't do anything else, we'll help you out on May 17.

The approach depends what and when you want to communicate these things. I didn't mention login.gov in either version - just said there's a new way to sign in. 

Version A - If a user already has a USAJOBS profile, I think it's okay to recommend they add their Bio info and their federal agency/email before May 17. But, not sure how you want to handle users with no USAJOBS profile. 

Version B - Minimal approach.  

HOpe this is enough to start discussion and iterate.

[Open-opportunities-login-gov-one-profile-coming-soon-email_variationA_20190502_v3.docx](https://github.com/openopps/OpenOppsTasks/files/3139432/Open-opportunities-login-gov-one-profile-coming-soon-email_variationA_20190502_v3.docx)
[Open-opportunities-login-gov-one-profile-coming-soon-email_variationB_20190502_v3.docx](https://github.com/openopps/OpenOppsTasks/files/3139433/Open-opportunities-login-gov-one-profile-coming-soon-email_variationB_20190502_v3.docx)

**Comment by KatMullens-work** [comment]
Did we decide which version we're using @tlorrison @LisaLNelson @dalenard21 ?

**Comment by dalenard21** [comment]
@tlorrison @LisaLNelson @KatMullens-work @kbwagner @Piglady64 

Do you have any feedback or preference for the email options above?  Please see the previous comment that has two versions attached.

We need to make a decision on which one you want to send out, update it with changes if needed and decide when the email will be sent. 

Who is taking the lead on this email communication? Right now I have lots of people 'assigned'. I'm happy to take people off, but I don't know who needs to approve this and get it over to Dev so it can go out to all Open Opps users.

**Comment by tlorrison** [comment]
@dalenard21 @kbwagner @Piglady64 @LisaLNelson I personally like B, but we haven't really discussed who makes the final call on what/when something is sent. We'll discuss in our 1:00 PM meeting tomorrow and move forward from there. I'm discussing what we need to do to send with Brice from a technical perspective.

**Comment by LisaLNelson** [comment]
@dalenard21 @kbwagner @Piglady64 We need to send the most comprehensive email out.  I believe that a significant portion of our users will not have a USAJOBS account and we will need to give them as much info as possible to make a smooth transition.

**Comment by dalenard21** [comment]
@LisaLNelson @tlorrison 

Here is an updated version of the 'changes coming soon' email for Open Opportunities.  Julie reviewed it as well.  It covers the topics we talked about during yesterday's meeting.  Please review and if this is good to go, let's send to Kat so she can base the 'newsletter' article off of it.

[Open-opportunities-login-gov-one-profile-coming-soon-email_variationA_20190509_v4.docx](https://github.com/openopps/OpenOppsTasks/files/3166647/Open-opportunities-login-gov-one-profile-coming-soon-email_variationA_20190509_v4.docx)

**Comment by KatMullens-work** [comment]
Is this approved @tlorrison @LisaLNelson ? (Bugging you since Debbie is out today :) )

**Comment by dalenard21** [comment]
@Piglady64 @tlorrison @KatMullens-work @LisaLNelson 

Here is an updated version of the email for all Open Opps users telling them about login.gov, one profile and what they need to do.

@Piglady64 let's use this version for the usability test.

[Open-opportunities-login-gov-one-profile-coming-soon-email_20190531_v7.docx](https://github.com/openopps/OpenOppsTasks/files/3241848/Open-opportunities-login-gov-one-profile-coming-soon-email_20190531_v7.docx)

**Comment by dalenard21** [comment]
@Piglady64 @tlorrison @KatMullens-work @LisaLNelson 

Here is a revised version of the email for all Open Opps users for login.gov, one profile, etc.  This revision includes one edit based on the one person who did the usability test yesterday.

Use this version to help write the newsletter article.

[Open-opportunities-login-gov-one-profile-coming-soon-email_20190604_v8.docx](https://github.com/openopps/OpenOppsTasks/files/3252406/Open-opportunities-login-gov-one-profile-coming-soon-email_20190604_v8.docx)

**Comment by dalenard21** [comment]
@Piglady64 @tlorrison @LisaLNelson 

The email to all open opps users went out yesterday (6/18).  Closing this issue.
