### ISSUE TITLE
Open Opportunities Privacy Impact Assessment

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#76]
**Old Trello URL:** https://trello.com/c/dpkIzwd0/298-open-opportunities-privacy-impact-assessment

**Checklists:**

**Attachments:** 

**Comments:**

*Yusuf Raza 2018-06-28*: Received. Will review today

**Comment by kbwagner** [comment]
@tlorrison - any updates on this?  I can't tag Yusuf since he's not in this repo.

**Comment by kbwagner** [comment]
@tlorrison - can this one be closed?

**Comment by tlorrison** [comment]
All documents in support of the A&A have been submitted
