### ISSUE TITLE
Complete Business Impact Assessment

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#77]
**Old Trello URL:** https://trello.com/c/BuJS2x8C/297-complete-business-impact-assessment

**Checklists:**

**Attachments:** 

**Comments:**

*Katrina Wagner 2018-06-26*: @tracyorrison to determine due date.

**Comment by kbwagner** [comment]
@tlorrison is this still ongoing?  If so, is there a due date?

**Comment by kbwagner** [comment]
@tlorrison - can this be closed?

**Comment by tlorrison** [comment]
All documents in support of the A&A have been submitted
