### ISSUE TITLE
Authority to Operate

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#78]
**Old Trello URL:** https://trello.com/c/JJ0gfEYj/27-authority-to-operate

**Checklists:**

**Attachments:** 

**Comments:**

*Katrina Wagner 2018-06-27*: 6/26/18 - @tracyorrison to check on the status of this.
Last check brice was working on some items for security team.

**Comment by kbwagner** [comment]
@tlorrison Reopening this because it is required for State dept implementation.

Status as of 11/6/18 - this will be contracted out and Quadrina will check on it.  But this means the contract will have to have an RFP...this could take a while and is a concern for the March timeline.

**Comment by kbwagner** [comment]
We have the IATT (interim Authority to Test) but just need the final.

**Comment by tlorrison** [comment]
I have set-up bi-weekly meetings to discuss open POA&Ms with Victor and Todd.

**Comment by kbwagner** [comment]
[OpenOpps 2 Year ATO Memo 20200515.pdf](https://github.com/openopps/OpenOppsTasks/files/4646399/OpenOpps.2.Year.ATO.Memo.20200515.pdf)

Signed 5/15/2020
