### ISSUE TITLE
Create landing page for Help

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#8]
**Old Trello URL:** https://trello.com/c/tvBpI3tP/280-create-landing-page-for-help

**Checklists:**

**Attachments:** 

**Comments:**

**Comment by kbwagner** [comment]
@abudz19 do you know anything about this?  It's very old and was on Min's Trello board.  I'm thinking we just close it unless you know of a plan for the help center

**Comment by abudz19** [comment]
Nope, I don't know anything about this.

**Comment by kbwagner** [comment]
Closing - not enough information on the intent
