### ISSUE TITLE
Open Opps Help Center move to Federalist.

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#80]
**Old Trello URL:** https://trello.com/c/SjfhUbN5/190-open-opps-help-center-move-to-federalist

**Checklists:**

**Attachments:** 

**Comments:**

*Matthew Dingee 2018-07-02*: I raised it with Michelle this morning (we ran out of time during the leadership meeting). I wrote to the cloud.gov support folks and copied Will Slack, per his suggestion. We're unclear whether our current account with cloud.gov allows us to deploy other sites or just Open Opps. IF we can deploy other sites/applications then I just need to get my account associated with the rest of the USAJOBS team (which I also asked them to advise me on) then I'll be able to deploy. After that we can assign a task for the dev team to create a permanent URL for the site and we can point it at the deployed help content.

*Katrina Wagner 2018-07-02*: @tracyorrison making sure you see the message from Matt below on this.  @matthewdingee1 let us know if you need anything from us on this!  Thanks.

*Matthew Dingee 2018-07-02*: Since Fedearlist is stalling I'd like to deploy to cloud.gov and start paying for a minimal install there. That would allow us to point a proper URL there. We've got enough things to deploy there that it would be worth the cost.

**Comment by kbwagner** [comment]
@humancompanion I'm seeing some things in federalists now...does that mean we are moving over to them?

**Comment by dalenard21** [comment]
@kbwagner we're only using Federalist for a 'test site' for Open Opps Help and Core Help.  So, when I update pages in GitHub, we can 'preview' them in Federalist, but they're not linked in production to Open Opps or Core.  I'm not sure where we stand on the move to Federalist for hosting the site completely.

@humancompanion chime in if I'm wrong about this.

**Comment by kbwagner** [comment]
@humancompanion - are there any updates on this?  Something we need to track?

**Comment by humancompanion** [comment]
As of 4/23 Quadrina had not yet filed a request for it and thus there was no progress.

**Comment by kbwagner** [comment]
@humancompanion is this something you think I should leave open to track?  Or just not a big deal...leave it be...and close it?

**Comment by humancompanion** [comment]
You should leave it open and agitate Quadrina and Michelle until you get it. github URLs are a stop-gap solution. They are not official government web sites. I have confidence the CIO will approve our use of Federalist so long as the request reaches her desk.
