### ISSUE TITLE
ask USAJOBS to change "Contracting" to "Acquisitions" or "Acquisitions/Contracting" on their Urgent Hiring Needs page

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#84]
Dan has put this in the backlog for Core/Titan.  TFS 33247

**Old Trello URL:** https://trello.com/c/zEhRwLEp/197-ask-usajobs-to-change-contracting-to-acquisitions-or-acquisitions-contracting-on-their-urgent-hiring-needs-page

**Checklists:**

**Attachments:** 

[UrgentHiringNeedsUSAJOBS_Current.jpg](https://trello-attachments.s3.amazonaws.com/59df9ff7b7b887ebae452662/5ab03c033f91cbd0995e8ba2/aea49b2c193361c8de197f80c3cbb8bf/UrgentHiringNeedsUSAJOBS_Current.jpg)

[USAJOBS_Contracting_Page.jpg](https://trello-attachments.s3.amazonaws.com/59df9ff7b7b887ebae452662/5ab03c033f91cbd0995e8ba2/d41e22c3cc5dee396f772cb4022514cb/USAJOBS_Contracting_Page.jpg)

**Comments:**

*Lisa Nelson - XC0D 2018-06-27*: @katrinawagner @tracyorrison Spoke with Dan and he says that during the Titan team review May 4 the ticket was discussed and removed because it would require a manual update since that page is data driven. This is something you may need to address again because of it's importance to the community.

**Comment by kbwagner** [comment]
@tlorrison - this is an old issue that was closed on the Titan side.  No one from FAI asked us to make this change so I'm inclined to close it since it's not likely to happen anytime soon.  Or, I can keep it open for down the road.  Thoughts?

**Comment by humancompanion** [comment]
Dan's right. They'd need to lobby OPM Policy to change the Series name.
