### ISSUE TITLE
Reach out to Brody on Skills Engine progress

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#85]
Skills Engine has been purchased and it appears there is discussion on how to use the data in the Core product.  Get looped in so we can stay aware on how skills data could be incorporated into Open Opps.

**Old Trello URL:** https://trello.com/c/zcor7nSS/299-reach-out-to-brody-on-skills-engine-progress

**Checklists:**

**Attachments:** 

**Comments:**

*Katrina Wagner 2018-06-26*: 6/26/18 - Tracy will reach out to Brody.  Keep Lisa involved/informed

**Comment by kbwagner** [comment]
Duplicate issue to 44 - closing
