### ISSUE TITLE
Update help content for One Profile Release

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#92]
The following updates should be made to the help content to reflect changes in the system with the One Profile release: 
1) https://usajobs.github.io/openopps-help/opportunity/
Create Opportunity Step 4 - will no longer be saved in profile...will be on signed in landing page.

2) https://usajobs.github.io/openopps-help/assets/Opportunity_Creation_Process_final.pdf
Same as above - create opportunity step 4
- also the screen shot displayed in step 1 is still incorrect although I know Min updated

This is for release 4 with an estimated release date now of mid September. 9/20/18 - One profile is not going live with release 4.  New date TBD.

**Comment by dalenard21** [comment]
@kbwagner @Lforeman22 

Here's an updated version of how to create an opportunity, specifically step 4.  It's a little awkward.

@minchung12 - can you update the pdf?

**Comment by kbwagner** [comment]
See issue #75

**Comment by Piglady64** [comment]
This has been reviewed and will be released with the next release. Waiting on a new release date.

**Comment by dalenard21** [comment]
@abudz19 i just noticed the How to create an opportunity PDF needs to be updated.

Step 4 needs to say: Click **Submit** when you’re ready to post the opportunity. Or, click **Save for later** if you’re not ready to post—we’ll save it as a draft. You can find your drafts under your **Created opportunities** on your home page.

Can you update the PDF? I can upload the updated version.

**Comment by kbwagner** [comment]
@dalenard21 good catch! 
@abudz19 if it's possible to get this updated prior to the release that would be ideal.  I haven't heard any udpates on when that might be yet...still 6/14 with a big maybe beside it?

**Comment by abudz19** [comment]
[Opportunity Creation Process.pdf](https://github.com/openopps/OpenOppsTasks/files/3282050/Opportunity.Creation.Process.pdf)

**Comment by dalenard21** [comment]
@abudz19 @kbwagner I updated the pdf in federalist:

https://federalist-proxy.app.cloud.gov/site/usajobs/openopps-help/assets/Opportunity_Creation_Process_final.pdf

Thanks, I appreciate your help.

**Comment by dalenard21** [comment]
@kbwagner @abudz19 this content has been updated in production.

Issue closed.
