### ISSUE TITLE
Email Content: Confirm Open Opps profile

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#93]
Create email content for when the Open Opps user needs to manually match their Open Opps account to USAJOBS.  
1) user will enter government email address and click "Send email"
https://opm.invisionapp.com/d/main#/console/14593252/311571044/preview#project_console

2) Email will be sent to the entered email address
- need to get some more info from Brice on this.
- Once the user clicks on the link within the email, their Open Opps and USAJOBS profiles will be linked.
- Once the user is signed in they will be taken to the signed in landing page.
- If no matching account, no email is sent.

Issue 2454

Due Date:  TBD - this may go into sprint 5 which starts 8/13 and ends 8/24.

**Comment by dalenard21** [comment]
@kbwagner 

Here are a couple of options. 

**Option 1.** 

Hello [[GivenName]],    

You recently asked to connect your USAJOBS and Open Opportunities profile using this email address. Please click the link below to confirm this is your Federal Government email address and we'll finish the process.

 [[URLLink]]

_Question:_ The screen they enter their gov. email address doesn't really talk about linking their USAJOBS profile and open opps. We mention it earlier, but I wonder if this is the right message.  Is 'connect' the right term?  Thought about 'link', but then we say click on the link below in the following sentence.

**Option 2**

Hello [Given name]

You recently asked to find your Open Opportunities profile using this email address.  Please click the link below to confirm this is your Federal Government email address and verify you have an Open Opportunities profile.

_Question_: Is this the right messaging?  they are trying to manually find their profile.

**Comment by kbwagner** [comment]
@dalenard21 @Lforeman22 Dev is hoping to start this ticket soon.  Thoughts on when the final version might be ready?  I think Lauren provided comments via email but now I can't find the email.

**Comment by Lforeman22** [comment]
@kbwagner 
I think Debbie wanted @tlorrison to take a look at it for final review according to her last message to me on Thursday.

**Comment by dalenard21** [comment]
@kbwagner @Lforeman22 

I'm leaning towards Option 2, but would like Tracy to review.

@tlorrison see the email content options above. I think Option 2 is the right message, but can you please review?

**Comment by dalenard21** [comment]
@tlorrison any update on which email language you want to use?  My vote is Option 2.

cc:; @kbwagner @Lforeman22

**Comment by dalenard21** [comment]
After meeting with @kbwagner we are revising this email to say:

You recently asked to find your Open Opportunities profile using this email address. Please click the link below to confirm this is your email address and verify you have an Open Opportunities profile.

cc: @tlorrison @Lforeman22

**Comment by kbwagner** [comment]
Agreed on content and entered into ticket 2454
