### ISSUE TITLE
State: Create Opportunity page

### ISSUE THREAD

**Issue by mchung07** [openopps/OpenOppsTasks#98]
Modify Create Opportunity with outcomes from usability test and review with State.  See below.

**Comment by mchung07** [comment]
Usability test on 8/30

**Comment by kbwagner** [comment]
From 10/22/18 Usability test review with DOS:
1) For state/end date - modify to display the 3 sets of dates defined by State department so there isn't any confusion

**Comment by kbwagner** [comment]
@abudz19 if you can get your sketch going - can we have this one in place by this Thursday 11/15 for the meeting we have with State?

**Comment by abudz19** [comment]
@kbwagner Yes no problem. 
For (1) Are we talking about specific dates, or just Spring/Summer/Fall
For (2) is there specific language already desired here, e.g. Duty Station, Location of Internship? Or is whatever I choose fine?

**Comment by kbwagner** [comment]
@abudz19 
- Matt was thinking they wanted spring/summer/fall...but then we'll need to find a way to configure start and end dates for each of those which I think we can do in the attribute table.  I'm going to look into that more.
- I think keep it simple like location of internship but yep up to you.  Nothing defined it's just wrong right now
- there may have been more things I didn't capture from that meeting but those are the two I caught.

**Comment by abudz19** [comment]
1. Added radio buttons for Fall/Spring/Summer with corresponding dates beneath. 
2. "Where can participants be located?" to "Where is the internship located?" 
3. Removed "include a specific skill or outcome" from Title instructions. 

https://opm.invisionapp.com/share/UHNZS9XEYR8#/319309731_Create_-_Unpaid_-Desktop-

**Comment by Piglady64** [comment]
Thanks Alex

**Comment by kbwagner** [comment]
@abudz19 @Piglady64 the only issue I see with displaying the dates is that we will have to update them every year.  I have a separate ticket to find a place to have them loaded in the site so we can post and pull down the internships based on the date.  Thoughts?

**Comment by Piglady64** [comment]
@abudz19 @Kbwagner let's ask them this question tomorrow.  We will need to come up with a solution together that will make this as easy as possible to manage.

**Comment by abudz19** [comment]
Are there other ways that they will have to interact with us on a yearly basis, or is the loading of the dates the only thing? I'd argue for removing it, it's one less thing they won't have to remember to send us.

**Comment by kbwagner** [comment]
@abudz19 @Piglady64 I can't think of anything else that will change yearly.  So yes tomorrow we can explain we'll have a place on their administrator dashboard where we can enter the dates yearly but yes would say we remove it from here.  it can stay for tomorrow no worries and yes we can discuss with them.  thanks!  Glad you got your access!

**Comment by abudz19** [comment]
@kbwagner re: radio button vs. dropdown, are we switching back to radio buttons?

**Comment by abudz19** [comment]
@kbwagner I meant for the create screen, when they choose federal or student. Below that is a list of programs, which were radio buttons and then became a drop down.

**Comment by kbwagner** [comment]
@abudz19 got it - I emailed that question to Brice to get clarification

**Comment by kbwagner** [comment]
Per Brice: we chose to do a drop-down because this is an ever expanding list. So at some point if we actually build a product agencies want to use and we have multiple communities this list could potential contain 10 or more options. So instead of having to one day do a production code change to handle the dynamically growing list we have already take the time to code for scalability.

**Comment by kbwagner** [comment]
Per Brice: we chose to do a drop-down because this is an ever expanding list. So at some point if we actually build a product agencies want to use and we have multiple communities this list could potential contain 10 or more options. So instead of having to one day do a production code change to handle the dynamically growing list we have already take the time to code for scalability.

**Comment by humancompanion** [comment]
Yes, and hell could freeze over. This is classic over engineering. Build to
what you have not what might be.

**Comment by kbwagner** [comment]
@abudz19 I think this one can be closed?
